///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SolidWorksTaskPaneTools
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseActiveSolidWorksDocument recording.
    /// </summary>
    [TestModule("be755a78-5106-4d9a-8e67-d42f239d2a94", ModuleType.Recording, 1)]
    public partial class CloseActiveSolidWorksDocument : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SolidWorksTaskPaneToolsRepository repository.
        /// </summary>
        public static SolidWorksTaskPaneToolsRepository repo = SolidWorksTaskPaneToolsRepository.Instance;

        static CloseActiveSolidWorksDocument instance = new CloseActiveSolidWorksDocument();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseActiveSolidWorksDocument()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseActiveSolidWorksDocument Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SolidWorksPremium2014X64Edition.Titlebar' at 31;14.", repo.SolidWorksPremium2014X64Edition.TitlebarInfo, new RecordItemIndex(0));
            repo.SolidWorksPremium2014X64Edition.Titlebar.MoveTo("31;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolidWorksPremium2014X64Edition.StandardMenu' at 7;4.", repo.SolidWorksPremium2014X64Edition.StandardMenuInfo, new RecordItemIndex(1));
            repo.SolidWorksPremium2014X64Edition.StandardMenu.Click(new Location(StandardMenu_Screenshot1, "7;4", StandardMenu_Screenshot1_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolidWorksMenu.CloseCtrlPlusW' at 58;7.", repo.SolidWorksMenu.CloseCtrlPlusWInfo, new RecordItemIndex(2));
            repo.SolidWorksMenu.CloseCtrlPlusW.Click("58;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage StandardMenu_Screenshot1
        { get { return repo.SolidWorksPremium2014X64Edition.StandardMenuInfo.GetScreenshot1(new Rectangle(18, 10, 18, 10)); } }

        Imaging.FindOptions StandardMenu_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
