///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.EditRecipe.AddOperations.WriteCustomProperties
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddWriteCustomProperties recording.
    /// </summary>
    [TestModule("bcaaf1bd-9959-4cf1-8fa1-f61bb52fdaea", ModuleType.Recording, 1)]
    public partial class AddWriteCustomProperties : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static AddWriteCustomProperties instance = new AddWriteCustomProperties();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddWriteCustomProperties()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddWriteCustomProperties Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperations' at Center.", repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperationsInfo, new RecordItemIndex(0));
            repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperations.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.AddOperations.AddWriteCustomProperties' at Center.", repo.SomeContextMenu.AddOperations.AddWriteCustomPropertiesInfo, new RecordItemIndex(1));
            repo.SomeContextMenu.AddOperations.AddWriteCustomProperties.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
