///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JDE_Heartbeat
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JDE_HeartbeatRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2a747583-596f-4b8e-9668-bc61c1079c58")]
    public partial class JDE_HeartbeatRepository : RepoGenBaseFolder
    {
        static JDE_HeartbeatRepository instance = new JDE_HeartbeatRepository();
        JDE_HeartbeatRepositoryFolders.JDEdwardsEnterpriseOneAppFolder _jdedwardsenterpriseone;
        JDE_HeartbeatRepositoryFolders.JDEPathAppFolder _jdepath;
        JDE_HeartbeatRepositoryFolders.PopupAppFolder _popup;
        JDE_HeartbeatRepositoryFolders.ChromeCancelPopupAppFolder _chromecancelpopup;
        JDE_HeartbeatRepositoryFolders.SelectboxAppFolder _selectbox;
        JDE_HeartbeatRepositoryFolders.IECancelPopupAppFolder _iecancelpopup;
        JDE_HeartbeatRepositoryFolders.IEFrameAppFolder _ieframe;
        JDE_HeartbeatRepositoryFolders.IEFormAppFolder _ieform;

        /// <summary>
        /// Gets the singleton class instance representing the JDE_HeartbeatRepository element repository.
        /// </summary>
        [RepositoryFolder("2a747583-596f-4b8e-9668-bc61c1079c58")]
        public static JDE_HeartbeatRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JDE_HeartbeatRepository() 
            : base("JDE_HeartbeatRepository", "/", null, 0, false, "2a747583-596f-4b8e-9668-bc61c1079c58", ".\\RepositoryImages\\JDE_HeartbeatRepository2a747583.rximgres")
        {
            _jdedwardsenterpriseone = new JDE_HeartbeatRepositoryFolders.JDEdwardsEnterpriseOneAppFolder(this);
            _jdepath = new JDE_HeartbeatRepositoryFolders.JDEPathAppFolder(this);
            _popup = new JDE_HeartbeatRepositoryFolders.PopupAppFolder(this);
            _chromecancelpopup = new JDE_HeartbeatRepositoryFolders.ChromeCancelPopupAppFolder(this);
            _selectbox = new JDE_HeartbeatRepositoryFolders.SelectboxAppFolder(this);
            _iecancelpopup = new JDE_HeartbeatRepositoryFolders.IECancelPopupAppFolder(this);
            _ieframe = new JDE_HeartbeatRepositoryFolders.IEFrameAppFolder(this);
            _ieform = new JDE_HeartbeatRepositoryFolders.IEFormAppFolder(this);
        }

#region Variables

        string _varGridSelection = "Dev";

        /// <summary>
        /// Gets or sets the value of variable varGridSelection.
        /// </summary>
        [TestVariable("cd2d1974-769f-4e35-b8f6-cc7ba8126ae5")]
        public string varGridSelection
        {
            get { return _varGridSelection; }
            set { _varGridSelection = value; }
        }

        string _varURL = "http://deve1";

        /// <summary>
        /// Gets or sets the value of variable varURL.
        /// </summary>
        [TestVariable("9c47e5cb-3b98-4da6-a079-5a511c9308d8")]
        public string varURL
        {
            get { return _varURL; }
            set { _varURL = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2a747583-596f-4b8e-9668-bc61c1079c58")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The JDEdwardsEnterpriseOne folder.
        /// </summary>
        [RepositoryFolder("3faedca7-42db-4a89-a782-63e2216c3d36")]
        public virtual JDE_HeartbeatRepositoryFolders.JDEdwardsEnterpriseOneAppFolder JDEdwardsEnterpriseOne
        {
            get { return _jdedwardsenterpriseone; }
        }

        /// <summary>
        /// The JDEPath folder.
        /// </summary>
        [RepositoryFolder("aaad287a-e3f8-4811-a325-03fc674ab70e")]
        public virtual JDE_HeartbeatRepositoryFolders.JDEPathAppFolder JDEPath
        {
            get { return _jdepath; }
        }

        /// <summary>
        /// The Popup folder.
        /// </summary>
        [RepositoryFolder("7d77d6c9-3c92-490c-8d15-88fdb530a417")]
        public virtual JDE_HeartbeatRepositoryFolders.PopupAppFolder Popup
        {
            get { return _popup; }
        }

        /// <summary>
        /// The ChromeCancelPopup folder.
        /// </summary>
        [RepositoryFolder("e16d0568-4acf-4867-bac2-fec7b93c74e1")]
        public virtual JDE_HeartbeatRepositoryFolders.ChromeCancelPopupAppFolder ChromeCancelPopup
        {
            get { return _chromecancelpopup; }
        }

        /// <summary>
        /// The Selectbox folder.
        /// </summary>
        [RepositoryFolder("83dbf1ed-9740-47ae-8f56-49488b226aca")]
        public virtual JDE_HeartbeatRepositoryFolders.SelectboxAppFolder Selectbox
        {
            get { return _selectbox; }
        }

        /// <summary>
        /// The IECancelPopup folder.
        /// </summary>
        [RepositoryFolder("7182567e-b11e-4211-80a7-9787b911be51")]
        public virtual JDE_HeartbeatRepositoryFolders.IECancelPopupAppFolder IECancelPopup
        {
            get { return _iecancelpopup; }
        }

        /// <summary>
        /// The IEFrame folder.
        /// </summary>
        [RepositoryFolder("63318ccf-afa1-49f5-9b3f-667947056476")]
        public virtual JDE_HeartbeatRepositoryFolders.IEFrameAppFolder IEFrame
        {
            get { return _ieframe; }
        }

        /// <summary>
        /// The IEForm folder.
        /// </summary>
        [RepositoryFolder("cf57487d-8ebe-4b42-a972-6f10034db28c")]
        public virtual JDE_HeartbeatRepositoryFolders.IEFormAppFolder IEForm
        {
            get { return _ieform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class JDE_HeartbeatRepositoryFolders
    {
        /// <summary>
        /// The JDEdwardsEnterpriseOneAppFolder folder.
        /// </summary>
        [RepositoryFolder("3faedca7-42db-4a89-a782-63e2216c3d36")]
        public partial class JDEdwardsEnterpriseOneAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _userInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _fastpathInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new JDEdwardsEnterpriseOne  folder.
            /// </summary>
            public JDEdwardsEnterpriseOneAppFolder(RepoGenBaseFolder parentFolder) :
                    base("JDEdwardsEnterpriseOne", "/dom[@caption='JD Edwards']", parentFolder, 30000, null, false, "3faedca7-42db-4a89-a782-63e2216c3d36", "")
            {
                _userInfo = new RepoItemInfo(this, "User", ".//input[#'User']", 30000, null, "417e8c02-3c9d-4eb3-a47c-e4c66820e4d5");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'Password']", 30000, null, "c2740c92-3ebf-476e-98b3-2e413e76d6db");
                _fastpathInfo = new RepoItemInfo(this, "FastPath", ".//form[#'e1MFastpathForm']/?/?/img[@alt='Fast Path']", 30000, null, "e1578791-200c-4f29-9946-c9550c6259f0");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//table[#'mainLoginTable']//input[@type='submit']", 30000, null, "520fa1d6-b289-41e2-b650-aa1f9a4ebf46");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3faedca7-42db-4a89-a782-63e2216c3d36")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3faedca7-42db-4a89-a782-63e2216c3d36")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The User item.
            /// </summary>
            [RepositoryItem("417e8c02-3c9d-4eb3-a47c-e4c66820e4d5")]
            public virtual Ranorex.InputTag User
            {
                get
                {
                    return _userInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The User item info.
            /// </summary>
            [RepositoryItemInfo("417e8c02-3c9d-4eb3-a47c-e4c66820e4d5")]
            public virtual RepoItemInfo UserInfo
            {
                get
                {
                    return _userInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("c2740c92-3ebf-476e-98b3-2e413e76d6db")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("c2740c92-3ebf-476e-98b3-2e413e76d6db")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The FastPath item.
            /// </summary>
            [RepositoryItem("e1578791-200c-4f29-9946-c9550c6259f0")]
            public virtual Ranorex.ImgTag FastPath
            {
                get
                {
                    return _fastpathInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The FastPath item info.
            /// </summary>
            [RepositoryItemInfo("e1578791-200c-4f29-9946-c9550c6259f0")]
            public virtual RepoItemInfo FastPathInfo
            {
                get
                {
                    return _fastpathInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("520fa1d6-b289-41e2-b650-aa1f9a4ebf46")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("520fa1d6-b289-41e2-b650-aa1f9a4ebf46")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

        /// <summary>
        /// The JDEPathAppFolder folder.
        /// </summary>
        [RepositoryFolder("aaad287a-e3f8-4811-a325-03fc674ab70e")]
        public partial class JDEPathAppFolder : RepoGenBaseFolder
        {
            JDE_HeartbeatRepositoryFolders.E1menuAppIframeFolder _e1menuappiframe;
            RepoItemInfo _homeInfo;
            RepoItemInfo _dropmainmenuInfo;
            RepoItemInfo _fastpathbuttonInfo;
            RepoItemInfo _tefastpathboxInfo;

            /// <summary>
            /// Creates a new JDEPath  folder.
            /// </summary>
            public JDEPathAppFolder(RepoGenBaseFolder parentFolder) :
                    base("JDEPath", "/dom[@path~'/jde/']", parentFolder, 30000, null, false, "aaad287a-e3f8-4811-a325-03fc674ab70e", "")
            {
                _e1menuappiframe = new JDE_HeartbeatRepositoryFolders.E1menuAppIframeFolder(this);
                _homeInfo = new RepoItemInfo(this, "Home", ".//div[#'listOCLInner']/?/?/table//td[@innertext='Home']", 30000, null, "dc8e962a-496f-4309-81ba-caa7301d62b9");
                _dropmainmenuInfo = new RepoItemInfo(this, "DropMainmenu", ".//div[#'drop_mainmenu']", 30000, null, "cc7204b3-f69f-4e2b-a94b-43e61a108428");
                _fastpathbuttonInfo = new RepoItemInfo(this, "FastPathButton", ".//a[#'fastPathButton']", 30000, null, "cedaafd6-b402-4062-bdc5-beb21210a038");
                _tefastpathboxInfo = new RepoItemInfo(this, "TEFASTPATHBOX", ".//input[#'TE_FAST_PATH_BOX']", 30000, false, "a6353dbf-70dc-40c3-8413-2be300df90d8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aaad287a-e3f8-4811-a325-03fc674ab70e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aaad287a-e3f8-4811-a325-03fc674ab70e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("dc8e962a-496f-4309-81ba-caa7301d62b9")]
            public virtual Ranorex.TdTag Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("dc8e962a-496f-4309-81ba-caa7301d62b9")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The DropMainmenu item.
            /// </summary>
            [RepositoryItem("cc7204b3-f69f-4e2b-a94b-43e61a108428")]
            public virtual Ranorex.DivTag DropMainmenu
            {
                get
                {
                    return _dropmainmenuInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DropMainmenu item info.
            /// </summary>
            [RepositoryItemInfo("cc7204b3-f69f-4e2b-a94b-43e61a108428")]
            public virtual RepoItemInfo DropMainmenuInfo
            {
                get
                {
                    return _dropmainmenuInfo;
                }
            }

            /// <summary>
            /// The FastPathButton item.
            /// </summary>
            [RepositoryItem("cedaafd6-b402-4062-bdc5-beb21210a038")]
            public virtual Ranorex.ATag FastPathButton
            {
                get
                {
                    return _fastpathbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FastPathButton item info.
            /// </summary>
            [RepositoryItemInfo("cedaafd6-b402-4062-bdc5-beb21210a038")]
            public virtual RepoItemInfo FastPathButtonInfo
            {
                get
                {
                    return _fastpathbuttonInfo;
                }
            }

            /// <summary>
            /// The TEFASTPATHBOX item.
            /// </summary>
            [RepositoryItem("a6353dbf-70dc-40c3-8413-2be300df90d8")]
            public virtual Ranorex.InputTag TEFASTPATHBOX
            {
                get
                {
                    return _tefastpathboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TEFASTPATHBOX item info.
            /// </summary>
            [RepositoryItemInfo("a6353dbf-70dc-40c3-8413-2be300df90d8")]
            public virtual RepoItemInfo TEFASTPATHBOXInfo
            {
                get
                {
                    return _tefastpathboxInfo;
                }
            }

            /// <summary>
            /// The E1menuAppIframe folder.
            /// </summary>
            [RepositoryFolder("55aa049e-cb7b-4ed5-8fc4-cc19815b278a")]
            public virtual JDE_HeartbeatRepositoryFolders.E1menuAppIframeFolder E1menuAppIframe
            {
                get { return _e1menuappiframe; }
            }
        }

        /// <summary>
        /// The E1menuAppIframeFolder folder.
        /// </summary>
        [RepositoryFolder("55aa049e-cb7b-4ed5-8fc4-cc19815b278a")]
        public partial class E1menuAppIframeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hcfindInfo;
            RepoItemInfo _c017Info;
            RepoItemInfo _c021Info;
            RepoItemInfo _jshyperlinkInfo;
            RepoItemInfo _atsautomationtoolingsystemsInfo;
            RepoItemInfo _c011Info;
            RepoItemInfo _row2Info;
            RepoItemInfo _imgtaghc0Info;
            RepoItemInfo _addbuttonInfo;
            RepoItemInfo _hcokInfo;
            RepoItemInfo _fonttagormInfo;
            RepoItemInfo _submittedjobsInfo;
            RepoItemInfo _divtagdInfo;
            RepoItemInfo _jdegridcontainer01Info;
            RepoItemInfo _ranorexrtInfo;
            RepoItemInfo _selectgridInfo;
            RepoItemInfo _gtab011Info;
            RepoItemInfo _formheadingInfo;
            RepoItemInfo _jdeformtitle0Info;
            RepoItemInfo _branchplanttextboxInfo;
            RepoItemInfo _suppliertextboxInfo;
            RepoItemInfo _accountnumberInfo;
            RepoItemInfo _masterInfo;
            RepoItemInfo _unitcostInfo;
            RepoItemInfo _qtyInfo;
            RepoItemInfo _uomInfo;
            RepoItemInfo _linetypeInfo;
            RepoItemInfo _somespantagInfo;
            RepoItemInfo _description1Info;
            RepoItemInfo _buyerline2Info;

            /// <summary>
            /// Creates a new E1menuAppIframe  folder.
            /// </summary>
            public E1menuAppIframeFolder(RepoGenBaseFolder parentFolder) :
                    base("E1menuAppIframe", ".//iframe[#'e1menuAppIframe']", parentFolder, 30000, null, false, "55aa049e-cb7b-4ed5-8fc4-cc19815b278a", "")
            {
                _hcfindInfo = new RepoItemInfo(this, "HcFind", ".//img[#'hc_Find']", 30000, null, "01716dd1-9c2c-4c5b-a69c-c5883459c566");
                _c017Info = new RepoItemInfo(this, "C017", ".//input[#'C0_17']", 30000, null, "98c6211e-c1ab-474d-bfe8-22d1080f5216");
                _c021Info = new RepoItemInfo(this, "C021", ".//input[#'C0_21']", 30000, null, "4dcb045e-46a6-4f62-b119-588c87ef81a2");
                _jshyperlinkInfo = new RepoItemInfo(this, "JSHyperlink", ".//tr[#'G0_1_R0']/td[2]/div", 30000, null, "bb5aeb5e-c6c7-435f-8128-a5116cb07704");
                _atsautomationtoolingsystemsInfo = new RepoItemInfo(this, "ATSAutomationToolingSystems", ".//tr[#'G0_1_R1']/?/?/div[@innertext~'Tooling']", 30000, null, "d83332b8-fb7c-4b3a-afb7-e6cc96b7f7ad");
                _c011Info = new RepoItemInfo(this, "C011", ".//input[#'C0_11']", 30000, null, "d9560478-f027-4bc1-bab0-61f7b655e9b1");
                _row2Info = new RepoItemInfo(this, "Row2", ".//tr/?/?/div[@innertext='ASG0001']/../..//input[@type='checkbox']", 30000, null, "0539732d-9fe8-408f-8101-db3282e75e3c");
                _imgtaghc0Info = new RepoItemInfo(this, "ImgTagHc0", ".//img[#'hc0']", 30000, null, "3804c08c-b1c0-46d1-a217-2fc38a116e91");
                _addbuttonInfo = new RepoItemInfo(this, "AddButton", ".//img[#'hc_Add']", 30000, null, "9b3c467a-95f7-4cff-a837-7054e5b69fc6");
                _hcokInfo = new RepoItemInfo(this, "HcOK", ".//img[#'hc_OK']", 30000, null, "33aa1bc4-44f7-452c-be0c-a97ffba83af6");
                _fonttagormInfo = new RepoItemInfo(this, "FontTagOrm", ".//table[#'WebMenuBar']/?/?/tr/td[9]/table//div[@id='div']/font[@innertext='orm']", 30000, null, "6a4cc2a4-c94d-4a6d-8b35-c73e8c2aa718");
                _submittedjobsInfo = new RepoItemInfo(this, "SubmittedJobs", ".//tag[@innertext='Submitted Jobs ']", 3000, null, "4fc0ce56-719a-426f-8a9e-1e6dcd3c0daa");
                _divtagdInfo = new RepoItemInfo(this, "DivTagD", ".//tr[#'G0_1_R0']/td[7]/div[@tagname='div']", 30000, null, "fc554e2b-47c8-4708-8f1d-3015f985f3bf");
                _jdegridcontainer01Info = new RepoItemInfo(this, "JdeGridContainer01", ".//td[#'jdeGridContainer0_1']", 30000, null, "f9486f31-a26e-42b4-beae-85b1de4686cb");
                _ranorexrtInfo = new RepoItemInfo(this, "RANOREXRT", ".//tr[#'G0_1_R0']/?/?/div[@innertext='RANOREXRT']", 30000, null, "ad2aecb5-15d0-4658-9f87-adb5fdae688e");
                _selectgridInfo = new RepoItemInfo(this, "SelectGrid", ".//select[#'gtab0_1']/option[@innertext=$varGridSelection]", 30000, null, "93d78be4-872a-4a70-9ab3-bea8c464cdec");
                _gtab011Info = new RepoItemInfo(this, "Gtab011", ".//select[#'gtab0_1']", 30000, null, "bfc69ea7-6d07-4402-a18d-9ee10f48eecf");
                _formheadingInfo = new RepoItemInfo(this, "FormHeading", ".//td[#'formHeading']", 30000, null, "8819b871-b7cf-4db9-a433-4eb6da5fbda1");
                _jdeformtitle0Info = new RepoItemInfo(this, "JdeFormTitle0", ".//span[@innertext~'Available Versions']", 30000, null, "9e8c86b5-5bb6-43bb-8b65-bd1dec9edb2a");
                _branchplanttextboxInfo = new RepoItemInfo(this, "BranchPlantTextBox", ".//input[@title='Branch/Plant1']", 30000, null, "e9fe1bdb-d377-413e-9e9a-67e4b1f286d0");
                _suppliertextboxInfo = new RepoItemInfo(this, "SupplierTextBox", ".//input[@title='Supplier']", 30000, null, "bc439823-9f41-46a8-874a-47fd037d78cc");
                _accountnumberInfo = new RepoItemInfo(this, "AccountNumber", ".//div[#'FormAboveGrid']/span[4]/table/tbody/tr[2]/?/?/table//td/table/tbody/tr[2]//table/?/?/tr/td[2]/table//td/table/?/?/tr/td[11]/?/?/input[@type='text']", 30000, null, "68d8d780-b6ca-42be-9103-423e31e00df1");
                _masterInfo = new RepoItemInfo(this, "Master", ".//iframe[#'defaultFrame']//div[#'master']", 30000, null, "56660a25-3abe-43fb-be19-8f753587a21d");
                _unitcostInfo = new RepoItemInfo(this, "UnitCost", ".//div[#'FormAboveGrid']/span[4]/table/tbody/tr[2]/?/?/table//td/table/tbody/tr[2]//table/?/?/tr/td[2]/table//td/table/?/?/tr/td[10]/?/?/input[@type='text']", 30000, null, "9f0a6096-9227-4cdf-9165-9e9218e90e05");
                _qtyInfo = new RepoItemInfo(this, "Qty", ".//div[#'FormAboveGrid']/span[4]/table/tbody/tr[2]/?/?/table//td/table/tbody/tr[2]//table/?/?/tr/td[2]/table//td/table/?/?/tr/td[7]/?/?/input[@type='text']", 30000, null, "3c17b0e0-aac8-4d3b-89aa-03e619438cc7");
                _uomInfo = new RepoItemInfo(this, "UOM", ".//div[#'FormAboveGrid']/span[4]/table/tbody/tr[2]/?/?/table//td/table/tbody/tr[2]//table/?/?/tr/td[2]/table//td/table/?/?/tr/td[8]/?/?/input[@type='text']", 30000, null, "cf66846d-1894-41d2-ac8f-e320e88f49bf");
                _linetypeInfo = new RepoItemInfo(this, "LineType", ".//div[#'FormAboveGrid']/span[4]/table/tbody/tr[2]/?/?/table//td/table/tbody/tr[2]//table/?/?/tr/td[2]/table//td/table/?/?/tr/td[4]/?/?/input[@type='text']", 30000, null, "1416a0aa-1005-44a6-91ef-804738f9b0d4");
                _somespantagInfo = new RepoItemInfo(this, "SomeSpanTag", ".//div[#'FormAboveGrid']/span[2]/span/table/tbody//table//td/table//div/span[47]", 30000, null, "af5b8aa0-c0c7-45c3-8a3c-10baf06cfa11");
                _description1Info = new RepoItemInfo(this, "Description1", ".//div[#'FormAboveGrid']/span[4]/table/tbody/tr[2]/?/?/table//td/table/tbody/tr[2]//table/?/?/tr/td[2]/table/tbody/tr[1]/?/?/table/?/?/tr/td[12]/?/?/input[@type='text']", 30000, null, "8917d4f0-8f46-426a-911c-97a956a276da");
                _buyerline2Info = new RepoItemInfo(this, "Buyerline2", ".//div[#'FormAboveGrid']/span[4]/table/tbody/tr[2]/?/?/table//td/table/tbody/tr[2]//table/?/?/tr/td[2]/table/tbody/tr[2]/?/?/table/?/?/tr/td[3]/?/?/input[@type='text']", 30000, null, "5956e159-2210-4e2b-a7e2-0bf98b4efd4c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55aa049e-cb7b-4ed5-8fc4-cc19815b278a")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55aa049e-cb7b-4ed5-8fc4-cc19815b278a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HcFind item.
            /// </summary>
            [RepositoryItem("01716dd1-9c2c-4c5b-a69c-c5883459c566")]
            public virtual Ranorex.ImgTag HcFind
            {
                get
                {
                    return _hcfindInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HcFind item info.
            /// </summary>
            [RepositoryItemInfo("01716dd1-9c2c-4c5b-a69c-c5883459c566")]
            public virtual RepoItemInfo HcFindInfo
            {
                get
                {
                    return _hcfindInfo;
                }
            }

            /// <summary>
            /// The C017 item.
            /// </summary>
            [RepositoryItem("98c6211e-c1ab-474d-bfe8-22d1080f5216")]
            public virtual Ranorex.InputTag C017
            {
                get
                {
                    return _c017Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The C017 item info.
            /// </summary>
            [RepositoryItemInfo("98c6211e-c1ab-474d-bfe8-22d1080f5216")]
            public virtual RepoItemInfo C017Info
            {
                get
                {
                    return _c017Info;
                }
            }

            /// <summary>
            /// The C021 item.
            /// </summary>
            [RepositoryItem("4dcb045e-46a6-4f62-b119-588c87ef81a2")]
            public virtual Ranorex.InputTag C021
            {
                get
                {
                    return _c021Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The C021 item info.
            /// </summary>
            [RepositoryItemInfo("4dcb045e-46a6-4f62-b119-588c87ef81a2")]
            public virtual RepoItemInfo C021Info
            {
                get
                {
                    return _c021Info;
                }
            }

            /// <summary>
            /// The JSHyperlink item.
            /// </summary>
            [RepositoryItem("bb5aeb5e-c6c7-435f-8128-a5116cb07704")]
            public virtual Ranorex.DivTag JSHyperlink
            {
                get
                {
                    return _jshyperlinkInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The JSHyperlink item info.
            /// </summary>
            [RepositoryItemInfo("bb5aeb5e-c6c7-435f-8128-a5116cb07704")]
            public virtual RepoItemInfo JSHyperlinkInfo
            {
                get
                {
                    return _jshyperlinkInfo;
                }
            }

            /// <summary>
            /// The ATSAutomationToolingSystems item.
            /// </summary>
            [RepositoryItem("d83332b8-fb7c-4b3a-afb7-e6cc96b7f7ad")]
            public virtual Ranorex.DivTag ATSAutomationToolingSystems
            {
                get
                {
                    return _atsautomationtoolingsystemsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ATSAutomationToolingSystems item info.
            /// </summary>
            [RepositoryItemInfo("d83332b8-fb7c-4b3a-afb7-e6cc96b7f7ad")]
            public virtual RepoItemInfo ATSAutomationToolingSystemsInfo
            {
                get
                {
                    return _atsautomationtoolingsystemsInfo;
                }
            }

            /// <summary>
            /// The C011 item.
            /// </summary>
            [RepositoryItem("d9560478-f027-4bc1-bab0-61f7b655e9b1")]
            public virtual Ranorex.InputTag C011
            {
                get
                {
                    return _c011Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The C011 item info.
            /// </summary>
            [RepositoryItemInfo("d9560478-f027-4bc1-bab0-61f7b655e9b1")]
            public virtual RepoItemInfo C011Info
            {
                get
                {
                    return _c011Info;
                }
            }

            /// <summary>
            /// The Row2 item.
            /// </summary>
            [RepositoryItem("0539732d-9fe8-408f-8101-db3282e75e3c")]
            public virtual Ranorex.InputTag Row2
            {
                get
                {
                    return _row2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Row2 item info.
            /// </summary>
            [RepositoryItemInfo("0539732d-9fe8-408f-8101-db3282e75e3c")]
            public virtual RepoItemInfo Row2Info
            {
                get
                {
                    return _row2Info;
                }
            }

            /// <summary>
            /// The ImgTagHc0 item.
            /// </summary>
            [RepositoryItem("3804c08c-b1c0-46d1-a217-2fc38a116e91")]
            public virtual Ranorex.ImgTag ImgTagHc0
            {
                get
                {
                    return _imgtaghc0Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgTagHc0 item info.
            /// </summary>
            [RepositoryItemInfo("3804c08c-b1c0-46d1-a217-2fc38a116e91")]
            public virtual RepoItemInfo ImgTagHc0Info
            {
                get
                {
                    return _imgtaghc0Info;
                }
            }

            /// <summary>
            /// The AddButton item.
            /// </summary>
            [RepositoryItem("9b3c467a-95f7-4cff-a837-7054e5b69fc6")]
            public virtual Ranorex.ImgTag AddButton
            {
                get
                {
                    return _addbuttonInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The AddButton item info.
            /// </summary>
            [RepositoryItemInfo("9b3c467a-95f7-4cff-a837-7054e5b69fc6")]
            public virtual RepoItemInfo AddButtonInfo
            {
                get
                {
                    return _addbuttonInfo;
                }
            }

            /// <summary>
            /// The HcOK item.
            /// </summary>
            [RepositoryItem("33aa1bc4-44f7-452c-be0c-a97ffba83af6")]
            public virtual Ranorex.ImgTag HcOK
            {
                get
                {
                    return _hcokInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HcOK item info.
            /// </summary>
            [RepositoryItemInfo("33aa1bc4-44f7-452c-be0c-a97ffba83af6")]
            public virtual RepoItemInfo HcOKInfo
            {
                get
                {
                    return _hcokInfo;
                }
            }

            /// <summary>
            /// The FontTagOrm item.
            /// </summary>
            [RepositoryItem("6a4cc2a4-c94d-4a6d-8b35-c73e8c2aa718")]
            public virtual Ranorex.FontTag FontTagOrm
            {
                get
                {
                    return _fonttagormInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The FontTagOrm item info.
            /// </summary>
            [RepositoryItemInfo("6a4cc2a4-c94d-4a6d-8b35-c73e8c2aa718")]
            public virtual RepoItemInfo FontTagOrmInfo
            {
                get
                {
                    return _fonttagormInfo;
                }
            }

            /// <summary>
            /// The SubmittedJobs item.
            /// </summary>
            [RepositoryItem("4fc0ce56-719a-426f-8a9e-1e6dcd3c0daa")]
            public virtual Ranorex.WebElement SubmittedJobs
            {
                get
                {
                    return _submittedjobsInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The SubmittedJobs item info.
            /// </summary>
            [RepositoryItemInfo("4fc0ce56-719a-426f-8a9e-1e6dcd3c0daa")]
            public virtual RepoItemInfo SubmittedJobsInfo
            {
                get
                {
                    return _submittedjobsInfo;
                }
            }

            /// <summary>
            /// The DivTagD item.
            /// </summary>
            [RepositoryItem("fc554e2b-47c8-4708-8f1d-3015f985f3bf")]
            public virtual Ranorex.DivTag DivTagD
            {
                get
                {
                    return _divtagdInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagD item info.
            /// </summary>
            [RepositoryItemInfo("fc554e2b-47c8-4708-8f1d-3015f985f3bf")]
            public virtual RepoItemInfo DivTagDInfo
            {
                get
                {
                    return _divtagdInfo;
                }
            }

            /// <summary>
            /// The JdeGridContainer01 item.
            /// </summary>
            [RepositoryItem("f9486f31-a26e-42b4-beae-85b1de4686cb")]
            public virtual Ranorex.TdTag JdeGridContainer01
            {
                get
                {
                    return _jdegridcontainer01Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The JdeGridContainer01 item info.
            /// </summary>
            [RepositoryItemInfo("f9486f31-a26e-42b4-beae-85b1de4686cb")]
            public virtual RepoItemInfo JdeGridContainer01Info
            {
                get
                {
                    return _jdegridcontainer01Info;
                }
            }

            /// <summary>
            /// The RANOREXRT item.
            /// </summary>
            [RepositoryItem("ad2aecb5-15d0-4658-9f87-adb5fdae688e")]
            public virtual Ranorex.DivTag RANOREXRT
            {
                get
                {
                    return _ranorexrtInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RANOREXRT item info.
            /// </summary>
            [RepositoryItemInfo("ad2aecb5-15d0-4658-9f87-adb5fdae688e")]
            public virtual RepoItemInfo RANOREXRTInfo
            {
                get
                {
                    return _ranorexrtInfo;
                }
            }

            /// <summary>
            /// The SelectGrid item.
            /// </summary>
            [RepositoryItem("93d78be4-872a-4a70-9ab3-bea8c464cdec")]
            public virtual Ranorex.OptionTag SelectGrid
            {
                get
                {
                    return _selectgridInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The SelectGrid item info.
            /// </summary>
            [RepositoryItemInfo("93d78be4-872a-4a70-9ab3-bea8c464cdec")]
            public virtual RepoItemInfo SelectGridInfo
            {
                get
                {
                    return _selectgridInfo;
                }
            }

            /// <summary>
            /// The Gtab011 item.
            /// </summary>
            [RepositoryItem("bfc69ea7-6d07-4402-a18d-9ee10f48eecf")]
            public virtual Ranorex.SelectTag Gtab011
            {
                get
                {
                    return _gtab011Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Gtab011 item info.
            /// </summary>
            [RepositoryItemInfo("bfc69ea7-6d07-4402-a18d-9ee10f48eecf")]
            public virtual RepoItemInfo Gtab011Info
            {
                get
                {
                    return _gtab011Info;
                }
            }

            /// <summary>
            /// The FormHeading item.
            /// </summary>
            [RepositoryItem("8819b871-b7cf-4db9-a433-4eb6da5fbda1")]
            public virtual Ranorex.TdTag FormHeading
            {
                get
                {
                    return _formheadingInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The FormHeading item info.
            /// </summary>
            [RepositoryItemInfo("8819b871-b7cf-4db9-a433-4eb6da5fbda1")]
            public virtual RepoItemInfo FormHeadingInfo
            {
                get
                {
                    return _formheadingInfo;
                }
            }

            /// <summary>
            /// The JdeFormTitle0 item.
            /// </summary>
            [RepositoryItem("9e8c86b5-5bb6-43bb-8b65-bd1dec9edb2a")]
            public virtual Ranorex.SpanTag JdeFormTitle0
            {
                get
                {
                    return _jdeformtitle0Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The JdeFormTitle0 item info.
            /// </summary>
            [RepositoryItemInfo("9e8c86b5-5bb6-43bb-8b65-bd1dec9edb2a")]
            public virtual RepoItemInfo JdeFormTitle0Info
            {
                get
                {
                    return _jdeformtitle0Info;
                }
            }

            /// <summary>
            /// The BranchPlantTextBox item.
            /// </summary>
            [RepositoryItem("e9fe1bdb-d377-413e-9e9a-67e4b1f286d0")]
            public virtual Ranorex.InputTag BranchPlantTextBox
            {
                get
                {
                    return _branchplanttextboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BranchPlantTextBox item info.
            /// </summary>
            [RepositoryItemInfo("e9fe1bdb-d377-413e-9e9a-67e4b1f286d0")]
            public virtual RepoItemInfo BranchPlantTextBoxInfo
            {
                get
                {
                    return _branchplanttextboxInfo;
                }
            }

            /// <summary>
            /// The SupplierTextBox item.
            /// </summary>
            [RepositoryItem("bc439823-9f41-46a8-874a-47fd037d78cc")]
            public virtual Ranorex.InputTag SupplierTextBox
            {
                get
                {
                    return _suppliertextboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SupplierTextBox item info.
            /// </summary>
            [RepositoryItemInfo("bc439823-9f41-46a8-874a-47fd037d78cc")]
            public virtual RepoItemInfo SupplierTextBoxInfo
            {
                get
                {
                    return _suppliertextboxInfo;
                }
            }

            /// <summary>
            /// The AccountNumber item.
            /// </summary>
            [RepositoryItem("68d8d780-b6ca-42be-9103-423e31e00df1")]
            public virtual Ranorex.InputTag AccountNumber
            {
                get
                {
                    return _accountnumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountNumber item info.
            /// </summary>
            [RepositoryItemInfo("68d8d780-b6ca-42be-9103-423e31e00df1")]
            public virtual RepoItemInfo AccountNumberInfo
            {
                get
                {
                    return _accountnumberInfo;
                }
            }

            /// <summary>
            /// The Master item.
            /// </summary>
            [RepositoryItem("56660a25-3abe-43fb-be19-8f753587a21d")]
            public virtual Ranorex.DivTag Master
            {
                get
                {
                    return _masterInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Master item info.
            /// </summary>
            [RepositoryItemInfo("56660a25-3abe-43fb-be19-8f753587a21d")]
            public virtual RepoItemInfo MasterInfo
            {
                get
                {
                    return _masterInfo;
                }
            }

            /// <summary>
            /// The UnitCost item.
            /// </summary>
            [RepositoryItem("9f0a6096-9227-4cdf-9165-9e9218e90e05")]
            public virtual Ranorex.InputTag UnitCost
            {
                get
                {
                    return _unitcostInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UnitCost item info.
            /// </summary>
            [RepositoryItemInfo("9f0a6096-9227-4cdf-9165-9e9218e90e05")]
            public virtual RepoItemInfo UnitCostInfo
            {
                get
                {
                    return _unitcostInfo;
                }
            }

            /// <summary>
            /// The Qty item.
            /// </summary>
            [RepositoryItem("3c17b0e0-aac8-4d3b-89aa-03e619438cc7")]
            public virtual Ranorex.InputTag Qty
            {
                get
                {
                    return _qtyInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Qty item info.
            /// </summary>
            [RepositoryItemInfo("3c17b0e0-aac8-4d3b-89aa-03e619438cc7")]
            public virtual RepoItemInfo QtyInfo
            {
                get
                {
                    return _qtyInfo;
                }
            }

            /// <summary>
            /// The UOM item.
            /// </summary>
            [RepositoryItem("cf66846d-1894-41d2-ac8f-e320e88f49bf")]
            public virtual Ranorex.InputTag UOM
            {
                get
                {
                    return _uomInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UOM item info.
            /// </summary>
            [RepositoryItemInfo("cf66846d-1894-41d2-ac8f-e320e88f49bf")]
            public virtual RepoItemInfo UOMInfo
            {
                get
                {
                    return _uomInfo;
                }
            }

            /// <summary>
            /// The LineType item.
            /// </summary>
            [RepositoryItem("1416a0aa-1005-44a6-91ef-804738f9b0d4")]
            public virtual Ranorex.InputTag LineType
            {
                get
                {
                    return _linetypeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LineType item info.
            /// </summary>
            [RepositoryItemInfo("1416a0aa-1005-44a6-91ef-804738f9b0d4")]
            public virtual RepoItemInfo LineTypeInfo
            {
                get
                {
                    return _linetypeInfo;
                }
            }

            /// <summary>
            /// The SomeSpanTag item.
            /// </summary>
            [RepositoryItem("af5b8aa0-c0c7-45c3-8a3c-10baf06cfa11")]
            public virtual Ranorex.SpanTag SomeSpanTag
            {
                get
                {
                    return _somespantagInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SomeSpanTag item info.
            /// </summary>
            [RepositoryItemInfo("af5b8aa0-c0c7-45c3-8a3c-10baf06cfa11")]
            public virtual RepoItemInfo SomeSpanTagInfo
            {
                get
                {
                    return _somespantagInfo;
                }
            }

            /// <summary>
            /// The Description1 item.
            /// </summary>
            [RepositoryItem("8917d4f0-8f46-426a-911c-97a956a276da")]
            public virtual Ranorex.InputTag Description1
            {
                get
                {
                    return _description1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Description1 item info.
            /// </summary>
            [RepositoryItemInfo("8917d4f0-8f46-426a-911c-97a956a276da")]
            public virtual RepoItemInfo Description1Info
            {
                get
                {
                    return _description1Info;
                }
            }

            /// <summary>
            /// The Buyerline2 item.
            /// </summary>
            [RepositoryItem("5956e159-2210-4e2b-a7e2-0bf98b4efd4c")]
            public virtual Ranorex.InputTag Buyerline2
            {
                get
                {
                    return _buyerline2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Buyerline2 item info.
            /// </summary>
            [RepositoryItemInfo("5956e159-2210-4e2b-a7e2-0bf98b4efd4c")]
            public virtual RepoItemInfo Buyerline2Info
            {
                get
                {
                    return _buyerline2Info;
                }
            }
        }

        /// <summary>
        /// The PopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("7d77d6c9-3c92-490c-8d15-88fdb530a417")]
        public partial class PopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new Popup  folder.
            /// </summary>
            public PopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Popup", "/form[@accessiblename~'says']", parentFolder, 30000, null, true, "7d77d6c9-3c92-490c-8d15-88fdb530a417", "")
            {
                _cancelInfo = new RepoItemInfo(this, "Cancel", ".//button[@accessiblename='Cancel']", 30000, null, "3f187014-4873-47af-a05e-1f6bd282f66e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7d77d6c9-3c92-490c-8d15-88fdb530a417")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7d77d6c9-3c92-490c-8d15-88fdb530a417")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("3f187014-4873-47af-a05e-1f6bd282f66e")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("3f187014-4873-47af-a05e-1f6bd282f66e")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeCancelPopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("e16d0568-4acf-4867-bac2-fec7b93c74e1")]
        public partial class ChromeCancelPopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cancelchromeInfo;

            /// <summary>
            /// Creates a new ChromeCancelPopup  folder.
            /// </summary>
            public ChromeCancelPopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ChromeCancelPopup", "/form[@processname='chrome']", parentFolder, 30000, null, true, "e16d0568-4acf-4867-bac2-fec7b93c74e1", "")
            {
                _cancelchromeInfo = new RepoItemInfo(this, "CancelChrome", ".//form[@accessiblename~'says']//button[@accessiblename='Cancel']", 30000, null, "afc1234e-71cd-415a-87a0-82b66de135cd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e16d0568-4acf-4867-bac2-fec7b93c74e1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e16d0568-4acf-4867-bac2-fec7b93c74e1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CancelChrome item.
            /// </summary>
            [RepositoryItem("afc1234e-71cd-415a-87a0-82b66de135cd")]
            public virtual Ranorex.Button CancelChrome
            {
                get
                {
                    return _cancelchromeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelChrome item info.
            /// </summary>
            [RepositoryItemInfo("afc1234e-71cd-415a-87a0-82b66de135cd")]
            public virtual RepoItemInfo CancelChromeInfo
            {
                get
                {
                    return _cancelchromeInfo;
                }
            }
        }

        /// <summary>
        /// The SelectboxAppFolder folder.
        /// </summary>
        [RepositoryFolder("83dbf1ed-9740-47ae-8f56-49488b226aca")]
        public partial class SelectboxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _listitemgridInfo;

            /// <summary>
            /// Creates a new Selectbox  folder.
            /// </summary>
            public SelectboxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Selectbox", "/container[@caption='selectbox']", parentFolder, 30000, null, true, "83dbf1ed-9740-47ae-8f56-49488b226aca", "")
            {
                _listitemgridInfo = new RepoItemInfo(this, "ListItemGrid", "listitem[@accessiblename<$varGridSelection]", 30000, null, "713ac659-a789-4fbc-a129-11b7d6493831");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("83dbf1ed-9740-47ae-8f56-49488b226aca")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("83dbf1ed-9740-47ae-8f56-49488b226aca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItemGrid item.
            /// </summary>
            [RepositoryItem("713ac659-a789-4fbc-a129-11b7d6493831")]
            public virtual Ranorex.ListItem ListItemGrid
            {
                get
                {
                    return _listitemgridInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemGrid item info.
            /// </summary>
            [RepositoryItemInfo("713ac659-a789-4fbc-a129-11b7d6493831")]
            public virtual RepoItemInfo ListItemGridInfo
            {
                get
                {
                    return _listitemgridInfo;
                }
            }
        }

        /// <summary>
        /// The IECancelPopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("7182567e-b11e-4211-80a7-9787b911be51")]
        public partial class IECancelPopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cancelieInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new IECancelPopup  folder.
            /// </summary>
            public IECancelPopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IECancelPopup", "/form[@processname='iexplore']", parentFolder, 30000, null, true, "7182567e-b11e-4211-80a7-9787b911be51", "")
            {
                _cancelieInfo = new RepoItemInfo(this, "CancelIE", ".//form[@accessiblename~'says']//button[@accessiblename='Cancel']", 30000, null, "b2f07826-d91a-4eae-aef4-f448247f02fa");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@text='Cancel']", 30000, null, "57e04e60-e24c-46bf-84a2-0a19477c32c4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7182567e-b11e-4211-80a7-9787b911be51")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7182567e-b11e-4211-80a7-9787b911be51")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CancelIE item.
            /// </summary>
            [RepositoryItem("b2f07826-d91a-4eae-aef4-f448247f02fa")]
            public virtual Ranorex.Button CancelIE
            {
                get
                {
                    return _cancelieInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelIE item info.
            /// </summary>
            [RepositoryItemInfo("b2f07826-d91a-4eae-aef4-f448247f02fa")]
            public virtual RepoItemInfo CancelIEInfo
            {
                get
                {
                    return _cancelieInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("57e04e60-e24c-46bf-84a2-0a19477c32c4")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("57e04e60-e24c-46bf-84a2-0a19477c32c4")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The IEFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("63318ccf-afa1-49f5-9b3f-667947056476")]
        public partial class IEFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _noneInfo;

            /// <summary>
            /// Creates a new IEFrame  folder.
            /// </summary>
            public IEFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IEFrame", "/form", parentFolder, 30000, null, true, "63318ccf-afa1-49f5-9b3f-667947056476", "")
            {
                _noneInfo = new RepoItemInfo(this, "None", ".//toolbar/button", 30000, null, "340970b3-c1a1-4536-bb0d-ceef17926f0c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("63318ccf-afa1-49f5-9b3f-667947056476")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("63318ccf-afa1-49f5-9b3f-667947056476")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("340970b3-c1a1-4536-bb0d-ceef17926f0c")]
            public virtual Ranorex.Button None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("340970b3-c1a1-4536-bb0d-ceef17926f0c")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }
        }

        /// <summary>
        /// The IEFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("cf57487d-8ebe-4b42-a972-6f10034db28c")]
        public partial class IEFormAppFolder : RepoGenBaseFolder
        {
            JDE_HeartbeatRepositoryFolders.SecureToolbarFolder _securetoolbar;

            /// <summary>
            /// Creates a new IEForm  folder.
            /// </summary>
            public IEFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IEForm", "/form[@class='IEFrame']", parentFolder, 10000, null, true, "cf57487d-8ebe-4b42-a972-6f10034db28c", "")
            {
                _securetoolbar = new JDE_HeartbeatRepositoryFolders.SecureToolbarFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf57487d-8ebe-4b42-a972-6f10034db28c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf57487d-8ebe-4b42-a972-6f10034db28c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SecureToolbar folder.
            /// </summary>
            [RepositoryFolder("e6088881-a4e9-49e3-9632-3a39b8aec23d")]
            public virtual JDE_HeartbeatRepositoryFolders.SecureToolbarFolder SecureToolbar
            {
                get { return _securetoolbar; }
            }
        }

        /// <summary>
        /// The SecureToolbarFolder folder.
        /// </summary>
        [RepositoryFolder("e6088881-a4e9-49e3-9632-3a39b8aec23d")]
        public partial class SecureToolbarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _showallcontentInfo;

            /// <summary>
            /// Creates a new SecureToolbar  folder.
            /// </summary>
            public SecureToolbarFolder(RepoGenBaseFolder parentFolder) :
                    base("SecureToolbar", ".//toolbar[@accessiblename='Notification']", parentFolder, 10000, null, false, "e6088881-a4e9-49e3-9632-3a39b8aec23d", "")
            {
                _showallcontentInfo = new RepoItemInfo(this, "ShowAllContent", "button[@accessiblename='Show all content']", 15000, null, "63a36c13-43c1-4de7-9ce7-490c5857c480");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e6088881-a4e9-49e3-9632-3a39b8aec23d")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e6088881-a4e9-49e3-9632-3a39b8aec23d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ShowAllContent item.
            /// </summary>
            [RepositoryItem("63a36c13-43c1-4de7-9ce7-490c5857c480")]
            public virtual Ranorex.Button ShowAllContent
            {
                get
                {
                    return _showallcontentInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ShowAllContent item info.
            /// </summary>
            [RepositoryItemInfo("63a36c13-43c1-4de7-9ce7-490c5857c480")]
            public virtual RepoItemInfo ShowAllContentInfo
            {
                get
                {
                    return _showallcontentInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
