///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace JDE_Heartbeat
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowserUrl recording.
    /// </summary>
    [TestModule("533f7045-2e9a-4161-a348-01693c86950d", ModuleType.Recording, 1)]
    public partial class OpenBrowserUrl : ITestModule
    {
        /// <summary>
        /// Holds an instance of the JDE_HeartbeatRepository repository.
        /// </summary>
        public static JDE_HeartbeatRepository repo = JDE_HeartbeatRepository.Instance;

        static OpenBrowserUrl instance = new OpenBrowserUrl();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowserUrl()
        {
            varURL = "http://deve1";
            varTimeSpan = "";
            varRxPath = "/dom[@caption='JD Edwards']";
            varKeepBrowserOpen = "N";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowserUrl Instance
        {
            get { return instance; }
        }

#region Variables

        string _varTimeSpan;

        /// <summary>
        /// Gets or sets the value of variable varTimeSpan.
        /// </summary>
        [TestVariable("76e2a14a-dd01-4c1e-82b4-9f6ed32b2bd1")]
        public string varTimeSpan
        {
            get { return _varTimeSpan; }
            set { _varTimeSpan = value; }
        }

        string _varRxPath;

        /// <summary>
        /// Gets or sets the value of variable varRxPath.
        /// </summary>
        [TestVariable("81012266-2466-4564-b076-ab1443601042")]
        public string varRxPath
        {
            get { return _varRxPath; }
            set { _varRxPath = value; }
        }

        string _varKeepBrowserOpen;

        /// <summary>
        /// Gets or sets the value of variable varKeepBrowserOpen.
        /// </summary>
        [TestVariable("702fa1db-8ccd-4f82-aa1d-65ba011d5b69")]
        public string varKeepBrowserOpen
        {
            get { return _varKeepBrowserOpen; }
            set { _varKeepBrowserOpen = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varURL.
        /// </summary>
        [TestVariable("1dfac4e1-9c07-4952-8059-613398c0e7e7")]
        public string varURL
        {
            get { return repo.varURL; }
            set { repo.varURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            varTimeSpan = OpenBrowser(varRxPath, varKeepBrowserOpen);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
