///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.NewRecipe
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SaveRecipeNewJob recording.
    /// </summary>
    [TestModule("fd34a2de-74e0-4e50-989a-1a9c55a14b16", ModuleType.Recording, 1)]
    public partial class SaveRecipeNewJob : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static SaveRecipeNewJob instance = new SaveRecipeNewJob();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SaveRecipeNewJob()
        {
            StatusMessage = "";
            ExpectedStatusMessage = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SaveRecipeNewJob Instance
        {
            get { return instance; }
        }

#region Variables

        string _StatusMessage;

        /// <summary>
        /// Gets or sets the value of variable StatusMessage.
        /// </summary>
        [TestVariable("e84871d2-271a-4a42-a068-7f5509880d8f")]
        public string StatusMessage
        {
            get { return _StatusMessage; }
            set { _StatusMessage = value; }
        }

        string _ExpectedStatusMessage;

        /// <summary>
        /// Gets or sets the value of variable ExpectedStatusMessage.
        /// </summary>
        [TestVariable("29d0a8c3-a0b5-4881-9575-604562ecd7c2")]
        public string ExpectedStatusMessage
        {
            get { return _ExpectedStatusMessage; }
            set { _ExpectedStatusMessage = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.RecipeToolsTab' at Center.", repo.ATSDocumentProcessorForm.Ribbon.RecipeToolsTabInfo, new RecordItemIndex(0));
            repo.ATSDocumentProcessorForm.Ribbon.RecipeToolsTab.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.RecipeTools.Main.Save' at 22;28.", repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Main.SaveInfo, new RecordItemIndex(1));
            repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Main.Save.Click("22;28");
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'NoTitleDialog.ButtonOK' at 74;17.", repo.NoTitleDialog.ButtonOKInfo, new RecordItemIndex(2));
                repo.NoTitleDialog.ButtonOK.Click("74;17");
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'ATSDocumentProcessorForm.MessageText' and assigning its value to variable 'StatusMessage'.", repo.ATSDocumentProcessorForm.MessageTextInfo, new RecordItemIndex(3));
            StatusMessage = repo.ATSDocumentProcessorForm.MessageText.Element.GetAttributeValueText("Text");
            
            CheckStatusMessage(StatusMessage, ExpectedStatusMessage);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
