///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SolidWorksTaskPaneTools
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CopyFolder recording.
    /// </summary>
    [TestModule("4a87acf5-96a1-4154-b660-64be18c43a1c", ModuleType.Recording, 1)]
    public partial class CopyFolder : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SolidWorksTaskPaneToolsRepository repository.
        /// </summary>
        public static SolidWorksTaskPaneToolsRepository repo = SolidWorksTaskPaneToolsRepository.Instance;

        static CopyFolder instance = new CopyFolder();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CopyFolder()
        {
            SourceFolder = "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Remove Design Tables\\app_files\\TestFiles";
            DestinationFolder = "C:\\home\\TestFiles";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CopyFolder Instance
        {
            get { return instance; }
        }

#region Variables

        string _SourceFolder;

        /// <summary>
        /// Gets or sets the value of variable SourceFolder.
        /// </summary>
        [TestVariable("12a7c045-504b-4d86-97c4-3d3a306b3927")]
        public string SourceFolder
        {
            get { return _SourceFolder; }
            set { _SourceFolder = value; }
        }

        string _DestinationFolder;

        /// <summary>
        /// Gets or sets the value of variable DestinationFolder.
        /// </summary>
        [TestVariable("449b027b-1568-44dd-bd5c-dfc2ba8b1874")]
        public string DestinationFolder
        {
            get { return _DestinationFolder; }
            set { _DestinationFolder = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            CopyDirectory(SourceFolder, DestinationFolder);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
