///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SolidWorksTaskPaneTools
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeepCopyItemVersion recording.
    /// </summary>
    [TestModule("6ee78158-1c43-4af8-8aca-6d82de82fc90", ModuleType.Recording, 1)]
    public partial class DeepCopyItemVersion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SolidWorksTaskPaneToolsRepository repository.
        /// </summary>
        public static SolidWorksTaskPaneToolsRepository repo = SolidWorksTaskPaneToolsRepository.Instance;

        static DeepCopyItemVersion instance = new DeepCopyItemVersion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeepCopyItemVersion()
        {
            FilePathOut = "";
            ItemVersion = "001";
            ItemMinorRevision = "00";
            ItemMajorRevision = "B";
            ItemNumber = "13615-0151-0000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeepCopyItemVersion Instance
        {
            get { return instance; }
        }

#region Variables

        string _FilePathOut;

        /// <summary>
        /// Gets or sets the value of variable FilePathOut.
        /// </summary>
        [TestVariable("e03d8d51-a810-4572-bc8a-ef1933a3be3c")]
        public string FilePathOut
        {
            get { return _FilePathOut; }
            set { _FilePathOut = value; }
        }

        string _ItemVersion;

        /// <summary>
        /// Gets or sets the value of variable ItemVersion.
        /// </summary>
        [TestVariable("252911de-bbb7-497d-84ed-8208c9cfb1df")]
        public string ItemVersion
        {
            get { return _ItemVersion; }
            set { _ItemVersion = value; }
        }

        string _ItemMinorRevision;

        /// <summary>
        /// Gets or sets the value of variable ItemMinorRevision.
        /// </summary>
        [TestVariable("73e65367-2f80-49d3-8cfc-4f14f1a1c6a9")]
        public string ItemMinorRevision
        {
            get { return _ItemMinorRevision; }
            set { _ItemMinorRevision = value; }
        }

        string _ItemMajorRevision;

        /// <summary>
        /// Gets or sets the value of variable ItemMajorRevision.
        /// </summary>
        [TestVariable("88dd5304-b49e-47dd-9fe8-e0238c9e997a")]
        public string ItemMajorRevision
        {
            get { return _ItemMajorRevision; }
            set { _ItemMajorRevision = value; }
        }

        string _ItemNumber;

        /// <summary>
        /// Gets or sets the value of variable ItemNumber.
        /// </summary>
        [TestVariable("89996a90-55d3-41b0-8801-2e182d23783a")]
        public string ItemNumber
        {
            get { return _ItemNumber; }
            set { _ItemNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'ConnectedToESRPRODAsAdamBridgman'.", repo.ConnectedToESRPRODAsAdamBridgman.SelfInfo, new RecordItemIndex(0));
            repo.ConnectedToESRPRODAsAdamBridgman.Self.Focus();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.AdvancedSearch' at Center.", repo.ConnectedToESRPRODAsAdamBridgman.AdvancedSearchInfo, new RecordItemIndex(1));
            repo.ConnectedToESRPRODAsAdamBridgman.AdvancedSearch.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.AdvancedSearchFavourites' at Center.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.AdvancedSearchFavouritesInfo, new RecordItemIndex(2));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.AdvancedSearchFavourites.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JavaContextMenu.ATSItemSearch' at 114;5.", repo.JavaContextMenu.ATSItemSearchInfo, new RecordItemIndex(3));
            repo.JavaContextMenu.ATSItemSearch.Click("114;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton' at 12;10.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButtonInfo, new RecordItemIndex(4));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton.Click("12;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox' at 59;6.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBoxInfo, new RecordItemIndex(5));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox.Click("59;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JavaContextMenu.ComboBoxList.ItemMajorRevision' at 59;6.", repo.JavaContextMenu.ComboBoxList.ItemMajorRevisionInfo, new RecordItemIndex(6));
            repo.JavaContextMenu.ComboBoxList.ItemMajorRevision.Click("59;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox1' at 102;8.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox1Info, new RecordItemIndex(7));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox1.Click("102;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JavaContextMenu.ComboBoxList.Contains' at 77;9.", repo.JavaContextMenu.ComboBoxList.ContainsInfo, new RecordItemIndex(8));
            repo.JavaContextMenu.ComboBoxList.Contains.Click("77;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton1' at 12;8.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton1Info, new RecordItemIndex(9));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton1.Click("12;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox2' at 44;12.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox2Info, new RecordItemIndex(10));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox2.Click("44;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JavaContextMenu.ComboBoxList.ItemMinorRevision' at 58;9.", repo.JavaContextMenu.ComboBoxList.ItemMinorRevisionInfo, new RecordItemIndex(11));
            repo.JavaContextMenu.ComboBoxList.ItemMinorRevision.Click("58;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox3' at 29;10.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox3Info, new RecordItemIndex(12));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox3.Click("29;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JavaContextMenu.ComboBoxList.Contains' at 28;11.", repo.JavaContextMenu.ComboBoxList.ContainsInfo, new RecordItemIndex(13));
            repo.JavaContextMenu.ComboBoxList.Contains.Click("28;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton2' at 13;9.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton2Info, new RecordItemIndex(14));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton2.Click("13;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox4' at 55;9.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox4Info, new RecordItemIndex(15));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox4.Click("55;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JavaContextMenu.ComboBoxList.ItemVersion' at 62;4.", repo.JavaContextMenu.ComboBoxList.ItemVersionInfo, new RecordItemIndex(16));
            repo.JavaContextMenu.ComboBoxList.ItemVersion.Click("62;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox5' at 63;8.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox5Info, new RecordItemIndex(17));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxComboBox5.Click("63;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JavaContextMenu.ComboBoxList.Contains' at 51;9.", repo.JavaContextMenu.ComboBoxList.ContainsInfo, new RecordItemIndex(18));
            repo.JavaContextMenu.ComboBoxList.Contains.Click("51;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton3' at 12;9.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton3Info, new RecordItemIndex(19));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton3.Click("12;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton3' at 13;8.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton3Info, new RecordItemIndex(20));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.WorxButton3.Click("13;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText1' at 35;6.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText1Info, new RecordItemIndex(21));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText1.Click("35;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ItemNumber' with focus on 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText1'.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText1Info, new RecordItemIndex(22));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText1.PressKeys(ItemNumber);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText2' at 18;6.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText2Info, new RecordItemIndex(23));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText2.Click("18;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ItemMajorRevision' with focus on 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText2'.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText2Info, new RecordItemIndex(24));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText2.PressKeys(ItemMajorRevision);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText3' at 34;5.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText3Info, new RecordItemIndex(25));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText3.Click("34;5");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ItemMinorRevision' with focus on 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText3'.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText3Info, new RecordItemIndex(26));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText3.PressKeys(ItemMinorRevision);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText4' at 27;5.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText4Info, new RecordItemIndex(27));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText4.Click("27;5");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ItemVersion' with focus on 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText4'.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText4Info, new RecordItemIndex(28));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchText4.PressKeys(ItemVersion);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.Search' at 55;7.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchInfo, new RecordItemIndex(29));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.Search.Click("55;7");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(30));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchResultFirstResult' at Center.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchResultFirstResultInfo, new RecordItemIndex(31));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchResultFirstResult.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchResultFirstResult' at 128;11.", repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchResultFirstResultInfo, new RecordItemIndex(32));
            repo.ConnectedToESRPRODAsAdamBridgman.MainHonSplitPane.SearchResultFirstResult.Click(System.Windows.Forms.MouseButtons.Right, "128;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JavaContextMenu.DeepCopy' at 52;6.", repo.JavaContextMenu.DeepCopyInfo, new RecordItemIndex(33));
            repo.JavaContextMenu.DeepCopy.Click("52;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeepCopy.False' at 20;11.", repo.DeepCopy.FalseInfo, new RecordItemIndex(34));
            repo.DeepCopy.False.Click("20;11");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(35));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeepCopy.True' at 20;11.", repo.DeepCopy.TrueInfo, new RecordItemIndex(36));
            repo.DeepCopy.True.Click("20;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeepCopy.DeepCopyAsNewVersion' at 96;13.", repo.DeepCopy.DeepCopyAsNewVersionInfo, new RecordItemIndex(37));
            repo.DeepCopy.DeepCopyAsNewVersion.Click("96;13");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
