///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SolidWorksTaskPaneTools
{
    public partial class PrepareSolidWorks
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Close_Application_SolidWorksPremium2014X64Edition()
        {
        	if (Validate.Exists(repo.SolidWorksPremium2014X64Edition.SelfInfo.AbsolutePath, Duration.FromMilliseconds(30000), "SOLIDWORKS", false))
        	{
	            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'SolidWorksPremium2014X64Edition'.", repo.SolidWorksPremium2014X64Edition.SelfInfo);
	            Host.Local.CloseApplication(repo.SolidWorksPremium2014X64Edition.Self, new Duration(0));
        	}
        }

    }
}