///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpchainMechDeployTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddinUpdater recording.
    /// </summary>
    [TestModule("a5d47db1-5dab-4d0e-8a6a-1209e95559bb", ModuleType.Recording, 1)]
    public partial class AddinUpdater : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpchainMechDeployTestRepository repository.
        /// </summary>
        public static UpchainMechDeployTestRepository repo = UpchainMechDeployTestRepository.Instance;

        static AddinUpdater instance = new AddinUpdater();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddinUpdater()
        {
            Environment = "none";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddinUpdater Instance
        {
            get { return instance; }
        }

#region Variables

        string _Environment;

        /// <summary>
        /// Gets or sets the value of variable Environment.
        /// </summary>
        [TestVariable("f5abccd7-cc51-4da5-9379-1f9ac5385b0c")]
        public string Environment
        {
            get { return _Environment; }
            set { _Environment = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeMethods.CheckandInstallCorrectAddInVersion(Environment);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
