///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpchainMechDeployTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AdvSearchForItemStaleCBOM recording.
    /// </summary>
    [TestModule("f7f79521-60b9-463c-9fcb-6af3067fc1f1", ModuleType.Recording, 1)]
    public partial class AdvSearchForItemStaleCBOM : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpchainMechDeployTestRepository repository.
        /// </summary>
        public static UpchainMechDeployTestRepository repo = UpchainMechDeployTestRepository.Instance;

        static AdvSearchForItemStaleCBOM instance = new AdvSearchForItemStaleCBOM();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AdvSearchForItemStaleCBOM()
        {
            ItemNumber = "125463534";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AdvSearchForItemStaleCBOM Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ItemNumber.
        /// </summary>
        [TestVariable("1199a63d-7d8f-4a09-9dd7-763dfff08758")]
        public string ItemNumber
        {
            get { return repo.ItemNumber; }
            set { repo.ItemNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'PLMMainForm'.", repo.PLMMainForm.SelfInfo, new RecordItemIndex(0));
            repo.PLMMainForm.Self.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.UpperButtons.AdvancedSearch' at 10;9.", repo.PLMMainForm.UpperButtons.AdvancedSearchInfo, new RecordItemIndex(1));
            repo.PLMMainForm.UpperButtons.AdvancedSearch.Click("10;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.SelectAdvancedSearch' at 182;9.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.SelectAdvancedSearchInfo, new RecordItemIndex(2));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.SelectAdvancedSearch.Click("182;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.ATS_Item_Search' at 143;7.", repo.eBom_Add_Item.ATS_Item_SearchInfo, new RecordItemIndex(3));
            repo.eBom_Add_Item.ATS_Item_Search.Click("143;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextField' at 44;13.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextFieldInfo, new RecordItemIndex(4));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextField.Click("44;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ItemNumber' with focus on 'PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextField'.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextFieldInfo, new RecordItemIndex(5));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextField.PressKeys(ItemNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2Info, new RecordItemIndex(6));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(7));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2Info, new RecordItemIndex(8));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.StartAdvancedSearch' at 58;12.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.StartAdvancedSearchInfo, new RecordItemIndex(9));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.StartAdvancedSearch.Click("58;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(10));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'PLMMainForm.MainSplitPane.AdvancedSearchPane.CellItemNumberSearchResult'", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.CellItemNumberSearchResultInfo, new ActionTimeout(60000), new RecordItemIndex(11));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.CellItemNumberSearchResultInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.CellVersion1andAAItemNumberSearchResult' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.CellVersion1andAAItemNumberSearchResultInfo, new RecordItemIndex(12));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.CellVersion1andAAItemNumberSearchResult.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.CellVersion1andAAItemNumberSearchResult' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.CellVersion1andAAItemNumberSearchResultInfo, new RecordItemIndex(13));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.CellVersion1andAAItemNumberSearchResult.DoubleClick();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
