///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UpchainMechDeployTest
{
    public partial class CheckoutFileDontOpen
    {
    	public static Duration oldTimeout = repo.OwnershipRequest.SearchTimeout;
    	public static Duration newTimeout = 90000;
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void TrimFilePath()
        {
        	Filepath = Filepath.Substring("File checked out to ".Length);
        	Report.Log(ReportLevel.Info, "Filepath set to " + Filepath);
        }

        public void CheckForOwnership()
        {
        	string title = repo.PLMMainForm.Self.Title.ToString();
        	int start = title.IndexOf("as") + 2;
            int end = title.IndexOf("(") - 1;
            title = title.Substring(start, end - start).Trim();
            string creator = repo.PLMMainForm.MainSplitPane.Creator.TextValue.ToString().Trim();
            if (title != creator)
            {
            	Report.Info("Usernames do not match: " + title + " and " + creator + " extending search timeout for Ownership request");
            	repo.OwnershipRequest.SearchTimeout = newTimeout;
            }
            else
            {
            	Report.Info("Usernames match, not changing ownership timeout");
            }
            
        }

        public void ResetOwnershipTimeout()
        {
            repo.OwnershipRequest.SearchTimeout = oldTimeout;
        }

        public void DisplayOwnershipTimeout()
        {
        	Report.Info("Ownership timeout set to: " + repo.OwnershipRequest.SearchTimeout.ToString());
        }

        public void GetFilePath()
        {
        	string shortUsername;
        	shortUsername = Username.Replace("ATSNA\\","");
        	Filepath = @"C:\home\" + shortUsername + "\\" + Filename.Trim();
        	Report.Info("Filepath set to: " + Filepath);
        }

    }
}