///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpchainMechDeployTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeepCopyAsNewVersion recording.
    /// </summary>
    [TestModule("3423c30a-0c54-4604-a313-e7b8018d6d7b", ModuleType.Recording, 1)]
    public partial class DeepCopyAsNewVersion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpchainMechDeployTestRepository repository.
        /// </summary>
        public static UpchainMechDeployTestRepository repo = UpchainMechDeployTestRepository.Instance;

        static DeepCopyAsNewVersion instance = new DeepCopyAsNewVersion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeepCopyAsNewVersion()
        {
            InitialVersion = "";
            ResultText = "";
            FinalVersion = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeepCopyAsNewVersion Instance
        {
            get { return instance; }
        }

#region Variables

        string _InitialVersion;

        /// <summary>
        /// Gets or sets the value of variable InitialVersion.
        /// </summary>
        [TestVariable("0b2a6916-5ff2-41ca-8432-db42c78a74fb")]
        public string InitialVersion
        {
            get { return _InitialVersion; }
            set { _InitialVersion = value; }
        }

        string _ResultText;

        /// <summary>
        /// Gets or sets the value of variable ResultText.
        /// </summary>
        [TestVariable("85b9a621-bb96-4e32-9313-0cdbd63d7a04")]
        public string ResultText
        {
            get { return _ResultText; }
            set { _ResultText = value; }
        }

        string _FinalVersion;

        /// <summary>
        /// Gets or sets the value of variable FinalVersion.
        /// </summary>
        [TestVariable("7fdfcc12-d2ed-4827-b18d-b5234bb1fd29")]
        public string FinalVersion
        {
            get { return _FinalVersion; }
            set { _FinalVersion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ProjectNumber.
        /// </summary>
        [TestVariable("0e8fec4e-ba50-4421-ad69-fb3d747c11f9")]
        public string ProjectNumber
        {
            get { return repo.ProjectNumber; }
            set { repo.ProjectNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable EndItemNumber.
        /// </summary>
        [TestVariable("16ced886-72ec-46dc-b79b-e4ffdca03342")]
        public string EndItemNumber
        {
            get { return repo.EndItemNumber; }
            set { repo.EndItemNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Deep copy as new version from engineering tab
            Report.Log(ReportLevel.Info, "Section", "Deep copy as new version from engineering tab", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PLMMainForm.MainSplitPane.NavigationPane.TreeItemEndItemNumber' at Center.", repo.PLMMainForm.MainSplitPane.NavigationPane.TreeItemEndItemNumberInfo, new RecordItemIndex(1));
            repo.PLMMainForm.MainSplitPane.NavigationPane.TreeItemEndItemNumber.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.TabItemEngineering' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.TabItemEngineeringInfo, new RecordItemIndex(2));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.TabItemEngineering.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEdit' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEditInfo, new RecordItemIndex(3));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEdit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel' and assigning its value to variable 'InitialVersion'.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevelInfo, new RecordItemIndex(4));
            InitialVersion = repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevelInfo, new RecordItemIndex(5));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java.DeepCopy' at 64;11.", repo.Java.DeepCopyInfo, new RecordItemIndex(6));
            repo.Java.DeepCopy.Click("64;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeepCopy.False' at 20;6.", repo.DeepCopy.FalseInfo, new RecordItemIndex(7));
            repo.DeepCopy.False.Click("20;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeepCopy.DeepCopyAsNewVersion' at 57;7.", repo.DeepCopy.DeepCopyAsNewVersionInfo, new RecordItemIndex(8));
            repo.DeepCopy.DeepCopyAsNewVersion.Click("57;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'PLMMainForm.LastMessage'", repo.PLMMainForm.LastMessageInfo, new ActionTimeout(60000), new RecordItemIndex(9));
            repo.PLMMainForm.LastMessageInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PLMMainForm.LastMessage' and assigning its value to variable 'ResultText'.", repo.PLMMainForm.LastMessageInfo, new RecordItemIndex(10));
            ResultText = repo.PLMMainForm.LastMessage.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", ResultText, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevelInfo, new RecordItemIndex(12));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel' and assigning its value to variable 'FinalVersion'.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevelInfo, new RecordItemIndex(13));
            FinalVersion = repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Initial verison was", new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "User", InitialVersion, new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "User", "Final version is", new RecordItemIndex(16));
            
            Report.Log(ReportLevel.Info, "User", FinalVersion, new RecordItemIndex(17));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PLMMainForm.Self, false, new RecordItemIndex(18));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
