///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpchainMechDeployTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GetItemAttributesSW recording.
    /// </summary>
    [TestModule("c2b49143-a46b-4581-9112-6d6a45bd6d83", ModuleType.Recording, 1)]
    public partial class GetItemAttributesSW : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpchainMechDeployTestRepository repository.
        /// </summary>
        public static UpchainMechDeployTestRepository repo = UpchainMechDeployTestRepository.Instance;

        static GetItemAttributesSW instance = new GetItemAttributesSW();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GetItemAttributesSW()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GetItemAttributesSW Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.ElementHost1.GridNav.ButtonHome.Container.ButtonItem' at Center.", repo.SOLIDWORKS.ElementHost1.GridNav.ButtonHome.Container.ButtonItemInfo, new RecordItemIndex(0));
            repo.SOLIDWORKS.ElementHost1.GridNav.ButtonHome.Container.ButtonItem.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ButtonRefresh' at Center.", repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ButtonRefreshInfo, new RecordItemIndex(1));
            repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ButtonRefresh.Click();
            Delay.Milliseconds(200);
            
            GetItemAttributesPlugin();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ButtonEdit' at Center.", repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ButtonEditInfo, new RecordItemIndex(3));
            repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ButtonEdit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 3m to exist. Associated repository item: 'SOLIDWORKS.ElementHost1.StatusBarContainer.statusEditMode'", repo.SOLIDWORKS.ElementHost1.StatusBarContainer.statusEditModeInfo, new ActionTimeout(180000), new RecordItemIndex(4));
            repo.SOLIDWORKS.ElementHost1.StatusBarContainer.statusEditModeInfo.WaitForExists(180000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.ShapeAttribute.ShapeAttrComboBox' at Center.", repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.ShapeAttribute.ShapeAttrComboBox.SelfInfo, new RecordItemIndex(5));
            repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.ShapeAttribute.ShapeAttrComboBox.Self.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SLDWORKS.Pipe' at Center.", repo.SLDWORKS.PipeInfo, new RecordItemIndex(6));
            repo.SLDWORKS.Pipe.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.MaterialAttribute.MaterialAttrComboBox' at Center.", repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.MaterialAttribute.MaterialAttrComboBox.SelfInfo, new RecordItemIndex(7));
            repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.MaterialAttribute.MaterialAttrComboBox.Self.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SLDWORKS.PVCforPipe' at Center.", repo.SLDWORKS.PVCforPipeInfo, new RecordItemIndex(8));
            repo.SLDWORKS.PVCforPipe.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.FinishAttribute.FinishAttrComboBox' at Center.", repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.FinishAttribute.FinishAttrComboBox.SelfInfo, new RecordItemIndex(9));
            repo.SOLIDWORKS.ElementHost1.StatusBarContainer.GripContainer.GridBody.ItemAttributes.GridItems.FinishAttribute.FinishAttrComboBox.Self.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SLDWORKS.NONETRACEABLE' at Center.", repo.SLDWORKS.NONETRACEABLEInfo, new RecordItemIndex(10));
            repo.SLDWORKS.NONETRACEABLE.Click();
            Delay.Milliseconds(200);
            
            GetNewItemAttributesPlugin();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.ElementHost1.GridNav.Container.AttributesHistoryButton' at Center.", repo.SOLIDWORKS.ElementHost1.GridNav.Container.AttributesHistoryButtonInfo, new RecordItemIndex(12));
            repo.SOLIDWORKS.ElementHost1.GridNav.Container.AttributesHistoryButton.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SLDWORKS.Self, false, new RecordItemIndex(13));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
