///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpchainMechDeployTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RemoveSecondaryDrawing recording.
    /// </summary>
    [TestModule("beebe76b-afc4-452a-ae52-0af8e2b957d3", ModuleType.Recording, 1)]
    public partial class RemoveSecondaryDrawing : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpchainMechDeployTestRepository repository.
        /// </summary>
        public static UpchainMechDeployTestRepository repo = UpchainMechDeployTestRepository.Instance;

        static RemoveSecondaryDrawing instance = new RemoveSecondaryDrawing();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RemoveSecondaryDrawing()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RemoveSecondaryDrawing Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'PLMMainForm'.", repo.PLMMainForm.SelfInfo, new RecordItemIndex(0));
            repo.PLMMainForm.Self.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.UpperButtons.AdvancedSearch' at 10;9.", repo.PLMMainForm.UpperButtons.AdvancedSearchInfo, new RecordItemIndex(1));
            repo.PLMMainForm.UpperButtons.AdvancedSearch.Click("10;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.SelectAdvancedSearch' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.SelectAdvancedSearchInfo, new RecordItemIndex(2));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.SelectAdvancedSearch.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.ATS_Item_Search' at Center.", repo.eBom_Add_Item.ATS_Item_SearchInfo, new RecordItemIndex(3));
            repo.eBom_Add_Item.ATS_Item_Search.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextField' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextFieldInfo, new RecordItemIndex(4));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextField.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '13615-1005-0003' with focus on 'PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextField'.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextFieldInfo, new RecordItemIndex(5));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.WorxTextField.PressKeys("13615-1005-0003");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2Info, new RecordItemIndex(6));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(7));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2Info, new RecordItemIndex(8));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(9));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2Info, new RecordItemIndex(10));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java2.ItemNameDropDown' at Center.", repo.Java2.ItemNameDropDownInfo, new RecordItemIndex(11));
            repo.Java2.ItemNameDropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.Status' at Center.", repo.eBom_Add_Item.StatusInfo, new RecordItemIndex(12));
            repo.eBom_Add_Item.Status.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java2.StatusDropDown' at Center.", repo.Java2.StatusDropDownInfo, new RecordItemIndex(13));
            repo.Java2.StatusDropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.ReleasedExternal' at Center.", repo.eBom_Add_Item.ReleasedExternalInfo, new RecordItemIndex(14));
            repo.eBom_Add_Item.ReleasedExternal.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.StartAdvancedSearch' at 58;12.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.StartAdvancedSearchInfo, new RecordItemIndex(15));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.StartAdvancedSearch.Click("58;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(16));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to exist. Associated repository item: 'PLMMainForm.MainSplitPane.CellReleasedExternal'", repo.PLMMainForm.MainSplitPane.CellReleasedExternalInfo, new ActionTimeout(120000), new RecordItemIndex(17));
            repo.PLMMainForm.MainSplitPane.CellReleasedExternalInfo.WaitForExists(120000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PLMMainForm.MainSplitPane.CellReleasedExternal' at Center.", repo.PLMMainForm.MainSplitPane.CellReleasedExternalInfo, new RecordItemIndex(18));
            repo.PLMMainForm.MainSplitPane.CellReleasedExternal.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.TabItemEngineering' at Center.", repo.PLMMainForm.MainSplitPane.TabItemEngineeringInfo, new RecordItemIndex(19));
            repo.PLMMainForm.MainSplitPane.TabItemEngineering.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.CellFirstCell' at Center.", repo.PLMMainForm.MainSplitPane.CellFirstCellInfo, new RecordItemIndex(20));
            repo.PLMMainForm.MainSplitPane.CellFirstCell.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.CellFirstCell' at Center.", repo.PLMMainForm.MainSplitPane.CellFirstCellInfo, new RecordItemIndex(21));
            repo.PLMMainForm.MainSplitPane.CellFirstCell.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java.DeepCopy' at Center.", repo.Java.DeepCopyInfo, new RecordItemIndex(22));
            repo.Java.DeepCopy.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeepCopy.False' at Center.", repo.DeepCopy.FalseInfo, new RecordItemIndex(23));
            repo.DeepCopy.False.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeepCopy.DeepCopyAsNewVersion' at Center.", repo.DeepCopy.DeepCopyAsNewVersionInfo, new RecordItemIndex(24));
            repo.DeepCopy.DeepCopyAsNewVersion.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.TabItemDocuments' at Center.", repo.PLMMainForm.MainSplitPane.TabItemDocumentsInfo, new RecordItemIndex(25));
            repo.PLMMainForm.MainSplitPane.TabItemDocuments.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.N32609148SLDDRW' at Center.", repo.PLMMainForm.MainSplitPane.N32609148SLDDRWInfo, new RecordItemIndex(26));
            repo.PLMMainForm.MainSplitPane.N32609148SLDDRW.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.N32609148SLDDRW' at Center.", repo.PLMMainForm.MainSplitPane.N32609148SLDDRWInfo, new RecordItemIndex(27));
            repo.PLMMainForm.MainSplitPane.N32609148SLDDRW.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java.Remove' at Center.", repo.Java.RemoveInfo, new RecordItemIndex(28));
            repo.Java.Remove.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Confirmation.ButtonYes' at Center.", repo.Confirmation.ButtonYesInfo, new RecordItemIndex(29));
            repo.Confirmation.ButtonYes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'PLMMainForm.MainSplitPane.N32609148SLDDRW'.", repo.PLMMainForm.MainSplitPane.N32609148SLDDRWInfo, new RecordItemIndex(30));
            Validate.NotExists(repo.PLMMainForm.MainSplitPane.N32609148SLDDRWInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.AdvancedSearch' at Center.", repo.PLMMainForm.AdvancedSearchInfo, new RecordItemIndex(31));
            repo.PLMMainForm.AdvancedSearch.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.SelectSearchCombo' at Center.", repo.PLMMainForm.MainSplitPane.SelectSearchComboInfo, new RecordItemIndex(32));
            repo.PLMMainForm.MainSplitPane.SelectSearchCombo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java.ATS_Item_Search' at Center.", repo.Java.ATS_Item_SearchInfo, new RecordItemIndex(33));
            repo.Java.ATS_Item_Search.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.WorxTextField1' at Center.", repo.PLMMainForm.MainSplitPane.WorxTextField1Info, new RecordItemIndex(34));
            repo.PLMMainForm.MainSplitPane.WorxTextField1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '25261357' with focus on 'PLMMainForm.MainSplitPane.WorxTextField1'.", repo.PLMMainForm.MainSplitPane.WorxTextField1Info, new RecordItemIndex(35));
            repo.PLMMainForm.MainSplitPane.WorxTextField1.PressKeys("25261357");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2Info, new RecordItemIndex(36));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(37));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2' at Center.", repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2Info, new RecordItemIndex(38));
            repo.PLMMainForm.MainSplitPane.AdvancedSearchPane.Button2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.StartAdvancedSearch' at Center.", repo.PLMMainForm.MainSplitPane.StartAdvancedSearchInfo, new RecordItemIndex(39));
            repo.PLMMainForm.MainSplitPane.StartAdvancedSearch.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'PLMMainForm.MainSplitPane.tableVisible'", repo.PLMMainForm.MainSplitPane.tableVisibleInfo, new ActionTimeout(60000), new RecordItemIndex(40));
            repo.PLMMainForm.MainSplitPane.tableVisibleInfo.WaitForExists(60000);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(41));
            //Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'PLMMainForm.MainSplitPane.CellFirstCellAdvancedSearch' at Center.", repo.PLMMainForm.MainSplitPane.CellFirstCellAdvancedSearchInfo, new RecordItemIndex(42));
            repo.PLMMainForm.MainSplitPane.CellFirstCellAdvancedSearch.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PLMMainForm.MainSplitPane.CellFirstCellAdvancedSearch' at Center.", repo.PLMMainForm.MainSplitPane.CellFirstCellAdvancedSearchInfo, new RecordItemIndex(43));
            repo.PLMMainForm.MainSplitPane.CellFirstCellAdvancedSearch.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.TabItemDocuments' at Center.", repo.PLMMainForm.MainSplitPane.TabItemDocumentsInfo, new RecordItemIndex(44));
            repo.PLMMainForm.MainSplitPane.TabItemDocuments.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.AP25885814SLDDRW' at Center.", repo.PLMMainForm.MainSplitPane.AP25885814SLDDRWInfo, new RecordItemIndex(45));
            repo.PLMMainForm.MainSplitPane.AP25885814SLDDRW.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.AP25885814SLDDRW' at Center.", repo.PLMMainForm.MainSplitPane.AP25885814SLDDRWInfo, new RecordItemIndex(46));
            repo.PLMMainForm.MainSplitPane.AP25885814SLDDRW.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'Java.Remove'.", repo.Java.RemoveInfo, new RecordItemIndex(47));
            Validate.NotExists(repo.Java.RemoveInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java2.TxtDescription' at Center.", repo.Java2.TxtDescriptionInfo, new RecordItemIndex(48));
            repo.Java2.TxtDescription.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
