///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpchainMechDeployTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RequisitionReleasedItemsInTopLevel recording.
    /// </summary>
    [TestModule("4845ce20-10b8-43e3-8f26-a4e853778007", ModuleType.Recording, 1)]
    public partial class RequisitionReleasedItemsInTopLevel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpchainMechDeployTestRepository repository.
        /// </summary>
        public static UpchainMechDeployTestRepository repo = UpchainMechDeployTestRepository.Instance;

        static RequisitionReleasedItemsInTopLevel instance = new RequisitionReleasedItemsInTopLevel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RequisitionReleasedItemsInTopLevel()
        {
            ProjectNumber = "13563";
            ChildCount = "";
            ReqNumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RequisitionReleasedItemsInTopLevel Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ProjectNumber.
        /// </summary>
        [TestVariable("00173edc-830b-4b94-b23c-94fa90e175d9")]
        public string ProjectNumber
        {
            get { return repo.ProjectNumber; }
            set { repo.ProjectNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable EndItemNumber.
        /// </summary>
        [TestVariable("16ced886-72ec-46dc-b79b-e4ffdca03342")]
        public string EndItemNumber
        {
            get { return repo.EndItemNumber; }
            set { repo.EndItemNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ChildCount.
        /// </summary>
        [TestVariable("f2c0963c-e94a-44b4-afbb-e06b43b78713")]
        public string ChildCount
        {
            get { return repo.ChildCount; }
            set { repo.ChildCount = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ReqNumber.
        /// </summary>
        [TestVariable("cb61cd0c-d5e6-4ee9-8ab1-af1989221a59")]
        public string ReqNumber
        {
            get { return repo.ReqNumber; }
            set { repo.ReqNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Create Requisition
            Report.Log(ReportLevel.Info, "Section", "Create Requisition", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'PLMMainForm'.", repo.PLMMainForm.SelfInfo, new RecordItemIndex(1));
            repo.PLMMainForm.Self.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'PLMMainForm.MainSplitPane.CustomerTree'.", repo.PLMMainForm.MainSplitPane.CustomerTreeInfo, new RecordItemIndex(2));
            repo.PLMMainForm.MainSplitPane.CustomerTree.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ProjectNumber' with focus on 'PLMMainForm.MainSplitPane.CustomerTree'.", repo.PLMMainForm.MainSplitPane.CustomerTreeInfo, new RecordItemIndex(3));
            repo.PLMMainForm.MainSplitPane.CustomerTree.PressKeys(ProjectNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.TreeItemProjectNumber' at 16;3.", repo.PLMMainForm.MainSplitPane.TreeItemProjectNumberInfo, new RecordItemIndex(4));
            repo.PLMMainForm.MainSplitPane.TreeItemProjectNumber.Click(System.Windows.Forms.MouseButtons.Right, "16;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java.Expand' at 49;13.", repo.Java.ExpandInfo, new RecordItemIndex(5));
            repo.Java.Expand.Click("49;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'ChildIndex' from item 'PLMMainForm.MainSplitPane.TreeItemEndItemNumber' and assigning its value to variable 'ChildCount'.", repo.PLMMainForm.MainSplitPane.TreeItemEndItemNumberInfo, new RecordItemIndex(6));
            ChildCount = repo.PLMMainForm.MainSplitPane.TreeItemEndItemNumber.Element.GetAttributeValueText("ChildIndex");
            Delay.Milliseconds(0);
            
            ChildIndexPlusOne();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'ChildCount' from item 'PLMMainForm.MainSplitPane.TreeItemProductStructure' and assigning its value to variable 'ChildCount'.", repo.PLMMainForm.MainSplitPane.TreeItemProductStructureInfo, new RecordItemIndex(8));
            //ChildCount = repo.PLMMainForm.MainSplitPane.TreeItemProductStructure.Element.GetAttributeValueText("ChildCount");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.TreeItemProjectNumber' at 16;3.", repo.PLMMainForm.MainSplitPane.TreeItemProjectNumberInfo, new RecordItemIndex(9));
            repo.PLMMainForm.MainSplitPane.TreeItemProjectNumber.Click(System.Windows.Forms.MouseButtons.Right, "16;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java.NewRequisition' at 84;8.", repo.Java.NewRequisitionInfo, new RecordItemIndex(10));
            repo.Java.NewRequisition.Click("84;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreateRequisition.SelectItemBtn' at 16;11.", repo.CreateRequisition.SelectItemBtnInfo, new RecordItemIndex(11));
            repo.CreateRequisition.SelectItemBtn.Click("16;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RequisitionSelectEndItem.False' at 49;11.", repo.RequisitionSelectEndItem.FalseInfo, new RecordItemIndex(12));
            repo.RequisitionSelectEndItem.False.Click("49;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RequisitionSelectEndItem.ButtonOK' at 52;12.", repo.RequisitionSelectEndItem.ButtonOKInfo, new RecordItemIndex(13));
            repo.RequisitionSelectEndItem.ButtonOK.Click("52;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreateRequisition.Create' at 30;9.", repo.CreateRequisition.CreateInfo, new RecordItemIndex(14));
            repo.CreateRequisition.Create.Click("30;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PLMMainForm.MainSplitPane.RequisitionNumber' and assigning its value to variable 'ReqNumber'.", repo.PLMMainForm.MainSplitPane.RequisitionNumberInfo, new RecordItemIndex(15));
            ReqNumber = repo.PLMMainForm.MainSplitPane.RequisitionNumber.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.SelectWorkflow' at 158;10.", repo.PLMMainForm.MainSplitPane.SelectWorkflowInfo, new RecordItemIndex(16));
            repo.PLMMainForm.MainSplitPane.SelectWorkflow.Click("158;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java.ReqWorkflowItemWoConfig' at 125;13.", repo.Java.ReqWorkflowItemWoConfigInfo, new RecordItemIndex(17));
            repo.Java.ReqWorkflowItemWoConfig.Click("125;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.RequisitionFalse' at 6;6.", repo.PLMMainForm.MainSplitPane.RequisitionFalseInfo, new RecordItemIndex(18));
            repo.PLMMainForm.MainSplitPane.RequisitionFalse.Click(System.Windows.Forms.MouseButtons.Right, "6;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Java.SelectAllReleased' at 77;4.", repo.Java.SelectAllReleasedInfo, new RecordItemIndex(19));
            repo.Java.SelectAllReleased.Click("77;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.Save' at 58;13.", repo.PLMMainForm.MainSplitPane.SaveInfo, new RecordItemIndex(20));
            repo.PLMMainForm.MainSplitPane.Save.Click("58;13");
            Delay.Milliseconds(200);
            
            // Approve as Self
            Report.Log(ReportLevel.Info, "Section", "Approve as Self", new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.wfButtonStart' at 38;7.", repo.PLMMainForm.MainSplitPane.wfButtonStartInfo, new RecordItemIndex(22));
            repo.PLMMainForm.MainSplitPane.wfButtonStart.Click("38;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(23));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15m to exist. Associated repository item: 'PLMMainForm.MainSplitPane.wfButtonApprove'", repo.PLMMainForm.MainSplitPane.wfButtonApproveInfo, new ActionTimeout(900000), new RecordItemIndex(24));
            repo.PLMMainForm.MainSplitPane.wfButtonApproveInfo.WaitForExists(900000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.wfButtonApprove' at Center.", repo.PLMMainForm.MainSplitPane.wfButtonApproveInfo, new RecordItemIndex(25));
            repo.PLMMainForm.MainSplitPane.wfButtonApprove.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15m to exist. Associated repository item: 'PLMMainForm.MainSplitPane.StatusEqPMApproval'", repo.PLMMainForm.MainSplitPane.StatusEqPMApprovalInfo, new ActionTimeout(900000), new RecordItemIndex(26));
            repo.PLMMainForm.MainSplitPane.StatusEqPMApprovalInfo.WaitForExists(900000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PLMMainForm.Self, false, new RecordItemIndex(27));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
