///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestforJenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestforJenkinsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("cfd3ca57-6f1c-431d-acb4-4d3128160660")]
    public partial class TestforJenkinsRepository : RepoGenBaseFolder
    {
        static TestforJenkinsRepository instance = new TestforJenkinsRepository();
        TestforJenkinsRepositoryFolders.GoogleAppFolder _google;
        TestforJenkinsRepositoryFolders.BreadGoogleSearchGoogleChromeAppFolder _breadgooglesearchgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the TestforJenkinsRepository element repository.
        /// </summary>
        [RepositoryFolder("cfd3ca57-6f1c-431d-acb4-4d3128160660")]
        public static TestforJenkinsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestforJenkinsRepository() 
            : base("TestforJenkinsRepository", "/", null, 0, false, "cfd3ca57-6f1c-431d-acb4-4d3128160660", ".\\RepositoryImages\\TestforJenkinsRepositorycfd3ca57.rximgres")
        {
            _google = new TestforJenkinsRepositoryFolders.GoogleAppFolder(this);
            _breadgooglesearchgooglechrome = new TestforJenkinsRepositoryFolders.BreadGoogleSearchGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cfd3ca57-6f1c-431d-acb4-4d3128160660")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Google folder.
        /// </summary>
        [RepositoryFolder("0ca82b7c-f99c-4223-b200-6ff15fad8811")]
        public virtual TestforJenkinsRepositoryFolders.GoogleAppFolder Google
        {
            get { return _google; }
        }

        /// <summary>
        /// The BreadGoogleSearchGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("886f288a-35a9-4679-8d40-1efbb5cac49e")]
        public virtual TestforJenkinsRepositoryFolders.BreadGoogleSearchGoogleChromeAppFolder BreadGoogleSearchGoogleChrome
        {
            get { return _breadgooglesearchgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestforJenkinsRepositoryFolders
    {
        /// <summary>
        /// The GoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("0ca82b7c-f99c-4223-b200-6ff15fad8811")]
        public partial class GoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lstibInfo;
            RepoItemInfo _breadInfo;
            RepoItemInfo _inputtagqInfo;
            RepoItemInfo _bread1Info;

            /// <summary>
            /// Creates a new Google  folder.
            /// </summary>
            public GoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Google", "/dom[@domain='www.google.com']", parentFolder, 30000, null, false, "0ca82b7c-f99c-4223-b200-6ff15fad8811", "")
            {
                _lstibInfo = new RepoItemInfo(this, "LstIb", ".//input[#'lst-ib']", 30000, null, "f72885e0-1b92-4562-9baf-6061f470cbd5");
                _breadInfo = new RepoItemInfo(this, "Bread", ".//div[#'rhs_block']/div[1]/div[1]/div/div[1]/div[2]/div[1]//span[@innertext='Bread']", 30000, null, "980f67f8-8c7b-4f52-a647-629377c33ee4");
                _inputtagqInfo = new RepoItemInfo(this, "InputTagQ", ".//form[#'tsf']/div[2]/div/div[1]//input[@title='Search']", 30000, null, "88a98f80-9a15-4bb7-be6e-394692e264cc");
                _bread1Info = new RepoItemInfo(this, "Bread1", ".//div[#'rhs_block']/div[1]/div[1]/div/div[1]/div[2]/div[2]//span[@innertext='Bread']", 30000, null, "f2589535-d9e4-4866-9463-78292d60fcb8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0ca82b7c-f99c-4223-b200-6ff15fad8811")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0ca82b7c-f99c-4223-b200-6ff15fad8811")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LstIb item.
            /// </summary>
            [RepositoryItem("f72885e0-1b92-4562-9baf-6061f470cbd5")]
            public virtual Ranorex.InputTag LstIb
            {
                get
                {
                    return _lstibInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LstIb item info.
            /// </summary>
            [RepositoryItemInfo("f72885e0-1b92-4562-9baf-6061f470cbd5")]
            public virtual RepoItemInfo LstIbInfo
            {
                get
                {
                    return _lstibInfo;
                }
            }

            /// <summary>
            /// The Bread item.
            /// </summary>
            [RepositoryItem("980f67f8-8c7b-4f52-a647-629377c33ee4")]
            public virtual Ranorex.SpanTag Bread
            {
                get
                {
                    return _breadInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Bread item info.
            /// </summary>
            [RepositoryItemInfo("980f67f8-8c7b-4f52-a647-629377c33ee4")]
            public virtual RepoItemInfo BreadInfo
            {
                get
                {
                    return _breadInfo;
                }
            }

            /// <summary>
            /// The InputTagQ item.
            /// </summary>
            [RepositoryItem("88a98f80-9a15-4bb7-be6e-394692e264cc")]
            public virtual Ranorex.InputTag InputTagQ
            {
                get
                {
                    return _inputtagqInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagQ item info.
            /// </summary>
            [RepositoryItemInfo("88a98f80-9a15-4bb7-be6e-394692e264cc")]
            public virtual RepoItemInfo InputTagQInfo
            {
                get
                {
                    return _inputtagqInfo;
                }
            }

            /// <summary>
            /// The Bread1 item.
            /// </summary>
            [RepositoryItem("f2589535-d9e4-4866-9463-78292d60fcb8")]
            public virtual Ranorex.SpanTag Bread1
            {
                get
                {
                    return _bread1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Bread1 item info.
            /// </summary>
            [RepositoryItemInfo("f2589535-d9e4-4866-9463-78292d60fcb8")]
            public virtual RepoItemInfo Bread1Info
            {
                get
                {
                    return _bread1Info;
                }
            }
        }

        /// <summary>
        /// The BreadGoogleSearchGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("886f288a-35a9-4679-8d40-1efbb5cac49e")]
        public partial class BreadGoogleSearchGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new BreadGoogleSearchGoogleChrome  folder.
            /// </summary>
            public BreadGoogleSearchGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BreadGoogleSearchGoogleChrome", "/form[@title~'^bread\\ -\\ Google\\ Search\\ -\\ G']", parentFolder, 30000, null, true, "886f288a-35a9-4679-8d40-1efbb5cac49e", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "container[@accessiblename~'^bread\\ -\\ Google\\ Search\\ -\\ G']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename='bread - Google Search']/button[@accessiblename='Close']", 30000, null, "c72e3cf4-fb85-4e21-aa7a-f69e9b593f63");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("886f288a-35a9-4679-8d40-1efbb5cac49e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("886f288a-35a9-4679-8d40-1efbb5cac49e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("c72e3cf4-fb85-4e21-aa7a-f69e9b593f63")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("c72e3cf4-fb85-4e21-aa7a-f69e9b593f63")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
