///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GlobalServicesPlatformTesting
{
    public partial class ChangePasswordOFSC
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public string GetNewPassword(string currentPW, string filePathToTextFile)
        {
            if (currentPW == "Welcome1")
        	{
        		GSPUserCodeCollection.WriteAllTextToFile(@filePathToTextFile, "Welcome2");
        		return "Welcome2";
        	}
        	
        	if (currentPW == "Welcome2")
        	{
        		GSPUserCodeCollection.WriteAllTextToFile(@filePathToTextFile, "Welcome1");
        		return "Welcome1";
        	}
        	
        	else
        		
        	{
        		Ranorex.Report.Failure("Error password not set properly");
        		return "";
        	}
        }

    }
}
