///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PLMTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LaunchPLMDev recording.
    /// </summary>
    [TestModule("ccd58b27-eb88-421d-874f-bff3b670f1eb", ModuleType.Recording, 1)]
    public partial class LaunchPLMDev : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PLMTestRepository repository.
        /// </summary>
        public static PLMTestRepository repo = PLMTestRepository.Instance;

        static LaunchPLMDev instance = new LaunchPLMDev();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LaunchPLMDev()
        {
            varLogin = "loginpassword";
            varUserName = "username";
            varUpchainVersion = "default";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LaunchPLMDev Instance
        {
            get { return instance; }
        }

#region Variables

        string _varLogin;

        /// <summary>
        /// Gets or sets the value of variable varLogin.
        /// </summary>
        [TestVariable("b2d8ff1a-3b0b-4fdc-b6ea-2ff803db0d49")]
        public string varLogin
        {
            get { return _varLogin; }
            set { _varLogin = value; }
        }

        string _varUserName;

        /// <summary>
        /// Gets or sets the value of variable varUserName.
        /// </summary>
        [TestVariable("9bbc0fe5-4800-4784-8a78-d07eb83998a8")]
        public string varUserName
        {
            get { return _varUserName; }
            set { _varUserName = value; }
        }

        string _varUpchainVersion;

        /// <summary>
        /// Gets or sets the value of variable varUpchainVersion.
        /// </summary>
        [TestVariable("902e1e8b-68e2-4529-8543-65207e245d44")]
        public string varUpchainVersion
        {
            get { return _varUpchainVersion; }
            set { _varUpchainVersion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Elec_Deploy_Test\\PLM Worx Shortcuts\\DEV.bat' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Elec_Deploy_Test\\PLM Worx Shortcuts\\DEV.bat", "", "\\\\ca01a9001\\pgmis\\Development\\Ranorex\\Elec_Deploy_Test\\PLM Worx Shortcuts", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to not exist. Associated repository item: 'CWindowsSystem32CmdExe'", repo.CWindowsSystem32CmdExe.SelfInfo, new ActionTimeout(60000), new RecordItemIndex(2));
            repo.CWindowsSystem32CmdExe.SelfInfo.WaitForNotExists(60000);
            
            Report.Log(ReportLevel.Info, "Application", "Run application 'V:\\zDebug_Launch_PLMWorx_64bit.bat' with arguments '' in normal mode.", new RecordItemIndex(3));
            Host.Local.RunApplication("V:\\zDebug_Launch_PLMWorx_64bit.bat", "", "V:\\", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'LoginForm'.", repo.LoginForm.SelfInfo, new RecordItemIndex(4));
            repo.LoginForm.Self.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'AccessibleName' from item 'LoginForm' and assigning its value to variable 'varUpchainVersion'.", repo.LoginForm.SelfInfo, new RecordItemIndex(5));
            varUpchainVersion = repo.LoginForm.Self.Element.GetAttributeValueText("AccessibleName");
            Delay.Milliseconds(0);
            
            GetUpChainXLM();
            Delay.Milliseconds(0);
            
            DecryptPassword();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varLogin' on item 'LoginForm.LoginPanel.TxtPasswd'.", repo.LoginForm.LoginPanel.TxtPasswdInfo, new RecordItemIndex(8));
            repo.LoginForm.LoginPanel.TxtPasswd.Element.SetAttributeValue("Text", varLogin);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginForm.LoginPanel.TxtName' at Center.", repo.LoginForm.LoginPanel.TxtNameInfo, new RecordItemIndex(9));
            repo.LoginForm.LoginPanel.TxtName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varUserName' on item 'LoginForm.LoginPanel.TxtName'.", repo.LoginForm.LoginPanel.TxtNameInfo, new RecordItemIndex(10));
            repo.LoginForm.LoginPanel.TxtName.Element.SetAttributeValue("Text", varUserName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginForm.LoginPanel.TxtName' at Center.", repo.LoginForm.LoginPanel.TxtNameInfo, new RecordItemIndex(11));
            repo.LoginForm.LoginPanel.TxtName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginForm.LoginPanel.Login' at 48;8.", repo.LoginForm.LoginPanel.LoginInfo, new RecordItemIndex(12));
            repo.LoginForm.LoginPanel.Login.Click("48;8");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
