///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CamDesigner
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoadFavourite recording.
    /// </summary>
    [TestModule("11440fc2-05c2-457c-9c11-32feb262f2e6", ModuleType.Recording, 1)]
    public partial class LoadFavourite : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CamDesignerRepository repository.
        /// </summary>
        public static CamDesignerRepository repo = CamDesignerRepository.Instance;

        static LoadFavourite instance = new LoadFavourite();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoadFavourite()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoadFavourite Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite' at Center.", repo.CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite.SelfInfo, new RecordItemIndex(0));
            repo.CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite.Self.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesigner1.Load' at 105;13.", repo.CamDesigner1.LoadInfo, new RecordItemIndex(1));
            repo.CamDesigner1.Load.Click("105;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite' at Center.", repo.CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite.SelfInfo, new RecordItemIndex(2));
            repo.CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite.Self.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesigner1.Remove' at Center.", repo.CamDesigner1.RemoveInfo, new RecordItemIndex(3));
            repo.CamDesigner1.Remove.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Confirm.ButtonNo' at Center.", repo.Confirm.ButtonNoInfo, new RecordItemIndex(4));
            repo.Confirm.ButtonNo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite' at Center.", repo.CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite.SelfInfo, new RecordItemIndex(5));
            repo.CamDesignerUniversal.TreeView.FavouritesFolder.LastFavourite.Self.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesigner1.Remove' at Center.", repo.CamDesigner1.RemoveInfo, new RecordItemIndex(6));
            repo.CamDesigner1.Remove.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Confirm.ButtonYes' at Center.", repo.Confirm.ButtonYesInfo, new RecordItemIndex(7));
            repo.Confirm.ButtonYes.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
