///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DDM_Lite_Full_Test
{
    public partial class DDM_Lite_Oregon_Reports
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        /// 
           public static string p1 = @"C:\home\DDM_Lite\DDMmechBOMExtract.txt";
           public static string p2 = @"C:\home\DDM_Lite\DDMmechBOMExtractcompare.txt";
           public static string p3 = @"C:\home\DDM_Lite\DDMmechBOMExtractNEQ.txt";
           public static string p4 = @"C:\home\DDM_Lite\DDMmechBOMExtractcompareNEQ.txt";
        
        public static Duration oldDurationMainForm {get; private set;}
        public static Duration oldDurationSubForm {get; private set;}
        public static Duration oldDuration {get; private set;}
        
        private void Init()
        {
            // Your recording specific initialization code goes here.
            filenamePath = p2;
            fileNamePathNEQ = p4;

        }

        public void CompareExcel()
        {
        	Validate.IsTrue(FileEquals(p1,p2), "Checking if DDM Mech BOM Extract Files are Equal.  The Validation @ValidateRESULT@.");
        }
        
        public static bool FileEquals (string path1, string path2)
        {
        	byte[] file1 = File.ReadAllBytes(path1);
            byte[] file2 = File.ReadAllBytes(path2);
            if (file1.Length == file2.Length)
            {
                for (int i = 0; i < file1.Length; i++)
                {
                    if (file1[i] != file2[i])
                    {
                        return false;
                    }
                }
                return true;
            }
            return false;
        }

        public void ShortenDurationTreeView()
        {
        	Duration newDuration = new Duration(1500);  
  			oldDurationMainForm = repo.FormCa01a9001PgmisDeploymentDEVDDM.SearchTimeout;
			oldDurationSubForm = repo.FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.SearchTimeout;
			oldDuration = repo.FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.projectDataTabItem.TreeView1.SelfInfo.SearchTimeout;
			
			repo.FormCa01a9001PgmisDeploymentDEVDDM.SearchTimeout = newDuration;
  			repo.FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.SearchTimeout = newDuration;
  			repo.FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.projectDataTabItem.TreeView1.SelfInfo.SearchTimeout = newDuration;
        }

        public void RestoreDurationTreeView()
        {
        	repo.FormCa01a9001PgmisDeploymentDEVDDM.SearchTimeout = oldDurationMainForm;
        	repo.FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.SearchTimeout = oldDurationSubForm;
        	repo.FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.projectDataTabItem.TreeView1.SelfInfo.SearchTimeout = oldDuration;
        }

        public void WatchForSaveChanges()
        {
        	PopupWatcher saveChangesPopUp = new PopupWatcher();
        	saveChangesPopUp.WatchAndClick(repo.SaveChanges.SelfInfo, repo.SaveChanges.DontSaveInfo);
        	saveChangesPopUp.Start();
        }

        public void WatchforConfirmSaveAs()
        {
        	PopupWatcher confirmSaveAsPopUp = new PopupWatcher();
        	confirmSaveAsPopUp.WatchAndClick(repo.ConfirmSaveAs.SelfInfo, repo.ConfirmSaveAs.ButtonYesInfo);
        	confirmSaveAsPopUp.Start();
        }

        public void CompareExcelNEQ()
        {
        	Validate.IsTrue(FileEquals(p3,p4), "Checking if DDM Mech BOM Extract Files(NEQ) are Equal.  The Validation @ValidateRESULT@.");
        }

    }
}