///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrainingSetup
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Excel_Macro recording.
    /// </summary>
    [TestModule("51c54a63-94f7-4573-b124-835aceab767f", ModuleType.Recording, 1)]
    public partial class Excel_Macro : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrainingSetupRepository repository.
        /// </summary>
        public static TrainingSetupRepository repo = TrainingSetupRepository.Instance;

        static Excel_Macro instance = new Excel_Macro();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Excel_Macro()
        {
            MacroPath = "\\\\ca01a9001\\pgmis\\Development\\ATSPLM PLM Test Files\\Cust property change Revisions2.xls";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Excel_Macro Instance
        {
            get { return instance; }
        }

#region Variables

        string _MacroPath;

        /// <summary>
        /// Gets or sets the value of variable MacroPath.
        /// </summary>
        [TestVariable("514d7e75-aa2b-4d06-9d88-ace0ea8129a2")]
        public string MacroPath
        {
            get { return _MacroPath; }
            set { _MacroPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\Microsoft Office\\Office14\\EXCEL.EXE' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\Microsoft Office\\Office14\\EXCEL.EXE", "", "C:\\Program Files (x86)\\Microsoft Office\\Office14", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.File' at Center.", repo.Excel.FileInfo, new RecordItemIndex(1));
            repo.Excel.File.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.Open' at Center.", repo.Excel.OpenInfo, new RecordItemIndex(2));
            repo.Excel.Open.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open1.File_Name' at Center.", repo.Open1.File_NameInfo, new RecordItemIndex(3));
            repo.Open1.File_Name.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$MacroPath' on item 'Open1.File_Name'.", repo.Open1.File_NameInfo, new RecordItemIndex(4));
            repo.Open1.File_Name.Element.SetAttributeValue("Text", MacroPath);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open1.ButtonOpen' at Center.", repo.Open1.ButtonOpenInfo, new RecordItemIndex(5));
            repo.Open1.ButtonOpen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.RUN_MACRO' at Center.", repo.Excel.RUN_MACROInfo, new RecordItemIndex(6));
            repo.Excel.RUN_MACRO.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(7));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.File' at Center.", repo.Excel.FileInfo, new RecordItemIndex(8));
            repo.Excel.File.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.Exit' at Center.", repo.Excel.ExitInfo, new RecordItemIndex(9));
            repo.Excel.Exit.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
