///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PLM_Mechanical_Deploy_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeepCopyAsNewItem recording.
    /// </summary>
    [TestModule("b8e1dbeb-9398-4440-a376-e785582038ff", ModuleType.Recording, 1)]
    public partial class DeepCopyAsNewItem : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PLM_Mechanical_Deploy_TestRepository repository.
        /// </summary>
        public static PLM_Mechanical_Deploy_TestRepository repo = PLM_Mechanical_Deploy_TestRepository.Instance;

        static DeepCopyAsNewItem instance = new DeepCopyAsNewItem();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeepCopyAsNewItem()
        {
            FinalVersion = "";
            ProjectNumber = "13563";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeepCopyAsNewItem Instance
        {
            get { return instance; }
        }

#region Variables

        string _FinalVersion;

        /// <summary>
        /// Gets or sets the value of variable FinalVersion.
        /// </summary>
        [TestVariable("8bb0d57d-70f7-448d-9660-9af190ae587c")]
        public string FinalVersion
        {
            get { return _FinalVersion; }
            set { _FinalVersion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ProjectNumber.
        /// </summary>
        [TestVariable("68504289-d31d-44f9-98b3-ffad8d65cb6e")]
        public string ProjectNumber
        {
            get { return repo.ProjectNumber; }
            set { repo.ProjectNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Deep copy as new item from navigation
            Report.Log(ReportLevel.Info, "Section", "Deep copy as new item from navigation", new RecordItemIndex(0));
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10m.", new RecordItemIndex(1));
            //Delay.Duration(600000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.NavigationPane.DoorsSpecific.TOP_LEVEL' at 101;12.", repo.PLMMainForm.MainSplitPane.NavigationPane.DoorsSpecific.TOP_LEVELInfo, new RecordItemIndex(2));
            repo.PLMMainForm.MainSplitPane.NavigationPane.DoorsSpecific.TOP_LEVEL.Click(System.Windows.Forms.MouseButtons.Right, "101;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.DeepCopy' at 81;8.", repo.eBom_Add_Item.DeepCopyInfo, new RecordItemIndex(3));
            repo.eBom_Add_Item.DeepCopy.Click("81;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeepCopy.DeepCopyAsNewItem' at 43;10.", repo.DeepCopy.DeepCopyAsNewItemInfo, new RecordItemIndex(4));
            repo.DeepCopy.DeepCopyAsNewItem.Click("43;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CADVersionCheck.ButtonOK' at 36;12.", repo.CADVersionCheck.ButtonOKInfo, new RecordItemIndex(5));
            repo.CADVersionCheck.ButtonOK.Click("36;12");
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'DeepCopy.ButtonYes' at 47;12.", repo.DeepCopy.ButtonYesInfo, new RecordItemIndex(6));
                repo.DeepCopy.ButtonYes.Click("47;12");
                Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5m to exist. Associated repository item: 'OpenItem.ButtonYes'", repo.OpenItem.ButtonYesInfo, new ActionTimeout(300000), new RecordItemIndex(7));
            repo.OpenItem.ButtonYesInfo.WaitForExists(300000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.OpenItem.Self, false, new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OpenItem.ButtonYes' at 57;13.", repo.OpenItem.ButtonYesInfo, new RecordItemIndex(9));
            repo.OpenItem.ButtonYes.Click("57;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PLMMainForm.LastMessage' and assigning its value to variable 'FinalVersion'.", repo.PLMMainForm.LastMessageInfo, new RecordItemIndex(10));
            FinalVersion = repo.PLMMainForm.LastMessage.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", FinalVersion, new RecordItemIndex(11));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
