///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using ATS.CodeLibrary.DataUtilities.SQL;
namespace DDM_Lite_Full_Test
{
    public partial class SetProjectMigrated
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SetProjMigrated()
        {
           try 
        	{
        		
        	 
        		var settings = ATS.CodeLibrary.Configuration.ConfigurationHelper.GetAllLocalSettingsDecrypted();
        		
        		var creds = new SqlCredentials(settings["server"], settings["database"], settings["username"], settings["password"]);
        		
        		string sqlStatement = "select is_migrated from ClosedProjects with (nolock) where legacy_number = 13600 ";
        		string newSql = "update ClosedProjects set is_migrated = 'TRUE' where legacy_number = 13600";
        		if (SqlHelper.ExecuteQuery(creds, sqlStatement).Tables[0].Rows[0][0].ToString() == "FALSE")
        		{
        			Report.Log(ReportLevel.Info,"Project 13600 is NOT Migrated...Locking Project Now...");
        			SqlHelper.ExecuteNonQuery(creds, newSql);
        			if (SqlHelper.ExecuteQuery(creds, sqlStatement).Tables[0].Rows[0][0].ToString() == "TRUE")
        			{
        				Report.Log(ReportLevel.Info,"Project 13600 is MIGRATED and LOCKED");
        			}
        		}
        		else if (SqlHelper.ExecuteQuery(creds, sqlStatement).Tables[0].Rows[0][0].ToString() == "TRUE")
        		{
        			Report.Log(ReportLevel.Info,"Project 13600 is already MIGRATED");
        		}
        		else
        		{
        			Report.Log(ReportLevel.Info,"Cannot get info about Project 13600");
        			
        		}

        	}
        	
        	catch (Exception ex)
        	{
        		
        		Report.Log(ReportLevel.Info,"Exception occurred: " + ex);
        	}
        }

    }
}
