///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Document_Processor_FilterTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Deploy_Test_Filter_Test recording.
    /// </summary>
    [TestModule("acec346c-2999-4d13-baba-218c6ff0dc4a", ModuleType.Recording, 1)]
    public partial class Deploy_Test_Filter_Test : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Deploy_Test_Filter_TestRepository repository.
        /// </summary>
        public static Deploy_Test_Filter_TestRepository repo = Deploy_Test_Filter_TestRepository.Instance;

        static Deploy_Test_Filter_Test instance = new Deploy_Test_Filter_Test();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Deploy_Test_Filter_Test()
        {
            FolderID = "256";
            FormTitle = "ATS Document Processor version 2.1.1.18734 Recipe - filter test 1204";
            ResultsFolder = "\\\\ca01a1900\\c$\\Test Results\\Filter Tests";
            ReferenceName = "references RecipeID = 1182.txt";
            NewTextName = "$NewTextName";
            RecipeIndex = "1";
            ReferenceFilesFolder = "\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS Document Processor\\Ranorex\\Download\\ReferenceFiles\\Test Case 3";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Deploy_Test_Filter_Test Instance
        {
            get { return instance; }
        }

#region Variables

        string _FormTitle;

        /// <summary>
        /// Gets or sets the value of variable FormTitle.
        /// </summary>
        [TestVariable("c0243a6c-cffd-451b-bde6-128278ab28d8")]
        public string FormTitle
        {
            get { return _FormTitle; }
            set { _FormTitle = value; }
        }

        string _ResultsFolder;

        /// <summary>
        /// Gets or sets the value of variable ResultsFolder.
        /// </summary>
        [TestVariable("5d8e4d72-f899-4963-88db-d68f88af37bd")]
        public string ResultsFolder
        {
            get { return _ResultsFolder; }
            set { _ResultsFolder = value; }
        }

        string _ReferenceName;

        /// <summary>
        /// Gets or sets the value of variable ReferenceName.
        /// </summary>
        [TestVariable("58403999-9520-4c7d-8c90-c460f48b8059")]
        public string ReferenceName
        {
            get { return _ReferenceName; }
            set { _ReferenceName = value; }
        }

        string _NewTextName;

        /// <summary>
        /// Gets or sets the value of variable NewTextName.
        /// </summary>
        [TestVariable("6b1bc715-6514-4e56-8d48-40dd0c4fe4f6")]
        public string NewTextName
        {
            get { return _NewTextName; }
            set { _NewTextName = value; }
        }

        string _ReferenceFilesFolder;

        /// <summary>
        /// Gets or sets the value of variable ReferenceFilesFolder.
        /// </summary>
        [TestVariable("ed25273a-fb92-4a20-9e59-92a1ea19e3fe")]
        public string ReferenceFilesFolder
        {
            get { return _ReferenceFilesFolder; }
            set { _ReferenceFilesFolder = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RecipeIndex.
        /// </summary>
        [TestVariable("3763b10c-92e0-4ca7-ab41-1eb0cfdfb6a5")]
        public string RecipeIndex
        {
            get { return repo.RecipeIndex; }
            set { repo.RecipeIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable FolderID.
        /// </summary>
        [TestVariable("18e7cd00-e59c-49c9-9e8e-89ee3061f71f")]
        public string FolderID
        {
            get { return repo.FolderID; }
            set { repo.FolderID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorMainWindow.Job_Tools_Tab' at 129;37.", repo.ATSDocumentProcessorMainWindow.Job_Tools_TabInfo, new RecordItemIndex(0));
            repo.ATSDocumentProcessorMainWindow.Job_Tools_Tab.Click("129;37");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorMainWindow.NewJobMenu1' at 28;30.", repo.ATSDocumentProcessorMainWindow.NewJobMenu1Info, new RecordItemIndex(1));
            repo.ATSDocumentProcessorMainWindow.NewJobMenu1.Click("28;30");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewJobMenu.NewJobGrid.ProjectNumberInput' at Center.", repo.NewJobMenu.NewJobGrid.ProjectNumberInputInfo, new RecordItemIndex(2));
            repo.NewJobMenu.NewJobGrid.ProjectNumberInput.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '99999' with focus on 'NewJobMenu.NewJobGrid.ProjectNumberInput'.", repo.NewJobMenu.NewJobGrid.ProjectNumberInputInfo, new RecordItemIndex(3));
            repo.NewJobMenu.NewJobGrid.ProjectNumberInput.PressKeys("99999");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewJobMenu.NewJobGrid.Load' at 16;18.", repo.NewJobMenu.NewJobGrid.LoadInfo, new RecordItemIndex(4));
            repo.NewJobMenu.NewJobGrid.Load.Click("16;18");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewJobMenu.NewJobGrid.SomeCheckBox' at 93;5.", repo.NewJobMenu.NewJobGrid.SomeCheckBoxInfo, new RecordItemIndex(5));
            repo.NewJobMenu.NewJobGrid.SomeCheckBox.Click("93;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessor1.FilterTest' at 53;6.", repo.ATSDocumentProcessor1.FilterTestInfo, new RecordItemIndex(6));
            repo.ATSDocumentProcessor1.FilterTest.Click("53;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewJobMenu.NewJobGrid.SomeCheckBox1' at 61;11.", repo.NewJobMenu.NewJobGrid.SomeCheckBox1Info, new RecordItemIndex(7));
            repo.NewJobMenu.NewJobGrid.SomeCheckBox1.Click("61;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessor1.SomeListItem' at 46;8.", repo.ATSDocumentProcessor1.SomeListItemInfo, new RecordItemIndex(8));
            repo.ATSDocumentProcessor1.SomeListItem.Click("46;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewJobMenu.NewJobGrid.SomeCheckBox2' at 57;9.", repo.NewJobMenu.NewJobGrid.SomeCheckBox2Info, new RecordItemIndex(9));
            repo.NewJobMenu.NewJobGrid.SomeCheckBox2.Click("57;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessor1.ListItem25243928XXXX001ADAMADAM' at 57;4.", repo.ATSDocumentProcessor1.ListItem25243928XXXX001ADAMADAMInfo, new RecordItemIndex(10));
            repo.ATSDocumentProcessor1.ListItem25243928XXXX001ADAMADAM.Click("57;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewJobMenu.SomeButton' at 124;18.", repo.NewJobMenu.SomeButtonInfo, new RecordItemIndex(11));
            repo.NewJobMenu.SomeButton.Click("124;18");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 8.3m for item 'ATSDocumentProcessorMainWindow.MainProgressBar' to not exist.", repo.ATSDocumentProcessorMainWindow.MainProgressBarInfo, new ActionTimeout(500000), new RecordItemIndex(12));
            repo.ATSDocumentProcessorMainWindow.MainProgressBarInfo.WaitForNotExists(500000);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'ATSDocumentProcessorMainWindow.ProjectLabel' and assigning its value to variable 'FolderID'.", repo.ATSDocumentProcessorMainWindow.ProjectLabelInfo, new RecordItemIndex(13));
            FolderID = repo.ATSDocumentProcessorMainWindow.ProjectLabel.Element.GetAttributeValueText("Text");
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'ATSDocumentProcessorMainWindow' and assigning its value to variable 'FormTitle'.", repo.ATSDocumentProcessorMainWindow.SelfInfo, new RecordItemIndex(14));
            FormTitle = repo.ATSDocumentProcessorMainWindow.Self.Element.GetAttributeValueText("Title");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorMainWindow.RunJob' at 8;2.", repo.ATSDocumentProcessorMainWindow.RunJobInfo, new RecordItemIndex(15));
            repo.ATSDocumentProcessorMainWindow.RunJob.Click("8;2");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectOutputFolder.PreviousLocations' at 7;12.", repo.SelectOutputFolder.PreviousLocationsInfo, new RecordItemIndex(16));
            repo.SelectOutputFolder.PreviousLocations.Click("7;12");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ResultsFolder'.", new RecordItemIndex(17));
            Keyboard.Press(ResultsFolder);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(18));
            Keyboard.Press("{Return}");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectOutputFolder.ButtonE44616AD6DF14B9485A4E465AE8A1' at 46;11.", repo.SelectOutputFolder.ButtonE44616AD6DF14B9485A4E465AE8A1Info, new RecordItemIndex(19));
            repo.SelectOutputFolder.ButtonE44616AD6DF14B9485A4E465AE8A1.Click("46;11");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FolderID'.", new RecordItemIndex(20));
            Keyboard.Press(FolderID);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(21));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}{Return}'.", new RecordItemIndex(22));
            Keyboard.Press("{Return}{Return}");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectOutputFolder.SelectFolder' at 7;15.", repo.SelectOutputFolder.SelectFolderInfo, new RecordItemIndex(23));
            repo.SelectOutputFolder.SelectFolder.Click("7;15");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10.3m for item 'ATSDocumentProcessorMainWindow.MainProgressBar' to not exist.", repo.ATSDocumentProcessorMainWindow.MainProgressBarInfo, new ActionTimeout(619998), new RecordItemIndex(24));
            repo.ATSDocumentProcessorMainWindow.MainProgressBarInfo.WaitForNotExists(619998);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ATSDocumentProcessorMainWindow.Self, false, new RecordItemIndex(25));
            
            ConcatenateStrings("", "", "");
            
            CompareTextFiles("\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS Document Processor\\Ranorex\\Download", FolderID, FormTitle, ReferenceFilesFolder, ReferenceName);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
