///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;
using Microsoft.Office.Interop.Excel;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ATS_BTP_TESTING
{
	public partial class Load_Invalid_File : Load_Valid_File
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void PrepareInValidFile()
        {
        	try 
        	{
        		string originalPathofInvalidFile = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\BTP_Test\test_files_BTP\ATSBTP4-1.xlsm";
	            string pathofInvalidFile = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\BTP_Test\test_files_BTP - Copy\ATSBTP4-1.xlsm";
	            string pathofIndexfile = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\BTP_Test\index.txt";
	            string adamsIndexFile = @"\\ca01a9001\pgmis\Deployment_DEV\ATSPLM PLM Test Files\Generate Test Assembly\Test Files\Doors-SW2018\Index.txt";
	            File.Copy(adamsIndexFile, pathofIndexfile, true);
	            if (!File.Exists(pathofIndexfile))
		            {
		            	throw new Exception("Error! File: " + pathofIndexfile + " does not exist!");
		            }
	            string curBTPIndex = "-" + File.ReadAllText(pathofIndexfile);
	            File.Copy(originalPathofInvalidFile, pathofInvalidFile, true);

	           string subBTPindex = curBTPIndex.Replace("-","");
	            int btpin = Convert.ToInt32(subBTPindex);
	            btpin--;
	            string convertedBTP = "-" + btpin.ToString("D4");
	            Report.Log(ReportLevel.Info, "Current BTP index is: " + curBTPIndex);
	            UpdateExcelRange(pathofInvalidFile, "-0095", "Input Sheet", curBTPIndex, true);
	            //UpdateExcelRange(pathofInvalidFile, "-0094", "Input Sheet", convertedBTP); //this is for one number less
	            UpdateExcelRange(pathofInvalidFile, "-0094", "Input Sheet", curBTPIndex, true);
	            varBTPInvalidFile = pathofInvalidFile;
        	} 
        	catch (Exception Ex) 
        	{
        		Report.Log(ReportLevel.Error, "Exception: " + Ex.Message);
        	}
        	

        }

        public void MatchIndex()
        {
            string originalCompareFilePath = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\BTP_Test\ExcelCompare\Original\original.txt";
            string newCompareFilePath = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\BTP_Test\ExcelCompare\Compare\compare.txt";
            string currentCompareFilePath = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\BTP_Test\ExcelCompare\Current\current.txt";
            string pathofIndexfile = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\BTP_Test\index.txt";
	            if (!File.Exists(pathofIndexfile))
		            {
		            	throw new Exception("Error! File: " + pathofIndexfile + " does not exist!");
		            }
	        string curBTPIndex = "-" + File.ReadAllText(pathofIndexfile);
	        File.Copy(originalCompareFilePath, newCompareFilePath, true);
	        BTPUserCodeCollection.FindandReplaceForTextFiles(newCompareFilePath, "-99999", curBTPIndex);
	        bool filesEqual = BTPUserCodeCollection.FileCompare(currentCompareFilePath, newCompareFilePath);
	        Ranorex.Validate.IsTrue(filesEqual, "Checking if the files are equal.  The Validation @ValidateRESULT@.");
            
        }

 
    }
}