///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GlobalServicesPlatformTesting
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Quotes recording.
    /// </summary>
    [TestModule("99cdfb9e-064b-490a-90c8-72059f5a8f53", ModuleType.Recording, 1)]
    public partial class Quotes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GlobalServicesPlatformTestingRepository repository.
        /// </summary>
        public static GlobalServicesPlatformTestingRepository repo = GlobalServicesPlatformTestingRepository.Instance;

        static Quotes instance = new Quotes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Quotes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Quotes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSStoreLogin.ATSLogo' at Center.", repo.ATSStoreLogin.ATSLogoInfo, new RecordItemIndex(0));
            repo.ATSStoreLogin.ATSLogo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'State' to equal the specified value 'complete'. Associated repository item: 'ATSStoreLogin'", repo.ATSStoreLogin.SelfInfo, new RecordItemIndex(1));
            repo.ATSStoreLogin.SelfInfo.WaitForAttributeEqual(30000, "State", "complete");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSStoreLogin.MyAccount' at Center.", repo.ATSStoreLogin.MyAccountInfo, new RecordItemIndex(3));
            repo.ATSStoreLogin.MyAccount.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSStoreLogin.Quotes' at Center.", repo.ATSStoreLogin.QuotesInfo, new RecordItemIndex(4));
            repo.ATSStoreLogin.Quotes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Quotes History') on item 'ATSStoreLogin.CCOrderHistoryTitle'.", repo.ATSStoreLogin.CCOrderHistoryTitleInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ATSStoreLogin.CCOrderHistoryTitleInfo, "InnerText", "Quotes History");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ATSStoreLogin.Self, false, new RecordItemIndex(6));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
