///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace OauthDanceSharepoint.Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UpdateRuntimes recording.
    /// </summary>
    [TestModule("d615c379-4fe4-4253-a3ec-19178f3612b8", ModuleType.Recording, 1)]
    public partial class UpdateRuntime : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::OauthDanceSharepoint.OauthDanceSharepointRepository repository.
        /// </summary>
        public static global::OauthDanceSharepoint.OauthDanceSharepointRepository repo = global::OauthDanceSharepoint.OauthDanceSharepointRepository.Instance;

        static UpdateRuntime instance = new UpdateRuntime();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UpdateRuntime()
        {
            varEnvID = "dev";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UpdateRuntime Instance
        {
            get { return instance; }
        }

#region Variables

        string _varEnvID;

        /// <summary>
        /// Gets or sets the value of variable varEnvID.
        /// </summary>
        [TestVariable("3cd73e22-c30e-4ffc-9afd-b386a1638a7d")]
        public string varEnvID
        {
            get { return _varEnvID; }
            set { _varEnvID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollectionSPProject.UpdateRuntime(varEnvID);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
