///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddExportFormatsOPG recording.
    /// </summary>
    [TestModule("a11326fb-550f-44ed-9ab9-781a3a314f6d", ModuleType.Recording, 1)]
    public partial class AddExportFormatsOPG : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static ATS_Document_ProcessorRepository repo = ATS_Document_ProcessorRepository.Instance;

        static AddExportFormatsOPG instance = new AddExportFormatsOPG();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddExportFormatsOPG()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddExportFormatsOPG Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperations' at 15;38.", repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperationsInfo, new RecordItemIndex(0));
            repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperations.Click("15;38");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.AddOperations.AddExportFormats' at 14;25.", repo.SomeContextMenu.AddOperations.AddExportFormatsInfo, new RecordItemIndex(1));
            repo.SomeContextMenu.AddOperations.AddExportFormats.Click("14;25");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExportFormats.CheckMark' at 4;8.", repo.ExportFormats.CheckMarkInfo, new RecordItemIndex(2));
            repo.ExportFormats.CheckMark.Click("4;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExportFormats.TextPDF' at 7;6.", repo.ExportFormats.TextPDFInfo, new RecordItemIndex(3));
            repo.ExportFormats.TextPDF.Click("7;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExportFormats.Okay' at 34;20.", repo.ExportFormats.OkayInfo, new RecordItemIndex(4));
            repo.ExportFormats.Okay.Click("34;20");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
