///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PLM_Mechanical_Deploy_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetRefOnlyFalse recording.
    /// </summary>
    [TestModule("9cfeed2a-5a29-40fb-99ba-dc224b9af05c", ModuleType.Recording, 1)]
    public partial class SetRefOnlyFalse : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PLM_Mechanical_Deploy_TestRepository repository.
        /// </summary>
        public static PLM_Mechanical_Deploy_TestRepository repo = PLM_Mechanical_Deploy_TestRepository.Instance;

        static SetRefOnlyFalse instance = new SetRefOnlyFalse();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetRefOnlyFalse()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetRefOnlyFalse Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ProjectNumber.
        /// </summary>
        [TestVariable("68504289-d31d-44f9-98b3-ffad8d65cb6e")]
        public string ProjectNumber
        {
            get { return repo.ProjectNumber; }
            set { repo.ProjectNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable EndItemNumber.
        /// </summary>
        [TestVariable("7590d2be-bcac-4524-beae-fdd272640edb")]
        public string EndItemNumber
        {
            get { return repo.EndItemNumber; }
            set { repo.EndItemNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Set Ref Only False
            Report.Log(ReportLevel.Info, "Section", "Set Ref Only False", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right DoubleClick item 'PLMMainForm.MainSplitPane.NavigationPane.TreeItemEndItemNumber' at 196;6.", repo.PLMMainForm.MainSplitPane.NavigationPane.TreeItemEndItemNumberInfo, new RecordItemIndex(2));
            repo.PLMMainForm.MainSplitPane.NavigationPane.TreeItemEndItemNumber.DoubleClick(System.Windows.Forms.MouseButtons.Right, "196;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.TabItemEngineering' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.TabItemEngineeringInfo, new RecordItemIndex(3));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.TabItemEngineering.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevelInfo, new RecordItemIndex(4));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellTopLevel.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.ViewEdit' at 48;7.", repo.eBom_Add_Item.ViewEditInfo, new RecordItemIndex(5));
            repo.eBom_Add_Item.ViewEdit.Click("48;7");
            Delay.Milliseconds(200);
            
            try {
                //Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'Java2.RefreshFullEBOM' at Center.", repo.Java2.RefreshFullEBOMInfo, new RecordItemIndex(6));
                //repo.Java2.RefreshFullEBOM.Click();
                //Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            CheckButtonRefreshExists();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.ExpandGeneralAssembly' at 22;10.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.ExpandGeneralAssemblyInfo, new RecordItemIndex(8));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.ExpandGeneralAssembly.Click("22;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEdit' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEditInfo, new RecordItemIndex(9));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEdit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEditNotActive'", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEditNotActiveInfo, new ActionTimeout(30000), new RecordItemIndex(10));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEditNotActiveInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.CellSpare' at 15;11.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellSpareInfo, new RecordItemIndex(11));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.CellSpare.Click(System.Windows.Forms.MouseButtons.Right, "15;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.SetAllToFALSE' at 100;16.", repo.eBom_Add_Item.SetAllToFALSEInfo, new RecordItemIndex(12));
            repo.eBom_Add_Item.SetAllToFALSE.Click("100;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Engineering.eBomSave' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBomSaveInfo, new RecordItemIndex(13));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBomSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to exist. Associated repository item: 'PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEditActive'", repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEditActiveInfo, new ActionTimeout(120000), new RecordItemIndex(14));
            repo.PLMMainForm.MainSplitPane.ItemPane.Engineering.eBOMEditActiveInfo.WaitForExists(120000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(15));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
