///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PLMTest
{
    public partial class CheckOutAndCheckInZW1 : PLMTest.CreateAndValidateElectricalPackage
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
            varPackageName = PackageItemNumber;
            //varPackageName = "25246801";
           
        }

        public void checkinzw1()
        {
        	//string dt = "JUN-2-14-02";
//        	string dirName = @"C:\home\PLM_Deploy_Test\" + dt;
//        	string destinationFileMOD = dirName + "\\" + "13563_" + dt + "-MOD.xml";
//        	string checkOutFolder = @"C:\home\ATS\REFERENCE FOR TESTING\13563";
//        	string destinationFileName = checkOutFolder + "\\" + "13563_" + dt + ".xml";
//        	string destinationFilePDF = dirName + "\\" + "13563_" + dt + ".pdf";
//        	string destinationFilePDFName = checkOutFolder + "\\" + "13563_" + dt + ".pdf";
//        	string destinationFileZW1 = dirName + "\\" + "13563_" + dt + ".zw1";
//        	string destinationFileZw1Name = checkOutFolder + "\\" + "13563_" + dt + ".zw1";
        	string dirName = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\Elec_Deploy_Test\home\" + dt;
        	string destinationFileMOD = dirName + "\\" + varProjName.Substring(0,5) + "_" + dt + "-MOD.xml";
        	string checkOutFolder = @"C:\home\ATS\REFERENCE FOR TESTING\" + varProjName.Substring(0,5);
        	string destinationFileName = checkOutFolder + "\\" + varProjName.Substring(0,5) + "_" + dt + ".xml";
        	string destinationFilePDF = dirName + "\\" + varProjName.Substring(0,5) + "_" + dt + ".pdf";
        	string destinationFilePDFName = checkOutFolder + "\\" + varProjName.Substring(0,5) + "_" + dt + ".pdf";
        	string destinationFileZW1 = dirName + "\\" + varProjName.Substring(0,5) + "_" + dt + ".zw1";
        	string destinationFileZw1Name = checkOutFolder + "\\" + varProjName.Substring(0,5) + "_" + dt + ".zw1";
        	string line = "";
      //  	File.Copy(destinationFileMOD, destinationFileName, true);
        	File.Copy(destinationFilePDF, destinationFilePDFName, true);
        	File.Copy(destinationFileZW1, destinationFileZw1Name, true);
        	
        	StreamReader myReader = new StreamReader(destinationFileMOD);
            StreamWriter myWriter = new StreamWriter(destinationFileName);
            
            while (line != null)
            {
            	while ((line = myReader.ReadLine()) != null)
            	{
            		if (line.Contains("Project Name"))
            		{
            			line = line.Replace("13563", varProjName.Substring(0,5));
            			myWriter.WriteLine(line);
            		}
            		
            		else if (line.Contains("Package Name"))
            		    {
            		    	line = line.Replace("C06", dt);
            		    	myWriter.WriteLine(line);
            		    }
            	
            		 else
            		    {
            		    	myWriter.WriteLine(line);
            		    }
            		    
            	}
            	myReader.Close();
            	myWriter.Close();
            	
           	}
        	
        }

    }
}