///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.ValidationRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateArchivedRecipe recording.
    /// </summary>
    [TestModule("d858f766-9c54-4f81-b7db-d2f1ab938d05", ModuleType.Recording, 1)]
    public partial class ValidateArchivedRecipe : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static ValidateArchivedRecipe instance = new ValidateArchivedRecipe();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateArchivedRecipe()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateArchivedRecipe Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable RecipeName.
        /// </summary>
        [TestVariable("c38db75e-289a-4f3d-8063-06222dc8a742")]
        public string RecipeName
        {
            get { return repo.RecipeName; }
            set { repo.RecipeName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RecipeID.
        /// </summary>
        [TestVariable("377f7ac9-b542-4231-9c0d-e88d063c7606")]
        public string RecipeID
        {
            get { return repo.RecipeID; }
            set { repo.RecipeID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.RecipeToolsTab' at Center.", repo.ATSDocumentProcessorForm.Ribbon.RecipeToolsTabInfo, new RecordItemIndex(0));
            repo.ATSDocumentProcessorForm.Ribbon.RecipeToolsTab.Click("Center");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.RecipeTools.Main.OpenRecipeMenu' at Center.", repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Main.OpenRecipeMenuInfo, new RecordItemIndex(1));
            repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Main.OpenRecipeMenu.Click("Center");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.OpenControls.RecipeOpenNames' at Center.", repo.SomeContextMenu.OpenControls.RecipeOpenNamesInfo, new RecordItemIndex(2));
            repo.SomeContextMenu.OpenControls.RecipeOpenNames.Click("Center");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.RecipeName' at Center.", repo.SomeContextMenu.RecipeNameInfo, new RecordItemIndex(3));
            repo.SomeContextMenu.RecipeName.Click("Center");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.OpenControls.RecipeOpenVersions' at Center.", repo.SomeContextMenu.OpenControls.RecipeOpenVersionsInfo, new RecordItemIndex(4));
            repo.SomeContextMenu.OpenControls.RecipeOpenVersions.Click("Center");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'ATSDocumentProcessor2.RecipeIDMenuItem'.", repo.ATSDocumentProcessor2.RecipeIDMenuItemInfo, new RecordItemIndex(5));
            Validate.NotExists(repo.ATSDocumentProcessor2.RecipeIDMenuItemInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
