///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_BTP_TESTING
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validate_Export_Menu recording.
    /// </summary>
    [TestModule("a98c4dcf-ad9e-4fb8-a5f9-83a67f9f624e", ModuleType.Recording, 1)]
    public partial class Validate_Export_Menu : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_BTP_TESTINGRepository repository.
        /// </summary>
        public static ATS_BTP_TESTINGRepository repo = ATS_BTP_TESTINGRepository.Instance;

        static Validate_Export_Menu instance = new Validate_Export_Menu();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validate_Export_Menu()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validate_Export_Menu Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSBuildToPrintPLMImporterMAIN.Export' at Center.", repo.ATSBuildToPrintPLMImporterMAIN.ExportInfo, new RecordItemIndex(0));
            repo.ATSBuildToPrintPLMImporterMAIN.Export.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSBuildToPrintPLMImporter.ExportErrorsToExcel' at 50;6.", repo.ATSBuildToPrintPLMImporter.ExportErrorsToExcelInfo, new RecordItemIndex(1));
            repo.ATSBuildToPrintPLMImporter.ExportErrorsToExcel.Click("50;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'Explorer.MicrosoftExcelBook1'.", repo.Explorer.MicrosoftExcelBook1Info, new RecordItemIndex(2));
            repo.Explorer.MicrosoftExcelBook1.Press();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MicrosoftExcelBook1'.", repo.MicrosoftExcelBook1.SelfInfo, new RecordItemIndex(3));
            repo.MicrosoftExcelBook1.Self.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='index') on item 'MicrosoftExcelBook1.CellA1'.", repo.MicrosoftExcelBook1.CellA1Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.MicrosoftExcelBook1.CellA1Info, "Text", "index");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftExcelBook1.Close' at CenterRight.", repo.MicrosoftExcelBook1.CloseInfo, new RecordItemIndex(5));
            repo.MicrosoftExcelBook1.Close.Click(Location.CenterRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Copy_of_MicrosoftExcelBook1.DontSave' at Center.", repo.Copy_of_MicrosoftExcelBook1.DontSaveInfo, new RecordItemIndex(6));
            repo.Copy_of_MicrosoftExcelBook1.DontSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSBuildToPrintPLMImporterMAIN.Export' at Center.", repo.ATSBuildToPrintPLMImporterMAIN.ExportInfo, new RecordItemIndex(7));
            repo.ATSBuildToPrintPLMImporterMAIN.Export.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSBuildToPrintPLMImporter.ExportPLMWorxEBOMCompare' at Center.", repo.ATSBuildToPrintPLMImporter.ExportPLMWorxEBOMCompareInfo, new RecordItemIndex(8));
            repo.ATSBuildToPrintPLMImporter.ExportPLMWorxEBOMCompare.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PLMWorxEBOMCompareExport'.", repo.PLMWorxEBOMCompareExport.SelfInfo, new RecordItemIndex(9));
            Validate.Exists(repo.PLMWorxEBOMCompareExport.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMWorxEBOMCompareExport.Close' at Center.", repo.PLMWorxEBOMCompareExport.CloseInfo, new RecordItemIndex(10));
            repo.PLMWorxEBOMCompareExport.Close.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSBuildToPrintPLMImporter2.ButtonOK' at Center.", repo.ATSBuildToPrintPLMImporter2.ButtonOKInfo, new RecordItemIndex(11));
            repo.ATSBuildToPrintPLMImporter2.ButtonOK.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSBuildToPrintPLMImporterMAIN.Export' at Center.", repo.ATSBuildToPrintPLMImporterMAIN.ExportInfo, new RecordItemIndex(12));
            repo.ATSBuildToPrintPLMImporterMAIN.Export.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSBuildToPrintPLMImporter.ExportExistingInfoToExcel' at Center.", repo.ATSBuildToPrintPLMImporter.ExportExistingInfoToExcelInfo, new RecordItemIndex(13));
            repo.ATSBuildToPrintPLMImporter.ExportExistingInfoToExcel.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'Explorer.MicrosoftExcelBook1'.", repo.Explorer.MicrosoftExcelBook1Info, new RecordItemIndex(14));
            repo.Explorer.MicrosoftExcelBook1.Press();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MicrosoftExcelBook1'.", repo.MicrosoftExcelBook1.SelfInfo, new RecordItemIndex(15));
            repo.MicrosoftExcelBook1.Self.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Info') on item 'MicrosoftExcelBook1.CellA1'.", repo.MicrosoftExcelBook1.CellA1Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.MicrosoftExcelBook1.CellA1Info, "Text", "Info");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftExcelBook1.Close' at CenterRight.", repo.MicrosoftExcelBook1.CloseInfo, new RecordItemIndex(17));
            repo.MicrosoftExcelBook1.Close.Click(Location.CenterRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Copy_of_MicrosoftExcelBook1.DontSave' at Center.", repo.Copy_of_MicrosoftExcelBook1.DontSaveInfo, new RecordItemIndex(18));
            repo.Copy_of_MicrosoftExcelBook1.DontSave.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
