///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PLMTest
{
	public partial class PrepareFileNamesandImport : PLMTest.CreateAndValidateElectricalPackage
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        /// 
        
       
        
        //string dt = "MAY-30-2-00";
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void PrepareFileNamesForImport()
        {
        	
        	varPackageName = PackageItemNumber;
        	string dirName = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\Elec_Deploy_Test\home\" + dt;
//        	string originalFileXML = @"C:\home\PLM_Deploy_Test\cell6\13563_C06.xml";
//        	string originalFileMOD = @"C:\home\PLM_Deploy_Test\cell6\13563_C06 - Mod.xml";
//        	string originalFilePDF = @"C:\home\PLM_Deploy_Test\cell6\13563_C06.pdf";
//        	string originalFileZW1 = @"C:\home\PLM_Deploy_Test\cell6\13563_C06.zw1";
			string originalFileXML = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\Elec_Deploy_Test\cell6\13563_C06.xml";
        	string originalFileMOD = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\Elec_Deploy_Test\cell6\13563_C06 - Mod.xml";
        	string originalFilePDF = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\Elec_Deploy_Test\cell6\13563_C06.pdf";
        	string originalFileZW1 = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\Elec_Deploy_Test\cell6\13563_C06.zw1";
        	string destinationFileXML = dirName + "\\" + varProjName.Substring(0,5) + "_" + dt + ".xml";
        	string destinationFileMOD = dirName + "\\" + varProjName.Substring(0,5) + "_" + dt + "-MOD.xml";
        	string destinationFilePDF = dirName + "\\" + varProjName.Substring(0,5) + "_" + dt + ".pdf";
        	string destinationFileZW1 = dirName + "\\" + varProjName.Substring(0,5) + "_" + dt + ".zw1";
        	string line = "";
        	varDestinationZW1 = destinationFileZW1;
        	Directory.CreateDirectory(dirName);
        	File.Copy(originalFileMOD, destinationFileMOD, true);
        	File.Copy(originalFilePDF, destinationFilePDF, true);
        	File.Copy(originalFileZW1, destinationFileZW1, true);
        	
        	StreamReader myReader = new StreamReader(originalFileXML);
            StreamWriter myWriter = new StreamWriter(destinationFileXML);
            
            while (line != null)
            {
            	while ((line = myReader.ReadLine()) != null)
            	{
            		if (line.Contains("Project Name"))
            		{
            			line = line.Replace("13563", varProjName.Substring(0,5));
            			myWriter.WriteLine(line);
            		}
            		
            		else if (line.Contains("Package Name"))
            		    {
            		    	line = line.Replace("C06", dt);
            		    	myWriter.WriteLine(line);
            		    }
            		    	
            		    
            		else if (line.Contains("2090-SCEP3-0"))
            		             {
            		             	line = line.Replace("2090-SCEP3-0", dt);
            		             	myWriter.WriteLine(line);
            		             }
            		else if (line.Contains("S45PATCH25B"))
            		             {
            		             	line = line.Replace("S45PATCH25B", dt);
            		             	myWriter.WriteLine(line);
            		             }
            		else if (line.Contains("F6T5"))
            		             {
            		             	line = line.Replace("F6T5", dt);
            		             	myWriter.WriteLine(line);
            		             } 
            		    else
            		    {
            		    	myWriter.WriteLine(line);
            		    }
            		    
            	}
            	myReader.Close();
            	myWriter.Close();
            	
            	}
            
            }


        public void updateElecImportTime()
        {
			varImportTime = GetTiming.ActionTime;
        }
            
                  
        	
        }

    }