///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.EditRecipe.AddOperations.DeleteCustomProperties
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddDeleteCustomProperties recording.
    /// </summary>
    [TestModule("aa8deda4-a7a6-47de-8564-8c31cfa91876", ModuleType.Recording, 1)]
    public partial class AddDeleteCustomProperties : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static AddDeleteCustomProperties instance = new AddDeleteCustomProperties();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddDeleteCustomProperties()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddDeleteCustomProperties Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperations' at 35;45.", repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperationsInfo, new RecordItemIndex(0));
            repo.ATSDocumentProcessorForm.Ribbon.RecipeTools.Operations.AddOperations.Click("35;45");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.AddOperations.AddDeleteCustomProperties' at 98;20.", repo.SomeContextMenu.AddOperations.AddDeleteCustomPropertiesInfo, new RecordItemIndex(1));
            repo.SomeContextMenu.AddOperations.AddDeleteCustomProperties.Click("98;20");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeleteCustomProperties.Options.OnlyKeepProperties' at 15;3.", repo.DeleteCustomProperties.Options.OnlyKeepPropertiesInfo, new RecordItemIndex(2));
            repo.DeleteCustomProperties.Options.OnlyKeepProperties.Click("15;3");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeleteCustomProperties.AddProperty' at 39;30.", repo.DeleteCustomProperties.AddPropertyInfo, new RecordItemIndex(3));
            repo.DeleteCustomProperties.AddProperty.Click("39;30");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeleteCustomProperties.PropertyName' at 81;12.", repo.DeleteCustomProperties.PropertyNameInfo, new RecordItemIndex(4));
            repo.DeleteCustomProperties.PropertyName.Click("81;12");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'PLM_ItemNumber'.", new RecordItemIndex(5));
            Keyboard.Press("PLM_ItemNumber");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeleteCustomProperties.ButtonAdd' at 8;16.", repo.DeleteCustomProperties.ButtonAddInfo, new RecordItemIndex(6));
            repo.DeleteCustomProperties.ButtonAdd.Click("8;16");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeleteCustomProperties.Okay' at 85;28.", repo.DeleteCustomProperties.OkayInfo, new RecordItemIndex(7));
            repo.DeleteCustomProperties.Okay.Click("85;28");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
