///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpchainMechDeployTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsertAssemblyinSW recording.
    /// </summary>
    [TestModule("cf15cc40-644a-40dd-9345-5aa59f0bfc1e", ModuleType.Recording, 1)]
    public partial class InsertAssemblyinSW : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpchainMechDeployTestRepository repository.
        /// </summary>
        public static UpchainMechDeployTestRepository repo = UpchainMechDeployTestRepository.Instance;

        static InsertAssemblyinSW instance = new InsertAssemblyinSW();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsertAssemblyinSW()
        {
            assemblyFolderName = "none";
            assemblyFileName = "none";
            fullPathAssemblyName = "none";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsertAssemblyinSW Instance
        {
            get { return instance; }
        }

#region Variables

        string _assemblyFolderName;

        /// <summary>
        /// Gets or sets the value of variable assemblyFolderName.
        /// </summary>
        [TestVariable("105e4173-76da-4444-8148-7a7b1a31a2e0")]
        public string assemblyFolderName
        {
            get { return _assemblyFolderName; }
            set { _assemblyFolderName = value; }
        }

        string _assemblyFileName;

        /// <summary>
        /// Gets or sets the value of variable assemblyFileName.
        /// </summary>
        [TestVariable("b7b39aeb-1338-4616-b482-40f3cdc2300d")]
        public string assemblyFileName
        {
            get { return _assemblyFileName; }
            set { _assemblyFileName = value; }
        }

        string _fullPathAssemblyName;

        /// <summary>
        /// Gets or sets the value of variable fullPathAssemblyName.
        /// </summary>
        [TestVariable("24d82264-cebf-46dc-b16f-51264eaa4b2d")]
        public string fullPathAssemblyName
        {
            get { return _fullPathAssemblyName; }
            set { _fullPathAssemblyName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'SOLIDWORKS'.", repo.SOLIDWORKS.SelfInfo, new RecordItemIndex(0));
            repo.SOLIDWORKS.Self.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS' at Center.", repo.SOLIDWORKS.SelfInfo, new RecordItemIndex(1));
            repo.SOLIDWORKS.Self.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.Insert' at Center.", repo.SOLIDWORKS.InsertInfo, new RecordItemIndex(2));
            //repo.SOLIDWORKS.Insert.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu down}{Ikey}{LMenu up}'.", new RecordItemIndex(3));
            Keyboard.Press("{LMenu down}{Ikey}{LMenu up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SLDWORKS.Component' at Center.", repo.SLDWORKS.ComponentInfo, new RecordItemIndex(4));
            repo.SLDWORKS.Component.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SLDWORKS.ExistingPartAssembly' at Center.", repo.SLDWORKS.ExistingPartAssemblyInfo, new RecordItemIndex(5));
            repo.SLDWORKS.ExistingPartAssembly.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.ButtonBrowse' at Center.", repo.SOLIDWORKS.ButtonBrowseInfo, new RecordItemIndex(6));
            //repo.SOLIDWORKS.ButtonBrowse.Click();
            //Delay.Milliseconds(200);
            
            FullPathofAssembly();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$fullPathAssemblyName' on item 'Open.FileName'.", repo.Open.FileNameInfo, new RecordItemIndex(8));
            repo.Open.FileName.Element.SetAttributeValue("Text", fullPathAssemblyName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.Open' at Center.", repo.Open.OpenInfo, new RecordItemIndex(9));
            repo.Open.Open.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(10));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKS.SWX_AREA' at Center.", repo.SOLIDWORKS.SWX_AREAInfo, new RecordItemIndex(11));
            repo.SOLIDWORKS.SWX_AREA.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(12));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Skey}{LControlKey up}' with focus on 'SOLIDWORKS.SWX_New'.", repo.SOLIDWORKS.SWX_NewInfo, new RecordItemIndex(13));
            repo.SOLIDWORKS.SWX_New.PressKeys("{LControlKey down}{Skey}{LControlKey up}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
