///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.Diagnostics;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PLM_Mechanical_Deploy_Test
{
    public partial class Excel_Macro
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void DeleteFiles()
        {
        	string dirPath = @"C:\home\test_files";
        	if(Directory.Exists(dirPath))
        	{
        		var files = Directory.EnumerateFiles(dirPath);
        		foreach (var file in files) {
        			File.SetAttributes(file, FileAttributes.Normal);
        			File.Delete(file);
        		}        		
        	}
        	else
        	{
        		Directory.CreateDirectory(dirPath);
        	}
        }

        public void KillProcess(string ProcessName)
        {
        	Thread.Sleep(1000);
        	foreach (var process in Process.GetProcessesByName(ProcessName))
			{
        		try {
			    	process.Kill();        				
        		} catch (Exception ex) {
        			Report.Log(ReportLevel.Info, ex.Message);
        		}
			}
        }


    }
}