///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PLM_Mechanical_Deploy_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetAttributesAssembly recording.
    /// </summary>
    [TestModule("6d40d7d7-0605-426a-8db9-f2272fee2097", ModuleType.Recording, 1)]
    public partial class SetAttributesAssembly : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PLM_Mechanical_Deploy_TestRepository repository.
        /// </summary>
        public static PLM_Mechanical_Deploy_TestRepository repo = PLM_Mechanical_Deploy_TestRepository.Instance;

        static SetAttributesAssembly instance = new SetAttributesAssembly();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetAttributesAssembly()
        {
            ItemName2 = "SUB - RAIL";
            assemblyItemNumber = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetAttributesAssembly Instance
        {
            get { return instance; }
        }

#region Variables

        string _assemblyItemNumber;

        /// <summary>
        /// Gets or sets the value of variable assemblyItemNumber.
        /// </summary>
        [TestVariable("52b839a8-f2c2-49ed-9ba1-c8ead5c1d171")]
        public string assemblyItemNumber
        {
            get { return _assemblyItemNumber; }
            set { _assemblyItemNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ProjectNumber.
        /// </summary>
        [TestVariable("68504289-d31d-44f9-98b3-ffad8d65cb6e")]
        public string ProjectNumber
        {
            get { return repo.ProjectNumber; }
            set { repo.ProjectNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ItemName2.
        /// </summary>
        [TestVariable("3ddf2ce4-5ebd-4a35-a995-d39fcf2eb609")]
        public string ItemName2
        {
            get { return repo.ItemName2; }
            set { repo.ItemName2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Set attributes for assemblies
            Report.Log(ReportLevel.Info, "Section", "Set attributes for assemblies", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PLMMainForm.MainSplitPane.NavigationPane.ItemsGeneral.Assembly' at Center.", repo.PLMMainForm.MainSplitPane.NavigationPane.ItemsGeneral.AssemblyInfo, new RecordItemIndex(1));
            repo.PLMMainForm.MainSplitPane.NavigationPane.ItemsGeneral.Assembly.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Edit' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.EditInfo, new RecordItemIndex(2));
            repo.PLMMainForm.MainSplitPane.ItemPane.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShape' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShapeInfo, new RecordItemIndex(3));
            repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShape.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'as' with focus on 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShape'.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShapeInfo, new RecordItemIndex(4));
            repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShape.PressKeys("as");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.Assembly' at Center.", repo.eBom_Add_Item.AssemblyInfo, new RecordItemIndex(5));
            repo.eBom_Add_Item.Assembly.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboMaterial' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboMaterialInfo, new RecordItemIndex(6));
            repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboMaterial.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.ASSEMBLY1' at Center.", repo.eBom_Add_Item.ASSEMBLY1Info, new RecordItemIndex(7));
            repo.eBom_Add_Item.ASSEMBLY1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboFinish2' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboFinish2Info, new RecordItemIndex(8));
            repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboFinish2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.NONE' at Center.", repo.eBom_Add_Item.NONEInfo, new RecordItemIndex(9));
            repo.eBom_Add_Item.NONE.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboHeatTreat2' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboHeatTreat2Info, new RecordItemIndex(10));
            repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboHeatTreat2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'eBom_Add_Item.NONE' at Center.", repo.eBom_Add_Item.NONEInfo, new RecordItemIndex(11));
            repo.eBom_Add_Item.NONE.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.TxtCost' at Center.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.TxtCostInfo, new RecordItemIndex(12));
            repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.TxtCost.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '15.0' with focus on 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.TxtCost'.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.TxtCostInfo, new RecordItemIndex(13));
            repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.TxtCost.PressKeys("15.0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShapeVal'.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShapeValInfo, new RecordItemIndex(14));
            Validate.Exists(repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboShapeValInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboMaterialVal'.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboMaterialValInfo, new RecordItemIndex(15));
            Validate.Exists(repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboMaterialValInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboFinish2Val'.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboFinish2ValInfo, new RecordItemIndex(16));
            Validate.Exists(repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboFinish2ValInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboHeatTreat2'.", repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboHeatTreat2Info, new RecordItemIndex(17));
            Validate.Exists(repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.CboHeatTreat2Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PLMMainForm.MainSplitPane.ItemPane.ItemNameLabel' and assigning its value to variable 'assemblyItemNumber'.", repo.PLMMainForm.MainSplitPane.ItemPane.ItemNameLabelInfo, new RecordItemIndex(18));
            assemblyItemNumber = repo.PLMMainForm.MainSplitPane.ItemPane.ItemNameLabel.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", assemblyItemNumber, repo.PLMMainForm.MainSplitPane.ItemPane.ItemNameLabel, false, new RecordItemIndex(19));
            
            Report.Screenshot(ReportLevel.Info, "User", ItemName2, repo.PLMMainForm.MainSplitPane.ItemPane.Attributes.AssemblyManufacturedAttributes.Self, false, new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLMMainForm.MainSplitPane.ItemPane.Save' at 39;9.", repo.PLMMainForm.MainSplitPane.ItemPane.SaveInfo, new RecordItemIndex(21));
            repo.PLMMainForm.MainSplitPane.ItemPane.Save.Click("39;9");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
