///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpchainMechDeployTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DelayModule recording.
    /// </summary>
    [TestModule("934447ef-6fdb-477a-9e3f-e220c11341f5", ModuleType.Recording, 1)]
    public partial class DelayModule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpchainMechDeployTestRepository repository.
        /// </summary>
        public static UpchainMechDeployTestRepository repo = UpchainMechDeployTestRepository.Instance;

        static DelayModule instance = new DelayModule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DelayModule()
        {
            delaytime = "10s";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DelayModule Instance
        {
            get { return instance; }
        }

#region Variables

        string _delaytime;

        /// <summary>
        /// Gets or sets the value of variable delaytime.
        /// </summary>
        [TestVariable("7d5481c2-7de4-4383-bf31-7e864902aa71")]
        public string delaytime
        {
            get { return _delaytime; }
            set { _delaytime = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for time from variable $delaytime.", new RecordItemIndex(0));
            Delay.Duration(Duration.Parse(delaytime), false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
