///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CamDesigner
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StationContextMenu recording.
    /// </summary>
    [TestModule("f3ba5a74-7f0c-4850-9abd-81e8339a1b98", ModuleType.Recording, 1)]
    public partial class StationContextMenu : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CamDesignerRepository repository.
        /// </summary>
        public static CamDesignerRepository repo = CamDesignerRepository.Instance;

        static StationContextMenu instance = new StationContextMenu();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StationContextMenu()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StationContextMenu Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Expand() on item 'CamDesignerUniversal.TreeView.LastProject'.", repo.CamDesignerUniversal.TreeView.LastProject.SelfInfo, new RecordItemIndex(0));
            repo.CamDesignerUniversal.TreeView.LastProject.Self.Expand();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'CamDesignerUniversal.TreeView.LastProject.Station.StationLabel' at Center.", repo.CamDesignerUniversal.TreeView.LastProject.Station.StationLabelInfo, new RecordItemIndex(1));
            repo.CamDesignerUniversal.TreeView.LastProject.Station.StationLabel.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesigner1.Remove' at 105;14.", repo.CamDesigner1.RemoveInfo, new RecordItemIndex(2));
            repo.CamDesigner1.Remove.Click("105;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesigner1.Rename' at 94;7.", repo.CamDesigner1.RenameInfo, new RecordItemIndex(3));
            repo.CamDesigner1.Rename.Click("94;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesignerUniversal.TreeView.LastProject.Station.StationTextbox' at Center.", repo.CamDesignerUniversal.TreeView.LastProject.Station.StationTextboxInfo, new RecordItemIndex(4));
            repo.CamDesignerUniversal.TreeView.LastProject.Station.StationTextbox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1'.", new RecordItemIndex(5));
            Keyboard.Press("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Escape}'.", new RecordItemIndex(6));
            Keyboard.Press("{Escape}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Test') on item 'CamDesignerUniversal.TreeView.LastProject.Station.StationLabel'.", repo.CamDesignerUniversal.TreeView.LastProject.Station.StationLabelInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.CamDesignerUniversal.TreeView.LastProject.Station.StationLabelInfo, "Text", "Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'CamDesignerUniversal.TreeView.LastProject.Station.StationLabel' at Center.", repo.CamDesignerUniversal.TreeView.LastProject.Station.StationLabelInfo, new RecordItemIndex(8));
            repo.CamDesignerUniversal.TreeView.LastProject.Station.StationLabel.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesigner1.Rename' at 27;8.", repo.CamDesigner1.RenameInfo, new RecordItemIndex(9));
            repo.CamDesigner1.Rename.Click("27;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesignerUniversal.TreeView.LastProject.Station.StationTextbox' at Center.", repo.CamDesignerUniversal.TreeView.LastProject.Station.StationTextboxInfo, new RecordItemIndex(10));
            repo.CamDesignerUniversal.TreeView.LastProject.Station.StationTextbox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}{Right}{Right}{Right}{Right}1'.", new RecordItemIndex(11));
            Keyboard.Press("{Right}{Right}{Right}{Right}{Right}1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(12));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Test1') on item 'CamDesignerUniversal.TreeView.LastProject.Station.StationLabel'.", repo.CamDesignerUniversal.TreeView.LastProject.Station.StationLabelInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.CamDesignerUniversal.TreeView.LastProject.Station.StationLabelInfo, "Text", "Test1");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
