///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CamDesigner
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateArmLayout recording.
    /// </summary>
    [TestModule("c77282a5-b7ce-4fbb-928d-81e86b1ef414", ModuleType.Recording, 1)]
    public partial class ValidateArmLayout : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CamDesignerRepository repository.
        /// </summary>
        public static CamDesignerRepository repo = CamDesignerRepository.Instance;

        static ValidateArmLayout instance = new ValidateArmLayout();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateArmLayout()
        {
            Value = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateArmLayout Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Value.
        /// </summary>
        [TestVariable("c15806e5-2703-4bce-ab25-96518973cb7b")]
        public string Value
        {
            get { return repo.Value; }
            set { repo.Value = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Value) on item 'CamDesigner.SelectedArmLayoutText'.", repo.CamDesigner.SelectedArmLayoutTextInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.CamDesigner.SelectedArmLayoutTextInfo, "Text", Value);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
