///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GlobalServicesPlatformTesting
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AssetDocument recording.
    /// </summary>
    [TestModule("5c68ca3a-063c-438f-8102-e1155a931231", ModuleType.Recording, 1)]
    public partial class AssetDocument : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GlobalServicesPlatformTestingRepository repository.
        /// </summary>
        public static GlobalServicesPlatformTestingRepository repo = GlobalServicesPlatformTestingRepository.Instance;

        static AssetDocument instance = new AssetDocument();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AssetDocument()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AssetDocument Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.WsWorkspace.LiTagDocuments' at Center.", repo.OsVCLogin.WsWorkspace.LiTagDocumentsInfo, new RecordItemIndex(0));
            repo.OsVCLogin.WsWorkspace.LiTagDocuments.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.WsWorkspace.ATag2522714125227141' at Center.", repo.OsVCLogin.WsWorkspace.ATag2522714125227141Info, new RecordItemIndex(1));
            repo.OsVCLogin.WsWorkspace.ATag2522714125227141.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(2));
            Delay.Duration(7000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OsVCLogin.WsWorkspace.ATag2522714125227141' at Center.", repo.OsVCLogin.WsWorkspace.ATag2522714125227141Info, new RecordItemIndex(3));
            repo.OsVCLogin.WsWorkspace.ATag2522714125227141.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(4));
            Delay.Duration(7000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.WsWorkspace.ATag25226778ABC10PROPULSIONASSEMBL' at Center.", repo.OsVCLogin.WsWorkspace.ATag25226778ABC10PROPULSIONASSEMBLInfo, new RecordItemIndex(5));
            repo.OsVCLogin.WsWorkspace.ATag25226778ABC10PROPULSIONASSEMBL.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(6));
            Delay.Duration(7000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OsVCLogin.WsWorkspace.ATag25226778ABC10PROPULSIONASSEMBL' at Center.", repo.OsVCLogin.WsWorkspace.ATag25226778ABC10PROPULSIONASSEMBLInfo, new RecordItemIndex(7));
            repo.OsVCLogin.WsWorkspace.ATag25226778ABC10PROPULSIONASSEMBL.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.WsWorkspace.ATag25226876ACC10S100UNLOAD' at Center.", repo.OsVCLogin.WsWorkspace.ATag25226876ACC10S100UNLOADInfo, new RecordItemIndex(8));
            repo.OsVCLogin.WsWorkspace.ATag25226876ACC10S100UNLOAD.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(9));
            Delay.Duration(7000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.OsVCLogin.Self, false, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'OsVCLogin.WsWorkspace.DownloadDocument25226876AC00000AP' at Center.", repo.OsVCLogin.WsWorkspace.DownloadDocument25226876AC00000APInfo, new RecordItemIndex(11));
            repo.OsVCLogin.WsWorkspace.DownloadDocument25226876AC00000AP.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.WsWorkspace.DownloadDocument25226876AC00000AP' at UpperLeft.", repo.OsVCLogin.WsWorkspace.DownloadDocument25226876AC00000APInfo, new RecordItemIndex(12));
            repo.OsVCLogin.WsWorkspace.DownloadDocument25226876AC00000AP.Click(Location.UpperLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'OsVCLogin.B0AB436E73256403259CE203892542D6'", repo.OsVCLogin.B0AB436E73256403259CE203892542D6Info, new ActionTimeout(10000), new RecordItemIndex(13));
            repo.OsVCLogin.B0AB436E73256403259CE203892542D6Info.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(14));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.B0AB436E73256403259CE203892542D6' at Center.", repo.OsVCLogin.B0AB436E73256403259CE203892542D6Info, new RecordItemIndex(15));
            repo.OsVCLogin.B0AB436E73256403259CE203892542D6.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.OsVCLogin.B0AB436E73256403259CE203892542D6, false, new RecordItemIndex(16));
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'OsVCLogin.B0AB436E73256403259CE203892542D6'.", repo.OsVCLogin.B0AB436E73256403259CE203892542D6Info, new RecordItemIndex(17));
            Host.Current.CloseApplication(repo.OsVCLogin.B0AB436E73256403259CE203892542D6, new Duration(0));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
