///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GlobalServicesPlatformTesting
{
    public partial class CreateSalesforceOpportunity
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CheckADUserandEnterCreds()
        {
        	//if(!System.Environment.UserName.ToLower().Contains("ranorexrt"))
        	//{
        		Report.Info("Signed in as " + System.Environment.UserName + " entering credentials");
        		repo.HttpsIdpAtsautomationComNtlmAuth.UserName.Click();
            	Delay.Milliseconds(200);
            	repo.HttpsIdpAtsautomationComNtlmAuth.UserName.PressKeys("ranorexrt");
            	Delay.Milliseconds(200);
            	repo.HttpsIdpAtsautomationComNtlmAuth.Password.Click();
            	Delay.Milliseconds(200);
            	repo.HttpsIdpAtsautomationComNtlmAuth.Password.PressKeys("_Dd}fTWA*b6P2tm5");
            	Delay.Milliseconds(200);
            	repo.HttpsIdpAtsautomationComNtlmAuth.SignInButton.Click();
            	Delay.Milliseconds(200);
        	//}
        	//else
        	//{
        	//	Report.Info("Signed in as ranorexrt");
        	//}
        }

    }
}
