///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GlobalServicesPlatformTesting
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The HamburgerMenu recording.
    /// </summary>
    [TestModule("5c840c71-973d-4297-8692-441a6d284799", ModuleType.Recording, 1)]
    public partial class HamburgerMenu : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GlobalServicesPlatformTestingRepository repository.
        /// </summary>
        public static GlobalServicesPlatformTestingRepository repo = GlobalServicesPlatformTestingRepository.Instance;

        static HamburgerMenu instance = new HamburgerMenu();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HamburgerMenu()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HamburgerMenu Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.HamburgerMenu' at Center.", repo.OsVCLogin.HamburgerMenuInfo, new RecordItemIndex(0));
            repo.OsVCLogin.HamburgerMenu.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ExpandHome' at Center.", repo.OsVCLogin.ExpandHomeInfo, new RecordItemIndex(1));
            repo.OsVCLogin.ExpandHome.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ExpandAnalytics' at Center.", repo.OsVCLogin.ExpandAnalyticsInfo, new RecordItemIndex(2));
            repo.OsVCLogin.ExpandAnalytics.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ExpandContacts' at Center.", repo.OsVCLogin.ExpandContactsInfo, new RecordItemIndex(3));
            repo.OsVCLogin.ExpandContacts.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ExpandAccounts' at Center.", repo.OsVCLogin.ExpandAccountsInfo, new RecordItemIndex(4));
            repo.OsVCLogin.ExpandAccounts.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ExpandAssets' at Center.", repo.OsVCLogin.ExpandAssetsInfo, new RecordItemIndex(5));
            repo.OsVCLogin.ExpandAssets.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ExpandAnswers' at Center.", repo.OsVCLogin.ExpandAnswersInfo, new RecordItemIndex(6));
            repo.OsVCLogin.ExpandAnswers.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ExpandSupportRequests' at Center.", repo.OsVCLogin.ExpandSupportRequestsInfo, new RecordItemIndex(7));
            repo.OsVCLogin.ExpandSupportRequests.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ExpandServiceActivity' at Center.", repo.OsVCLogin.ExpandServiceActivityInfo, new RecordItemIndex(8));
            repo.OsVCLogin.ExpandServiceActivity.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.OsVCLogin.Self, false, new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.HamburgerMenu' at Center.", repo.OsVCLogin.HamburgerMenuInfo, new RecordItemIndex(10));
            repo.OsVCLogin.HamburgerMenu.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
