///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GlobalServicesPlatformTesting
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginOCC recording.
    /// </summary>
    [TestModule("a254e111-a0ca-4a21-ac9b-98c1cd2bb626", ModuleType.Recording, 1)]
    public partial class LoginOCC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GlobalServicesPlatformTestingRepository repository.
        /// </summary>
        public static GlobalServicesPlatformTestingRepository repo = GlobalServicesPlatformTestingRepository.Instance;

        static LoginOCC instance = new LoginOCC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginOCC()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginOCC Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSStoreLogin.OELoginInput' at Center.", repo.ATSStoreLogin.OELoginInputInfo, new RecordItemIndex(0));
            repo.ATSStoreLogin.OELoginInput.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'ranorexrt@atsautomation.com' on item 'ATSStoreLogin.OELoginInput'.", repo.ATSStoreLogin.OELoginInputInfo, new RecordItemIndex(1));
            repo.ATSStoreLogin.OELoginInput.Element.SetAttributeValue("TagValue", "ranorexrt@atsautomation.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSStoreLogin.OELoginPasswordInput' at Center.", repo.ATSStoreLogin.OELoginPasswordInputInfo, new RecordItemIndex(2));
            repo.ATSStoreLogin.OELoginPasswordInput.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Welcome1' on item 'ATSStoreLogin.OELoginPasswordInput'.", repo.ATSStoreLogin.OELoginPasswordInputInfo, new RecordItemIndex(3));
            repo.ATSStoreLogin.OELoginPasswordInput.Element.SetAttributeValue("TagValue", "Welcome1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSStoreLogin.OeLoginButton' at Center.", repo.ATSStoreLogin.OeLoginButtonInfo, new RecordItemIndex(4));
            repo.ATSStoreLogin.OeLoginButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
