///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GlobalServicesPlatformTesting
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ServiceActivitySearch recording.
    /// </summary>
    [TestModule("d3700e2e-ddf1-4bfa-8115-bb99258d0f94", ModuleType.Recording, 1)]
    public partial class ServiceActivitySearch : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GlobalServicesPlatformTestingRepository repository.
        /// </summary>
        public static GlobalServicesPlatformTestingRepository repo = GlobalServicesPlatformTestingRepository.Instance;

        static ServiceActivitySearch instance = new ServiceActivitySearch();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ServiceActivitySearch()
        {
            varSearchID = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ServiceActivitySearch Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varSearchID.
        /// </summary>
        [TestVariable("57f133d5-e7b3-4483-ad89-d2438ec62cd8")]
        public string varSearchID
        {
            get { return repo.varSearchID; }
            set { repo.varSearchID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.HamburgerMenu' at Center.", repo.OsVCLogin.HamburgerMenuInfo, new RecordItemIndex(0));
            repo.OsVCLogin.HamburgerMenu.Click();
            Delay.Milliseconds(200);
            
            IsServiceActivitySearchExpanded();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.ServiceActivitySearch' at Center.", repo.OsVCLogin.ServiceActivitySearchInfo, new RecordItemIndex(2));
            repo.OsVCLogin.ServiceActivitySearch.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.Search1' at Center.", repo.OsVCLogin.Search1Info, new RecordItemIndex(3));
            repo.OsVCLogin.Search1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'OsVCLogin.ServiceActivityIDFirstRow'", repo.OsVCLogin.ServiceActivityIDFirstRowInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.OsVCLogin.ServiceActivityIDFirstRowInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'OsVCLogin.ServiceActivityIDFirstRow' and assigning its value to variable 'varSearchID'.", repo.OsVCLogin.ServiceActivityIDFirstRowInfo, new RecordItemIndex(5));
            varSearchID = repo.OsVCLogin.ServiceActivityIDFirstRow.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'OsVCLogin.ServiceActivityIDFirstRow' at Center.", repo.OsVCLogin.ServiceActivityIDFirstRowInfo, new RecordItemIndex(6));
            repo.OsVCLogin.ServiceActivityIDFirstRow.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OsVCLogin.ServiceActivityIDFirstRow' at Center.", repo.OsVCLogin.ServiceActivityIDFirstRowInfo, new RecordItemIndex(7));
            repo.OsVCLogin.ServiceActivityIDFirstRow.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'OsVCLogin.WsWorkspace.BillingMethod'", repo.OsVCLogin.WsWorkspace.BillingMethodInfo, new ActionTimeout(30000), new RecordItemIndex(8));
            repo.OsVCLogin.WsWorkspace.BillingMethodInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'OsVCLogin.SpanTag780'.", repo.OsVCLogin.SpanTag780Info, new RecordItemIndex(9));
            Validate.Exists(repo.OsVCLogin.SpanTag780Info);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.OsVCLogin.Self, false, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.CloseTab2' at Center.", repo.OsVCLogin.CloseTab2Info, new RecordItemIndex(11));
            repo.OsVCLogin.CloseTab2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(12));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OsVCLogin.CloseTab' at Center.", repo.OsVCLogin.CloseTabInfo, new RecordItemIndex(13));
            repo.OsVCLogin.CloseTab.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
