///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EnvironmentSwitcherConfiguration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateUpchainAdded recording.
    /// </summary>
    [TestModule("5f4cb926-f112-48fd-b9e8-f73199926111", ModuleType.Recording, 1)]
    public partial class ValidateUpchainAdded : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EnvironmentSwitcherConfigurationRepository repository.
        /// </summary>
        public static EnvironmentSwitcherConfigurationRepository repo = EnvironmentSwitcherConfigurationRepository.Instance;

        static ValidateUpchainAdded instance = new ValidateUpchainAdded();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateUpchainAdded()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateUpchainAdded Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SolidWorks2016.Element130076112' at 15;20.", repo.SolidWorks2016.Element130076112Info, new RecordItemIndex(0));
            repo.SolidWorks2016.Element130076112.MoveTo(new Location(Element130076112_Screenshot1, "15;20", Element130076112_Screenshot1_Options));
            Delay.Milliseconds(10550);
            
        }

#region Image Feature Data
        CompressedImage Element130076112_Screenshot1
        { get { return repo.SolidWorks2016.Element130076112Info.GetScreenshot1(new Rectangle(1, 168, 25, 25)); } }

        Imaging.FindOptions Element130076112_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
