///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DDM_Lite_Full_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DDM_Lite_Oregon_File_Search recording.
    /// </summary>
    [TestModule("5b6138cc-e4c8-4e34-bf25-886e6d6a475f", ModuleType.Recording, 1)]
    public partial class DDM_Lite_Oregon_File_Search : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DDM_Lite_Full_TestRepository repository.
        /// </summary>
        public static DDM_Lite_Full_TestRepository repo = DDM_Lite_Full_TestRepository.Instance;

        static DDM_Lite_Oregon_File_Search instance = new DDM_Lite_Oregon_File_Search();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DDM_Lite_Oregon_File_Search()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DDM_Lite_Oregon_File_Search Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCa01a9001PgmisDeploymentDEVDDM.FileSearchRibbonButton' at Center.", repo.FormCa01a9001PgmisDeploymentDEVDDM.FileSearchRibbonButtonInfo, new RecordItemIndex(0));
            repo.FormCa01a9001PgmisDeploymentDEVDDM.FileSearchRibbonButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '29672210' on item 'FormCa01a9001PgmisDeploymentDEVDDM.FileNameTextBox'.", repo.FormCa01a9001PgmisDeploymentDEVDDM.FileNameTextBoxInfo, new RecordItemIndex(1));
            repo.FormCa01a9001PgmisDeploymentDEVDDM.FileNameTextBox.Element.SetAttributeValue("Text", "29672210");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCa01a9001PgmisDeploymentDEVDDM.RunSearchRibbonButton' at Center.", repo.FormCa01a9001PgmisDeploymentDEVDDM.RunSearchRibbonButtonInfo, new RecordItemIndex(2));
            repo.FormCa01a9001PgmisDeploymentDEVDDM.RunSearchRibbonButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCa01a9001PgmisDeploymentDEVDDM.Cell2479312' at Center.", repo.FormCa01a9001PgmisDeploymentDEVDDM.Cell2479312Info, new RecordItemIndex(3));
            repo.FormCa01a9001PgmisDeploymentDEVDDM.Cell2479312.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FormCa01a9001PgmisDeploymentDEVDDM.PreviewImageViewer'.", repo.FormCa01a9001PgmisDeploymentDEVDDM.PreviewImageViewerInfo, new RecordItemIndex(4));
            Validate.Exists(repo.FormCa01a9001PgmisDeploymentDEVDDM.PreviewImageViewerInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'FormCa01a9001PgmisDeploymentDEVDDM.PreviewImageViewer' at Center.", repo.FormCa01a9001PgmisDeploymentDEVDDM.PreviewImageViewerInfo, new RecordItemIndex(5));
            repo.FormCa01a9001PgmisDeploymentDEVDDM.PreviewImageViewer.DoubleClick();
            Delay.Milliseconds(200);
            
            SWPopUp();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EDrawings.MFile' at Center.", repo.EDrawings.MFileInfo, new RecordItemIndex(8));
            repo.EDrawings.MFile.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 200ms.", new RecordItemIndex(9));
            //Delay.Duration(200, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EDrawings2.ElementBg' at Center.", repo.EDrawings2.ElementBgInfo, new RecordItemIndex(10));
            repo.EDrawings2.ElementBg.Click();
            Delay.Milliseconds(200);
            
            DisablePopupWatcher();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCa01a9001PgmisDeploymentDEVDDM.OpenInSolidWorksRibbonButton' at Center.", repo.FormCa01a9001PgmisDeploymentDEVDDM.OpenInSolidWorksRibbonButtonInfo, new RecordItemIndex(12));
            repo.FormCa01a9001PgmisDeploymentDEVDDM.OpenInSolidWorksRibbonButton.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolidWorksMultipleVersions.SolidWorks2014' at Center.", repo.SolidWorksMultipleVersions.SolidWorks2014Info, new RecordItemIndex(13));
            //repo.SolidWorksMultipleVersions.SolidWorks2014.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 3m to exist. Associated repository item: 'SWdwg29672210'", repo.SWdwg29672210.SelfInfo, new ActionTimeout(180000), new RecordItemIndex(14));
            repo.SWdwg29672210.SelfInfo.WaitForExists(180000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SWdwg29672210.Self, false, new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking Close() on item 'SWdwg29672210'.", repo.SWdwg29672210.SelfInfo, new RecordItemIndex(16));
            repo.SWdwg29672210.Self.Close();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveModifiedDocuments.DontSave' at Center.", repo.SaveModifiedDocuments.DontSaveInfo, new RecordItemIndex(17));
            repo.SaveModifiedDocuments.DontSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.BacktoMain' at Center.", repo.FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.BacktoMainInfo, new RecordItemIndex(18));
            repo.FormCa01a9001PgmisDeploymentDEVDDM.PresentationHost.BacktoMain.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
