///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.CloseOrOpenApplication
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseApplicationOpenAsOperator recording.
    /// </summary>
    [TestModule("df376e3d-4769-45f4-a44d-a1e0a36e265c", ModuleType.Recording, 1)]
    public partial class CloseApplicationOpenAsOperator : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static CloseApplicationOpenAsOperator instance = new CloseApplicationOpenAsOperator();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseApplicationOpenAsOperator()
        {
            ATSDocumentProcessorApplicationPath = "\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS Document Processor\\app_files\\ATSDocumentProcessor.exe";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseApplicationOpenAsOperator Instance
        {
            get { return instance; }
        }

#region Variables

        string _ATSDocumentProcessorApplicationPath;

        /// <summary>
        /// Gets or sets the value of variable ATSDocumentProcessorApplicationPath.
        /// </summary>
        [TestVariable("de0f797a-bb85-4ec5-a0f4-8daa7df54344")]
        public string ATSDocumentProcessorApplicationPath
        {
            get { return _ATSDocumentProcessorApplicationPath; }
            set { _ATSDocumentProcessorApplicationPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'ATSDocumentProcessorForm'.", repo.ATSDocumentProcessorForm.SelfInfo, new RecordItemIndex(0));
            Host.Current.CloseApplication(repo.ATSDocumentProcessorForm.Self, new Duration(0));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(1));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Run application with file name from variable $ATSDocumentProcessorApplicationPath in normal mode. Return value bound to $.", new RecordItemIndex(2));
            Host.Local.RunApplication(ATSDocumentProcessorApplicationPath, "1", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS Document Processor\\app_files", false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ATSDocumentProcessorForm'", repo.ATSDocumentProcessorForm.SelfInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.ATSDocumentProcessorForm.SelfInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
