///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.CloseOrOpenApplication
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartApplication recording.
    /// </summary>
    [TestModule("7100968b-ceff-4a67-b91d-45b8e83aa92e", ModuleType.Recording, 1)]
    public partial class StartApplication : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static StartApplication instance = new StartApplication();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartApplication()
        {
            ATSDocumentProcessorApplicationPath = "\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS Document Processor\\app_files\\ATSDocumentProcessor.exe";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartApplication Instance
        {
            get { return instance; }
        }

#region Variables

        string _ATSDocumentProcessorApplicationPath;

        /// <summary>
        /// Gets or sets the value of variable ATSDocumentProcessorApplicationPath.
        /// </summary>
        [TestVariable("9d0e1a57-ff67-442c-b1d2-9d119175ad5b")]
        public string ATSDocumentProcessorApplicationPath
        {
            get { return _ATSDocumentProcessorApplicationPath; }
            set { _ATSDocumentProcessorApplicationPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application with file name from variable $ATSDocumentProcessorApplicationPath in normal mode. Return value bound to $.", new RecordItemIndex(0));
            Host.Local.RunApplication(ATSDocumentProcessorApplicationPath, "3", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS_DOCS_PROCESSOR", false);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'TrustManagerPromptUI.BtnInstall' at Center.", repo.TrustManagerPromptUI.BtnInstallInfo, new RecordItemIndex(1));
                repo.TrustManagerPromptUI.BtnInstall.Click();
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'ATSDocumentProcessorForm'", repo.ATSDocumentProcessorForm.SelfInfo, new ActionTimeout(60000), new RecordItemIndex(2));
            repo.ATSDocumentProcessorForm.SelfInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(3));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
