///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.ValidationRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateCheckedDrawings recording.
    /// </summary>
    [TestModule("7fc10c39-1be5-4f75-b048-eb543f8ec14e", ModuleType.Recording, 1)]
    public partial class ValidateCheckedDrawings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static ValidateCheckedDrawings instance = new ValidateCheckedDrawings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateCheckedDrawings()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateCheckedDrawings Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.ViewFiltersTab' at Center.", repo.ATSDocumentProcessorForm.Ribbon.ViewFiltersTabInfo, new RecordItemIndex(0));
            repo.ATSDocumentProcessorForm.Ribbon.ViewFiltersTab.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.OnlyChecked' at Center.", repo.ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.OnlyCheckedInfo, new RecordItemIndex(1));
            repo.ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.OnlyChecked.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.FileTypeMenu' at Center.", repo.ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.FileTypeMenuInfo, new RecordItemIndex(2));
            repo.ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.FileTypeMenu.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.ShowSLDDRW' at Center.", repo.SomeContextMenu.ShowSLDDRWInfo, new RecordItemIndex(3));
            repo.SomeContextMenu.ShowSLDDRW.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.ApplyFilters' at Center.", repo.ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.ApplyFiltersInfo, new RecordItemIndex(4));
            repo.ATSDocumentProcessorForm.Ribbon.ViewFilters.FileListFilters.ApplyFilters.Click();
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(5));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='AP25709816.SLDDRW') on item 'ATSDocumentProcessorForm.JobGrid.Row0'.", repo.ATSDocumentProcessorForm.JobGrid.Row0Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ATSDocumentProcessorForm.JobGrid.Row0Info, "Text", "AP25709816.SLDDRW");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='32609148.SLDDRW') on item 'ATSDocumentProcessorForm.JobGrid.Row1'.", repo.ATSDocumentProcessorForm.JobGrid.Row1Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ATSDocumentProcessorForm.JobGrid.Row1Info, "Text", "32609148.SLDDRW");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='AP25782901.SLDDRW') on item 'ATSDocumentProcessorForm.JobGrid.Row2'.", repo.ATSDocumentProcessorForm.JobGrid.Row2Info, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ATSDocumentProcessorForm.JobGrid.Row2Info, "Text", "AP25782901.SLDDRW");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='31655374.SLDDRW') on item 'ATSDocumentProcessorForm.JobGrid.Row3'.", repo.ATSDocumentProcessorForm.JobGrid.Row3Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ATSDocumentProcessorForm.JobGrid.Row3Info, "Text", "31655374.SLDDRW");
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ATSDocumentProcessorForm.Self, false, new RecordItemIndex(10));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
