///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.ValidationRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDownloadFilesError recording.
    /// </summary>
    [TestModule("f27d06d0-b808-45c6-b311-b48ed0834bdb", ModuleType.Recording, 1)]
    public partial class ValidateDownloadFilesError : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static ValidateDownloadFilesError instance = new ValidateDownloadFilesError();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDownloadFilesError()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDownloadFilesError Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Error setting output names. See the grid for more detail') on item 'ATSDocumentProcessorForm.MessageText'.", repo.ATSDocumentProcessorForm.MessageTextInfo, new RecordItemIndex(0));
            //Validate.AttributeEqual(repo.ATSDocumentProcessorForm.MessageTextInfo, "Text", "Error setting output names. See the grid for more detail");
            //Delay.Milliseconds(0);
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=199,Height=36}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation1CopyToWorkingFolder'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation1CopyToWorkingFolderInfo, new RecordItemIndex(1));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation1CopyToWorkingFolderInfo, Operation1CopyToWorkingFolder_Screenshot1, Operation1CopyToWorkingFolder_Screenshot1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_ad7212ca_rxlog1' with region {X=4,Y=2,Width=194,Height=35}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation2DeleteCustomProps'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation2DeleteCustomPropsInfo, new RecordItemIndex(2));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation2DeleteCustomPropsInfo, Operation2DeleteCustomProps_Validate_ad7212ca_rxlog1, Operation2DeleteCustomProps_Validate_ad7212ca_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_68232994_rxlog1' with region {X=2,Y=3,Width=188,Height=34}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation3WriteCustomProps'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation3WriteCustomPropsInfo, new RecordItemIndex(3));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation3WriteCustomPropsInfo, Operation3WriteCustomProps_Validate_68232994_rxlog1, Operation3WriteCustomProps_Validate_68232994_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_380fe536_rxlog1' with region {X=6,Y=4,Width=127,Height=29}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation4DownloadFilesFail'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation4DownloadFilesFailInfo, new RecordItemIndex(4));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation4DownloadFilesFailInfo, Operation4DownloadFilesFail_Validate_380fe536_rxlog1, Operation4DownloadFilesFail_Validate_380fe536_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_f2c0fc00_rxlog1' with region {X=11,Y=8,Width=82,Height=29}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation5'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation5Info, new RecordItemIndex(5));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation5Info, Operation5_Validate_f2c0fc00_rxlog1, Operation5_Validate_f2c0fc00_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_c2adb7a2_rxlog1' with region {X=9,Y=5,Width=161,Height=33}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation6ChangeTitleblocksNS'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation6ChangeTitleblocksNSInfo, new RecordItemIndex(6));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation6ChangeTitleblocksNSInfo, Operation6ChangeTitleblocksNS_Validate_c2adb7a2_rxlog1, Operation6ChangeTitleblocksNS_Validate_c2adb7a2_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_ff1d12ca_rxlog1' with region {X=6,Y=6,Width=145,Height=32}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation7ExportFormats'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation7ExportFormatsInfo, new RecordItemIndex(7));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation7ExportFormatsInfo, Operation7ExportFormats_Validate_ff1d12ca_rxlog1, Operation7ExportFormats_Validate_ff1d12ca_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_15e712ca_rxlog1' with region {X=12,Y=8,Width=127,Height=31}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation8CreateReport'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation8CreateReportInfo, new RecordItemIndex(8));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation8CreateReportInfo, Operation8CreateReport_Validate_15e712ca_rxlog1, Operation8CreateReport_Validate_15e712ca_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_d18912ca_rxlog1' with region {X=10,Y=7,Width=175,Height=29}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation9ChangeBalloonStyle'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation9ChangeBalloonStyleInfo, new RecordItemIndex(9));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation9ChangeBalloonStyleInfo, Operation9ChangeBalloonStyle_Validate_d18912ca_rxlog1, Operation9ChangeBalloonStyle_Validate_d18912ca_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_e85312ca_rxlog1' with region {X=11,Y=10,Width=179,Height=26}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation10InsertProprietaryNote'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation10InsertProprietaryNoteInfo, new RecordItemIndex(10));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation10InsertProprietaryNoteInfo, Operation10InsertProprietaryNote_Validate_e85312ca_rxlog1, Operation10InsertProprietaryNote_Validate_e85312ca_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Validate_a3f512ca_rxlog1' with region {X=12,Y=9,Width=180,Height=27}) on item 'ATSDocumentProcessorFormNonWPF.OperationsList.Operation11RunSWMacro'.", repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation11RunSWMacroInfo, new RecordItemIndex(11));
                //Validate.ContainsImage(repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation11RunSWMacroInfo, Operation11RunSWMacro_Validate_a3f512ca_rxlog1, Operation11RunSWMacro_Validate_a3f512ca_rxlog1_Options, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation1CopyToWorkingFolder_Screenshot1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation1CopyToWorkingFolderInfo.GetScreenshot1(new Rectangle(0, 0, 199, 36)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation1CopyToWorkingFolder_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation2DeleteCustomProps_Validate_ad7212ca_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation2DeleteCustomPropsInfo.GetValidate_ad7212ca_rxlog1(new Rectangle(4, 2, 194, 35)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation2DeleteCustomProps_Validate_ad7212ca_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation3WriteCustomProps_Validate_68232994_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation3WriteCustomPropsInfo.GetValidate_68232994_rxlog1(new Rectangle(2, 3, 188, 34)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation3WriteCustomProps_Validate_68232994_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation4DownloadFilesFail_Validate_380fe536_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation4DownloadFilesFailInfo.GetValidate_380fe536_rxlog1(new Rectangle(6, 4, 127, 29)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation4DownloadFilesFail_Validate_380fe536_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation5_Validate_f2c0fc00_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation5Info.GetValidate_f2c0fc00_rxlog1(new Rectangle(11, 8, 82, 29)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation5_Validate_f2c0fc00_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation6ChangeTitleblocksNS_Validate_c2adb7a2_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation6ChangeTitleblocksNSInfo.GetValidate_c2adb7a2_rxlog1(new Rectangle(9, 5, 161, 33)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation6ChangeTitleblocksNS_Validate_c2adb7a2_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation7ExportFormats_Validate_ff1d12ca_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation7ExportFormatsInfo.GetValidate_ff1d12ca_rxlog1(new Rectangle(6, 6, 145, 32)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation7ExportFormats_Validate_ff1d12ca_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation8CreateReport_Validate_15e712ca_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation8CreateReportInfo.GetValidate_15e712ca_rxlog1(new Rectangle(12, 8, 127, 31)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation8CreateReport_Validate_15e712ca_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation9ChangeBalloonStyle_Validate_d18912ca_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation9ChangeBalloonStyleInfo.GetValidate_d18912ca_rxlog1(new Rectangle(10, 7, 175, 29)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation9ChangeBalloonStyle_Validate_d18912ca_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation10InsertProprietaryNote_Validate_e85312ca_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation10InsertProprietaryNoteInfo.GetValidate_e85312ca_rxlog1(new Rectangle(11, 10, 179, 26)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation10InsertProprietaryNote_Validate_e85312ca_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Operation11RunSWMacro_Validate_a3f512ca_rxlog1
        { get { return repo.ATSDocumentProcessorFormNonWPF.OperationsList.Operation11RunSWMacroInfo.GetValidate_a3f512ca_rxlog1(new Rectangle(12, 9, 180, 27)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Operation11RunSWMacro_Validate_a3f512ca_rxlog1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
