///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CamDesigner
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditFinal recording.
    /// </summary>
    [TestModule("8342f478-4be2-44ef-8a93-b2ff4178705d", ModuleType.Recording, 1)]
    public partial class EditFinal : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CamDesignerRepository repository.
        /// </summary>
        public static CamDesignerRepository repo = CamDesignerRepository.Instance;

        static EditFinal instance = new EditFinal();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditFinal()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditFinal Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Row.
        /// </summary>
        [TestVariable("ff243cf6-fc28-453d-965b-d606c780e5eb")]
        public string Row
        {
            get { return repo.Row; }
            set { repo.Row = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotContains (Text!>'130') on item 'CamDesignerUniversal.Content.CamDetails.Detailed.DetailedFinal'.", repo.CamDesignerUniversal.Content.CamDetails.Detailed.DetailedFinalInfo, new RecordItemIndex(0));
            Validate.AttributeNotContains(repo.CamDesignerUniversal.Content.CamDetails.Detailed.DetailedFinalInfo, "Text", "130");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesignerUniversal.Content.CamDetails.Detailed.DetailedFinal' at Center.", repo.CamDesignerUniversal.Content.CamDetails.Detailed.DetailedFinalInfo, new RecordItemIndex(1));
            repo.CamDesignerUniversal.Content.CamDetails.Detailed.DetailedFinal.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '130{Return}'.", new RecordItemIndex(2));
            Keyboard.Press("130{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamDesigner.Header.SaveCurrent' at Center.", repo.CamDesigner.Header.SaveCurrentInfo, new RecordItemIndex(3));
            repo.CamDesigner.Header.SaveCurrent.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
