///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.NewRecipe.AddCustomProperties
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddParent recording.
    /// </summary>
    [TestModule("4079310a-a3c3-4478-9000-ad70d572b9f8", ModuleType.Recording, 1)]
    public partial class AddParent : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static AddParent instance = new AddParent();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddParent()
        {
            ColumnNameVar = "Parent";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddParent Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ColumnNameVar.
        /// </summary>
        [TestVariable("a3bf746f-26b2-4f8d-9359-40c35101a986")]
        public string ColumnNameVar
        {
            get { return repo.ColumnNameVar; }
            set { repo.ColumnNameVar = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ParentPropertyName.
        /// </summary>
        [TestVariable("b84bb6a1-02c7-4915-8e44-fea6a93a725e")]
        public string ParentPropertyName
        {
            get { return repo.ParentPropertyName; }
            set { repo.ParentPropertyName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreateLookupTable.LookupColumns1.DownScroll' at Center.", repo.CreateLookupTable.LookupColumns1.DownScrollInfo, new RecordItemIndex(0));
            repo.CreateLookupTable.LookupColumns1.DownScroll.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreateLookupTable.LookupColumns1.LookupColumnParentCheck' at 10;10.", repo.CreateLookupTable.LookupColumns1.LookupColumnParentCheckInfo, new RecordItemIndex(1));
            repo.CreateLookupTable.LookupColumns1.LookupColumnParentCheck.Click("10;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreateLookupTable.LookupColumns1.ParentProperty' at 58;10.", repo.CreateLookupTable.LookupColumns1.ParentPropertyInfo, new RecordItemIndex(2));
            repo.CreateLookupTable.LookupColumns1.ParentProperty.Click("58;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSDocumentProcessor1.ListItemText' at 115;8.", repo.ATSDocumentProcessor1.ListItemTextInfo, new RecordItemIndex(3));
            repo.ATSDocumentProcessor1.ListItemText.Click("115;8");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
