///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.NewRecipe.AddCustomProperties
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddReadProperties recording.
    /// </summary>
    [TestModule("21a84dbe-a7a3-4051-8422-9282bfc07b29", ModuleType.Recording, 1)]
    public partial class AddReadProperties : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static AddReadProperties instance = new AddReadProperties();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddReadProperties()
        {
            PropertyName = "{Capital}ASSEMBLY{Space}DESCRIPTION";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddReadProperties Instance
        {
            get { return instance; }
        }

#region Variables

        string _PropertyName;

        /// <summary>
        /// Gets or sets the value of variable PropertyName.
        /// </summary>
        [TestVariable("8ea36fbb-5446-4ac0-bbd1-05a5aa620095")]
        public string PropertyName
        {
            get { return _PropertyName; }
            set { _PropertyName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreateLookupTable.ReadProperties.AddReadProperty1' at 133;20.", repo.CreateLookupTable.ReadProperties.AddReadProperty1Info, new RecordItemIndex(0));
            repo.CreateLookupTable.ReadProperties.AddReadProperty1.Click("133;20");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PropertyName'.", new RecordItemIndex(1));
            Keyboard.Press(PropertyName);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CreateLookupTable.ReadProperties.AddReadPropertyButton' at 12;13.", repo.CreateLookupTable.ReadProperties.AddReadPropertyButtonInfo, new RecordItemIndex(2));
            repo.CreateLookupTable.ReadProperties.AddReadPropertyButton.Click("12;13");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
