///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexTraining
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddPass recording.
    /// </summary>
    [TestModule("a39502cd-39c1-4247-8061-576be2d2235d", ModuleType.Recording, 1)]
    public partial class AddPass : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexTrainingRepository repository.
        /// </summary>
        public static RanorexTrainingRepository repo = RanorexTrainingRepository.Instance;

        static AddPass instance = new AddPass();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddPass()
        {
            Title = "test";
            Username = "test";
            Note = "test";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddPass Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Title.
        /// </summary>
        [TestVariable("a5ff2489-e681-4392-9aa6-cf96b561bf9a")]
        public string Title
        {
            get { return repo.Title; }
            set { repo.Title = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Username.
        /// </summary>
        [TestVariable("257f157d-9fbd-42e4-83f7-a8697f75b0e1")]
        public string Username
        {
            get { return repo.Username; }
            set { repo.Username = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Note.
        /// </summary>
        [TestVariable("c625a77e-c126-4d35-876f-9da335eafb89")]
        public string Note
        {
            get { return repo.Note; }
            set { repo.Note = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.AddEntry' at 8;12.", repo.KeePass.AddEntryInfo, new RecordItemIndex(0));
            repo.KeePass.AddEntry.Click("8;12");
            
            // Driven from table in test suite
            Report.Log(ReportLevel.Info, "Keyboard", "Driven from table in test suite\r\nKey sequence from variable '$Title' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(1));
            repo.PwEntryForm.MTabEntry.Text.PressKeys(Title);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Username' with focus on 'PwEntryForm.MTabEntry.UserName'.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(2));
            repo.PwEntryForm.MTabEntry.UserName.PressKeys(Username);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Note' with focus on 'PwEntryForm.MTabEntry.Notes'.", repo.PwEntryForm.MTabEntry.NotesInfo, new RecordItemIndex(3));
            repo.PwEntryForm.MTabEntry.Notes.PressKeys(Note);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MBtnOK' at 29;12.", repo.PwEntryForm.MBtnOKInfo, new RecordItemIndex(4));
            repo.PwEntryForm.MBtnOK.Click("29;12");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
