///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexTraining
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewPass recording.
    /// </summary>
    [TestModule("f38b099d-d138-4ea2-b351-90537926dfaf", ModuleType.Recording, 1)]
    public partial class CreateNewPass : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexTrainingRepository repository.
        /// </summary>
        public static RanorexTrainingRepository repo = RanorexTrainingRepository.Instance;

        static CreateNewPass instance = new CreateNewPass();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewPass()
        {
            Password = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewPass Instance
        {
            get { return instance; }
        }

#region Variables

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("f51cd1c7-1dec-4907-8a6f-e80e92dfa9cb")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\KeePass Password Safe 2\\KeePass.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\KeePass Password Safe 2\\KeePass.exe", "", "C:\\Program Files (x86)\\KeePass Password Safe 2", false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'rx' with focus on 'KeePassLoginForm.Text'.", repo.KeePassLoginForm.TextInfo, new RecordItemIndex(1));
            repo.KeePassLoginForm.Text.PressKeys("rx");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePassLoginForm.MBtnOK' at 19;9.", repo.KeePassLoginForm.MBtnOKInfo, new RecordItemIndex(2));
            repo.KeePassLoginForm.MBtnOK.Click("19;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.AddEntry' at 8;12.", repo.KeePass.AddEntryInfo, new RecordItemIndex(3));
            repo.KeePass.AddEntry.Click("8;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Text' at 23;8.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(4));
            repo.PwEntryForm.MTabEntry.Text.Click("23;8");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(5));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("test");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.UserName' at 36;9.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(6));
            repo.PwEntryForm.MTabEntry.UserName.Click("36;9");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'PwEntryForm.MTabEntry.UserName'.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(7));
            repo.PwEntryForm.MTabEntry.UserName.PressKeys("test");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Notes' at 94;36.", repo.PwEntryForm.MTabEntry.NotesInfo, new RecordItemIndex(8));
            repo.PwEntryForm.MTabEntry.Notes.Click("94;36");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'PwEntryForm.MTabEntry.Notes'.", repo.PwEntryForm.MTabEntry.NotesInfo, new RecordItemIndex(9));
            repo.PwEntryForm.MTabEntry.Notes.PressKeys("test");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.MCbHidePassword' at 18;10.", repo.PwEntryForm.MTabEntry.MCbHidePasswordInfo, new RecordItemIndex(10));
            repo.PwEntryForm.MTabEntry.MCbHidePassword.Click("18;10");
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PwEntryForm.MTabEntry.Password' and assigning its value to variable 'Password'.", repo.PwEntryForm.MTabEntry.PasswordInfo, new RecordItemIndex(11));
            Password = repo.PwEntryForm.MTabEntry.Password.Element.GetAttributeValueText("Text");
            
            Report.Log(ReportLevel.Info, "User", Password, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MBtnOK' at 29;12.", repo.PwEntryForm.MBtnOKInfo, new RecordItemIndex(13));
            repo.PwEntryForm.MBtnOK.Click("29;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.Close' at 20;11.", repo.KeePass.CloseInfo, new RecordItemIndex(14));
            repo.KeePass.Close.Click("20;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePassDialogs.ButtonDiscardChanges' at 82;33.", repo.KeePassDialogs.ButtonDiscardChangesInfo, new RecordItemIndex(15));
            repo.KeePassDialogs.ButtonDiscardChanges.Click("82;33");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
