///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PLM_Mechanical_Deploy_Test
{
    public partial class RequisitionWizard
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Report_Log()
        {
        	TopItemNumber = TopItemNumber.Substring(0, 9);
            Report.Log(ReportLevel.Info, "User", "Top item number set to " + TopItemNumber);
        }

        public void ChildIndexPlusOne()
        {
            int index = Int32.Parse(ChildCount)+ 1;
        	ChildCount = Convert.ToString(index);
        }

        public void ValidateAutoMove(string message)
        {
            var split = message.Split(new[] { "Qty <b>1.00</b>" }, StringSplitOptions.None);
            var expectedNumberOfInstances = 2;
            if (split.Length == expectedNumberOfInstances + 1)
            {
                // Valid
                Ranorex.Report.Log(Ranorex.ReportLevel.Success, "AutoMove message passed validation");
            } 
            else
            {
            	// Fail
            	Ranorex.Report.Log(Ranorex.ReportLevel.Failure, "AutoMove message failed validation");
            }
        }

    }
}