///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Document_Processor.EditRecipe
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GetRecipeVersion recording.
    /// </summary>
    [TestModule("03516334-2519-4a78-83a8-9344a4a11567", ModuleType.Recording, 1)]
    public partial class GetRecipeVersion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ATS_Document_Processor.ATS_Document_ProcessorRepository repository.
        /// </summary>
        public static global::ATS_Document_Processor.ATS_Document_ProcessorRepository repo = global::ATS_Document_Processor.ATS_Document_ProcessorRepository.Instance;

        static GetRecipeVersion instance = new GetRecipeVersion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GetRecipeVersion()
        {
            RecipeID = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GetRecipeVersion Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable RecipeID.
        /// </summary>
        [TestVariable("1297dd49-fe8d-44e1-8035-a8725e94bf96")]
        public string RecipeID
        {
            get { return repo.RecipeID; }
            set { repo.RecipeID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'ATSDocumentProcessorForm' and assigning its value to variable 'RecipeID'.", repo.ATSDocumentProcessorForm.SelfInfo, new RecordItemIndex(0));
            RecipeID = repo.ATSDocumentProcessorForm.Self.Element.GetAttributeValueText("Title");
            
            Report.Log(ReportLevel.Info, "User", RecipeID, new RecordItemIndex(1));
            
            TrimRecipeVersion();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
